---
sidebar: sidebar 
permalink: br-limitations-kubernetes.html 
keywords: limitations, known, NetApp Backup and Recovery, Kubernetes, applications, workloads 
summary: 'Veuillez prendre connaissance de ces limitations de NetApp Backup and Recovery avant d"utiliser Backup and Recovery dans votre environnement.' 
---
= Limitations connues de NetApp Backup and Recovery pour les charges de travail Kubernetes
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Examinez les limitations actuelles et les solutions de contournement pour les charges de travail Kubernetes dans NetApp Backup and Recovery.



[[limitation-in-the-backup-and-recovery-preview-for-netapp-console-local-deployment]]
== Limitation dans l'aperçu de NetApp Backup and Recovery pour le déploiement local de la NetApp Console

Dans la version préliminaire de Backup and Recovery pour le déploiement local de NetApp Console, les sauvegardes vers le stockage objet sont prises en charge uniquement pour les destinations ONTAP S3 et StorageGRID. L'archivage des sauvegardes n'est pas pris en charge dans cette version préliminaire.



[[changing-the-protection-policy-for-an-application]]
== Modification de la politique de protection d'une application

Si vous modifiez la politique de protection d'une application pour utiliser un compartiment différent ou une cible de réplication secondaire, la protection peut échouer.

*Solution de contournement* : Supprimez l’application et ajoutez-la à nouveau.



[[3-2-1-protection-policy-configuration-limitation]]
== Limitation de la configuration de la politique de protection 3-2-1

Si vous créez une politique de protection 3-2-1 qui planifie les sauvegardes du stockage d'objets séparément de la réplication vers le stockage secondaire, la protection peut se bloquer.

*Solution de contournement* : Supprimez l’application, ajoutez-la à nouveau, puis protégez-la avec une politique de protection différente.
