---
sidebar: sidebar 
permalink: br-limitations-kvm.html 
keywords: backing up, back up, backup, backup application data, Amazon Web services, AWS, NetApp Backup and Recovery, KVM, SAP HANA database, virtual machine, vm 
summary: Cette version de NetApp Backup and Recovery présente les limitations connues suivantes. 
---
= Limitations connues de NetApp Backup and Recovery pour les charges de travail KVM
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Consultez les limitations actuelles des charges de travail KVM dans NetApp Backup and Recovery.

Les actions et configurations suivantes ne sont pas prises en charge pour les charges de travail KVM dans NetApp Backup and Recovery :



[[unsupported-actions]]
== Actions non prises en charge

Les actions suivantes ne sont pas prises en charge :

* Dans la version préliminaire de Backup and Recovery pour le déploiement local de NetApp Console, les sauvegardes vers le stockage objet sont prises en charge uniquement pour les destinations ONTAP S3 et StorageGRID. L'archivage des sauvegardes n'est pas pris en charge dans cette version préliminaire.
* Cloner, monter ou démonter des machines virtuelles
* Protéger les machines virtuelles stockées sur SAN
* Protéger les applications
* Créer des sauvegardes définies par l'utilisateur (seules les sauvegardes lancées à partir de la NetApp Console sont prises en charge)




[[unsupported-configurations]]
== Configurations non prises en charge

Les configurations suivantes ne sont pas prises en charge :

* Contrôle d'accès basé sur les rôles (RBAC)
* Disques directement connectés à l'hôte KVM
* Disques répartis sur plusieurs points de montage ou partages NFS
* Format de disque RAW
* Types de pools de stockage autres que NetFS (seul NetFS est pris en charge)




[[troubleshooting-notes]]
== Notes de dépannage

Veuillez noter les points suivants lorsque vous utilisez des charges de travail KVM avec NetApp Backup and Recovery.

* Les sauvegardes peuvent échouer si l'agent invité QEMU n'est pas exécuté sur une machine virtuelle protégée. Pour éviter ce problème, assurez-vous que le  `qemu-guest-agent` démon est en cours d'exécution sur la machine virtuelle avant de lancer la sauvegarde.

