---
sidebar: sidebar 
permalink: br-limitations-kvm.html 
keywords: backing up, back up, backup, backup application data, Amazon Web services, AWS, NetApp Backup and Recovery, Oracle database, KVM, SAP HANA database, virtual machine, vm 
summary: Cette version de NetApp Backup and Recovery présente les limitations connues suivantes. 
---
= Limitations connues avec NetApp Backup and Recovery pour les charges de travail KVM
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Les plates-formes, appareils ou fonctionnalités qui ne fonctionnent pas ou ne fonctionnent pas bien avec cette version sont répertoriés ici.  Lisez attentivement ces limitations.

Les actions et configurations suivantes ne sont pas prises en charge dans la version d'aperçu privée des charges de travail KVM dans NetApp Backup and Recovery :



== Actions non prises en charge

Les actions suivantes ne sont pas prises en charge dans la version d’aperçu privée :

* Cloner, monter ou démonter des machines virtuelles
* Restaurer les machines virtuelles vers un autre emplacement
* Protéger les machines virtuelles stockées sur SAN
* Protéger les applications
* Modifier les groupes de protection
* Créer des groupes de protection à l'aide de machines virtuelles provenant de plusieurs hôtes KVM
* Créer des sauvegardes définies par l'utilisateur (seules les sauvegardes lancées à partir de la console NetApp sont prises en charge)




== Configurations non prises en charge

Les configurations suivantes ne sont pas prises en charge :

* Contrôle d'accès basé sur les rôles (RBAC)
* Disques directement connectés à l'hôte KVM
* Disques répartis sur plusieurs points de montage ou partages NFS
* Format de disque RAW
* Types de pools de stockage autres que NetFS (seul NetFS est pris en charge)




== Comptes de NetApp Console hérités non pris en charge

Les comptes de NetApp Console hérités ne prennent pas en charge les fonctionnalités requises pour protéger les charges de travail KVM.  Vérifiez si vous utilisez un compte hérité dans l’interface utilisateur Web de la console.  Si vous disposez d’un compte de console hérité, créez un nouveau compte avant de protéger les charges de travail KVM.

.Étapes
. Dans le menu de la NetApp Console , sélectionnez *Administration > Identité et accès*.
. Sous *Organisation*, vérifiez si un *ID de compte* est affiché à côté de l'ID de l'organisation.
+
Si un *ID de compte* s'affiche, vous utilisez un compte hérité.

. Si vous utilisez un compte hérité, procédez comme suit :
+
.. Déconnectez-vous de la console, puis accédez à la https://console.netapp.com/["Page de connexion à la console"^] .
.. Sélectionnez *S'inscrire* pour créer un nouveau compte.



