---
sidebar: sidebar 
permalink: br-limitations-kvm.html 
keywords: backing up, back up, backup, backup application data, Amazon Web services, AWS, NetApp Backup and Recovery, Oracle database, KVM, SAP HANA database, virtual machine, vm 
summary: Cette version de NetApp Backup and Recovery présente les limitations connues suivantes. 
---
= Limitations connues avec NetApp Backup and Recovery pour les charges de travail KVM
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Les limitations connues identifient les plates-formes, les appareils ou les fonctions qui ne sont pas pris en charge par cette version du produit ou qui n'interagissent pas correctement avec elle. Examinez attentivement ces limitations.

Les actions et configurations suivantes ne sont pas prises en charge dans la version d'aperçu privée des charges de travail KVM dans NetApp Backup and Recovery :



== Actions non prises en charge

Les actions suivantes ne sont pas prises en charge dans la version d’aperçu privée :

* Cloner, monter ou démonter des machines virtuelles
* Restaurer les machines virtuelles vers un autre emplacement
* Protéger les machines virtuelles stockées sur SAN
* Protéger les applications
* Sauvegarde ou restauration à partir de magasins d'objets
* Modifier les groupes de protection
* Créer des groupes de protection à l'aide de machines virtuelles provenant de plusieurs hôtes KVM
* Créer des sauvegardes définies par l'utilisateur (seules les sauvegardes lancées à partir de la console NetApp sont prises en charge)




== Configurations non prises en charge

Les configurations suivantes ne sont pas prises en charge :

* Contrôle d'accès basé sur les rôles (RBAC)
* Disques directement connectés à l'hôte KVM
* Disques répartis sur plusieurs points de montage ou partages NFS
* Format de disque RAW
* Types de pools de stockage autres que NetFS (seul NetFS est pris en charge)

