---
sidebar: sidebar 
permalink: br-limitations-hyperv.html 
keywords: backing up, back up, backup, backup application data, Amazon Web services, AWS, NetApp Backup and Recovery, Oracle database, Hyper-V, SAP HANA database, virtual machine, vm 
summary: NetApp Backup and Recovery doit d’abord découvrir les données pour que vous puissiez utiliser le service.  Lors de la découverte, NetApp Backup and Recovery analyse tous les volumes et fichiers des systèmes de votre organisation. 
---
= Limitations connues de NetApp Backup and Recovery pour les charges de travail Hyper-V
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Les plates-formes, appareils ou fonctionnalités qui ne fonctionnent pas ou ne fonctionnent pas bien avec cette version sont répertoriés ici.  Lisez attentivement ces limitations.



== Actions non prises en charge

Les actions suivantes ne sont pas prises en charge dans la version d'aperçu privée des charges de travail Hyper-V dans NetApp Backup and Recovery :

* Créer des groupes de ressources
* Disques répartis (sur plusieurs partages CIFS)
* Protéger les machines virtuelles via SAN
* Restaurer à partir du magasin d'objets
* Protégez les hôtes Hyper-V mis en cluster à l'aide de System Center Virtual Machine Manager (SCVMM)




== Comptes de NetApp Console hérités non pris en charge

Les comptes de NetApp Console hérités ne prennent pas en charge les fonctionnalités requises pour protéger les charges de travail Hyper-V.  Vérifiez si vous utilisez un compte hérité dans l’interface utilisateur Web de la console.  Si vous disposez d’un compte de console hérité, créez un nouveau compte avant de protéger les charges de travail Hyper-V.

.Étapes
. Dans le menu de la NetApp Console , sélectionnez *Administration > Identité et accès*.
. Sous *Organisation*, vérifiez si un *ID de compte* est affiché à côté de l'ID de l'organisation.
+
Si un *ID de compte* s'affiche, vous utilisez un compte hérité.

. Si vous utilisez un compte hérité, procédez comme suit :
+
.. Déconnectez-vous de la console, puis accédez à la https://console.netapp.com/["Page de connexion à la console"^] .
.. Sélectionnez *S'inscrire* pour créer un nouveau compte.



