---
sidebar: sidebar 
permalink: br-limitations-vmware.html 
keywords: backing up, back up, backup, backup application data, Amazon Web services, AWS, NetApp Backup and Recovery, vmware, vcenter 
summary: 'Veuillez prendre connaissance de ces limitations de NetApp Backup and Recovery avant d"utiliser Backup and Recovery dans votre environnement.' 
---
= Limitations connues des charges de travail VMware dans NetApp Backup and Recovery
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Veuillez prendre connaissance de ces limitations avant d'utiliser NetApp Backup and Recovery pour les charges de travail VMware.

NetApp Backup and Recovery ne prend pas en charge les actions suivantes pour les charges de travail VMware :

* Dans la version préliminaire de Backup and Recovery pour le déploiement local de NetApp Console, les sauvegardes vers le stockage objet sont prises en charge uniquement pour les destinations ONTAP S3 et StorageGRID. L'archivage des sauvegardes n'est pas pris en charge dans cette version préliminaire.
* Prise en charge de vVol
* Intégration de courrier électronique
* Prise en charge du contrôle d'accès basé sur les rôles (RBAC)

