---
sidebar: sidebar 
permalink: br-limitations-hyperv.html 
keywords: backing up, back up, backup, backup application data, Amazon Web services, AWS, NetApp Backup and Recovery, Oracle database, Hyper-V, SAP HANA database, virtual machine, vm 
summary: 'Veuillez prendre connaissance de ces limitations de NetApp Backup and Recovery avant d"utiliser Backup and Recovery dans votre environnement.' 
---
= Limitations connues de NetApp Backup and Recovery pour les charges de travail Hyper-V
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Les plates-formes, appareils ou fonctionnalités qui ne fonctionnent pas ou ne fonctionnent pas bien avec cette version sont répertoriés ici.  Lisez attentivement ces limitations.



== Actions non prises en charge

Les actions suivantes ne sont pas prises en charge dans les charges de travail Hyper-V dans NetApp Backup and Recovery :

* Créez des groupes de ressources à l'aide de machines virtuelles provenant de plusieurs hôtes Hyper-V.
* Restaurer les machines virtuelles vers un autre emplacement
* Répartition des disques (sur plusieurs partages CIFS)
* Protéger les machines virtuelles via SAN
* Il est impossible de restaurer des machines virtuelles ou leurs données entre des systèmes équipés de processeurs de fournisseurs différents (Intel vers AMD ou inversement), quel que soit le paramètre « Compatibilité du processeur » dans Hyper-V. Ce paramètre ne prend en charge que la compatibilité entre différentes générations d'un même fournisseur (par exemple, Intel vers Intel ou AMD vers AMD).



NOTE: Dans la version du 19 janvier 2026, il ne sera plus possible de mettre à niveau les plugins NetApp pour Hyper-V ou Windows à l'aide de l'option *Mettre à niveau* du menu Actions. Il faut plutôt supprimer chaque hôte Hyper-V et l'ajouter à nouveau pour mettre à jour les plugins.
