---
sidebar: sidebar 
permalink: br-limitations-oracle.html 
keywords: backing up, back up, backup, backup application data, Amazon Web services, AWS, NetApp Backup and Recovery, Oracle database, KVM, SAP HANA database, virtual machine, vm 
summary: NetApp Backup and Recovery doit d’abord découvrir les données pour que vous puissiez utiliser le service.  Lors de la découverte, NetApp Backup and Recovery analyse tous les volumes et fichiers des systèmes de votre organisation. 
---
= Limitations connues avec NetApp Backup and Recovery pour les charges de travail Oracle
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Les limitations connues identifient les plates-formes, les appareils ou les fonctions qui ne sont pas pris en charge par cette version du produit ou qui n'interagissent pas correctement avec elle. Examinez attentivement ces limitations.

Les actions suivantes ne sont pas prises en charge dans la version d'aperçu privée des charges de travail Oracle Database dans NetApp Backup and Recovery :

* Sauvegarde hors ligne
* Cloner
* Configuration ASM
* Protection des bases de données stockées sur SAN


Oracle Database est pris en charge uniquement en tant que déploiement autonome à l'aide de NFS dans la version d'aperçu privée des charges de travail Oracle.
