---
sidebar: sidebar 
permalink: br-limitations-hyperv.html 
keywords: backing up, back up, backup, backup application data, Amazon Web services, AWS, NetApp Backup and Recovery, Hyper-V, SAP HANA database, virtual machine, vm 
summary: 'Veuillez prendre connaissance de ces limitations de NetApp Backup and Recovery avant d"utiliser Backup and Recovery dans votre environnement.' 
---
= Limitations connues de NetApp Backup and Recovery pour les charges de travail Hyper-V
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Les plates-formes, appareils ou fonctionnalités qui ne fonctionnent pas ou ne fonctionnent pas bien avec cette version sont répertoriés ici.  Lisez attentivement ces limitations.



[[unsupported-actions]]
== Actions non prises en charge

Les actions suivantes ne sont pas prises en charge dans les charges de travail Hyper-V dans NetApp Backup and Recovery :

* Dans la version préliminaire de Backup and Recovery pour le déploiement local de NetApp Console, les sauvegardes vers le stockage objet sont prises en charge uniquement pour les destinations ONTAP S3 et StorageGRID. L'archivage des sauvegardes n'est pas pris en charge dans cette version préliminaire.
* La protection des machines virtuelles de génération 2 stockées sur un stockage SAN n'est pas prise en charge lors de l'utilisation de Microsoft Windows Server 2025.
* Créez des groupes de ressources à l'aide de machines virtuelles provenant de plusieurs hôtes Hyper-V.
* Répartition des disques (sur plusieurs partages CIFS)
* Il est impossible de restaurer des machines virtuelles ou leurs données entre des systèmes équipés de processeurs de fournisseurs différents (Intel vers AMD ou inversement), quel que soit le paramètre « Compatibilité du processeur » dans Hyper-V. Ce paramètre ne prend en charge que la compatibilité entre différentes générations d'un même fournisseur (par exemple, Intel vers Intel ou AMD vers AMD).

