---
sidebar: sidebar 
permalink: br-limitations-kvm.html 
keywords: backing up, back up, backup, backup application data, Amazon Web services, AWS, NetApp Backup and Recovery, Oracle database, KVM, SAP HANA database, virtual machine, vm 
summary: Cette version de NetApp Backup and Recovery présente les limitations connues suivantes. 
---
= Limitations connues de NetApp Backup and Recovery pour les charges de travail KVM
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Les plates-formes, appareils ou fonctionnalités qui ne fonctionnent pas ou ne fonctionnent pas bien avec cette version sont répertoriés ici.  Lisez attentivement ces limitations.

Les actions et configurations suivantes ne sont pas prises en charge dans la version d'aperçu privée des charges de travail KVM dans NetApp Backup and Recovery:



== Actions non prises en charge

Les actions suivantes ne sont pas prises en charge dans la version d’aperçu privée :

* Cloner, monter ou démonter des machines virtuelles
* Restaurer les machines virtuelles vers un autre emplacement
* Protéger les machines virtuelles stockées sur SAN
* Protéger les applications
* Modifier les groupes de protection
* Créer des groupes de protection à l'aide de machines virtuelles provenant de plusieurs hôtes KVM
* Créer des sauvegardes définies par l'utilisateur (seules les sauvegardes lancées à partir de la NetApp Console sont prises en charge)




== Configurations non prises en charge

Les configurations suivantes ne sont pas prises en charge :

* Contrôle d'accès basé sur les rôles (RBAC)
* Disques directement connectés à l'hôte KVM
* Disques répartis sur plusieurs points de montage ou partages NFS
* Format de disque RAW
* Types de pools de stockage autres que NetFS (seul NetFS est pris en charge)




== Notes de dépannage

Veuillez prendre note des points suivants lors de l'utilisation de la préversion privée des charges de travail KVM avec NetApp Backup and Recovery:

* Pour garantir la réussite des restaurations de charges de travail KVM, assurez-vous que le paramètre *Activer l'instantané cohérent avec la machine virtuelle* est actif dans la stratégie de protection que vous utilisez pour les sauvegardes KVM.
* Vous ne pouvez pas sauvegarder un pool de stockage avec des hôtes KVM gérés par Apache CloudStack à moins d'ajouter tous les hôtes gérés à NetApp Backup and Recovery. Pour contourner ce problème, ajoutez chaque hôte KVM géré par CloudStack à NetApp Backup and Recovery.
* Vous ne pouvez pas sauvegarder une machine virtuelle arrêtée appartenant à un groupe de protection. Pour contourner ce problème, retirez la machine virtuelle arrêtée du groupe de protection avant de démarrer la sauvegarde.

