---
sidebar: sidebar 
permalink: br-limitations-oracle.html 
keywords: NetApp Backup and Recovery, Oracle Database 
summary: 'Veuillez prendre connaissance de ces limitations de NetApp Backup and Recovery avant d"utiliser Backup and Recovery dans votre environnement.' 
---
= Limitations connues avec NetApp Backup and Recovery pour les charges de travail de base de données Oracle
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Veuillez consulter les limitations actuelles et les actions non prises en charge pour les charges de travail de base de données Oracle dans NetApp Backup and Recovery.

Les actions suivantes ne sont pas prises en charge pour les charges de travail Oracle Database dans la version préliminaire de NetApp Backup and Recovery :

* Après avoir effectué une récupération incomplète en restaurant une base de données à un point précis dans le temps ou à un SCN spécifique, si vous devez ultérieurement restaurer à un point antérieur à cette récupération, vous devez également sélectionner *fichiers de contrôle* dans les paramètres de destination de restauration. Sans la restauration du fichier de contrôle, la base de données ne peut pas être restaurée à un point antérieur à la précédente récupération incomplète.
* Dans la version préliminaire de Backup and Recovery pour le déploiement local de NetApp Console, les sauvegardes vers le stockage objet sont prises en charge uniquement pour les destinations ONTAP S3 et StorageGRID. L'archivage des sauvegardes n'est pas pris en charge dans cette version préliminaire.
* Sauvegardes hors ligne

