---
sidebar: sidebar 
permalink: br-reference-limitations.html 
keywords: backing up, back up, backup, backup application data, Amazon Web services, AWS, NetApp Backup and Recovery, Oracle database, Microsoft SQL Server database, SAP HANA database 
summary: 'Les limitations connues identifient les fonctions qui ne sont pas prises en charge par cette version du produit ou qui n"interagissent pas correctement avec elle. Examinez attentivement ces limitations.' 
---
= Limitations connues avec NetApp Backup and Recovery pour les volumes ONTAP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Les plates-formes, appareils ou fonctionnalités qui ne fonctionnent pas ou ne fonctionnent pas bien avec cette version sont répertoriés ici.  Lisez attentivement ces limitations.

* NetApp Backup and Recovery peut sauvegarder Cloud Volumes ONTAP dans un magasin d'objets dans les régions AWS Chine (y compris Pékin et Ningxia) ; cependant, vous devrez peut-être d'abord modifier manuellement les stratégies d'identité et d'accès.
+
Pour plus de détails sur la création d'un agent de console dans AWS, reportez-vous à https://docs.netapp.com/us-en/console-setup-admin/task-install-connector-aws-bluexp.html["Installation d'un agent de console dans AWS"^] .

+
Pour plus de détails, reportez-vous à l'article de blog https://community.netapp.com/t5/Tech-ONTAP-Blogs/BlueXP-Backup-and-Recovery-Feature-Blog-May-23-Updates/ba-p/444052["Blog sur les fonctionnalités de NetApp Backup and Recovery - mai 2023"^] .

* NetApp Backup and Recovery ne prend pas en charge les régions Microsoft Azure Chine.
+
Pour plus de détails sur la création d’un agent de console dans Azure, reportez-vous à https://docs.netapp.com/us-en/console-setup-admin/task-install-connector-azure-bluexp.html["Installation d'un agent de console dans Azure"^] .

* NetApp Backup and Recovery ne prend pas en charge les sauvegardes des volumes FlexCache .




== Limitations de réplication pour les volumes ONTAP

* Vous ne pouvez sélectionner qu'un seul volume FlexGroup à la fois pour la réplication.  Vous devrez activer les sauvegardes séparément pour chaque volume FlexGroup .
+
Il n'y a aucune limitation pour les volumes FlexVol : vous pouvez sélectionner tous les volumes FlexVol de votre système et attribuer les mêmes politiques de sauvegarde.

* La fonctionnalité suivante est prise en charge dans https://docs.netapp.com/us-en/data-services-replication/index.html["NetApp Replication"] , mais pas lors de l'utilisation de la fonction de réplication de NetApp Backup and Recovery:
+
** Il n'existe aucune prise en charge pour une configuration en cascade où la réplication se produit du volume A vers le volume B et du volume B vers le volume C. La prise en charge inclut la réplication du volume A vers le volume B.
** Il n'existe aucune prise en charge de la réplication des données vers et depuis les systèmes FSx pour ONTAP .
** Il n’existe aucune prise en charge pour la création d’une réplication unique d’un volume.


* Lors de la création de réplications à partir de systèmes ONTAP locaux, si la version ONTAP sur le système Cloud Volumes ONTAP cible est 9.8, 9.9 ou 9.11, seules les stratégies de coffre-fort miroir sont autorisées.
* NetApp Backup & Recovery ne prend pas en charge la conversion d'un FlexVol volume ayant une relation de sauvegarde cloud active en un volume FlexGroup tout en conservant la fonctionnalité de sauvegarde cloud.




== Limitations de sauvegarde sur objet pour les volumes ONTAP

* Lors de la sauvegarde des données, NetApp Backup and Recovery ne conservera pas le chiffrement de volume NetApp (NVE).  Cela signifie que les données chiffrées sur le volume NVE seront déchiffrées pendant le transfert des données vers la destination et le chiffrement ne sera pas conservé.
+
Pour une explication sur ces types de cryptage, reportez-vous àhttps://docs.netapp.com/us-en/ontap/encryption-at-rest/configure-netapp-volume-encryption-concept.html["Présentation de la configuration du chiffrement de volume NetApp"^] .

* Si les snapshots de rétention à long terme sont activés sur un volume de destination SnapMirror à l’aide de la planification de la stratégie SnapMirror , les snapshots sont créés directement sur le volume de destination.  Dans ce cas, vous ne devez pas sauvegarder ces volumes à l’aide de NetApp Backup and Recovery, car ces snapshots ne seront pas déplacés vers le stockage d’objets.
* Lors de la sauvegarde des données, NetApp Backup and Recovery ne conservera pas le chiffrement de volume NetApp (NVE).  Cela signifie que les données chiffrées sur le volume NVE seront déchiffrées pendant le transfert des données vers la destination et le chiffrement ne sera pas conservé.
+
Pour une explication sur ces types de cryptage, reportez-vous àhttps://docs.netapp.com/us-en/ontap/encryption-at-rest/configure-netapp-volume-encryption-concept.html["Présentation de la configuration du chiffrement de volume NetApp"^] .

* Si les snapshots de rétention à long terme sont activés sur un volume de destination SnapMirror à l’aide de la planification de la stratégie SnapMirror , les snapshots sont créés directement sur le volume de destination.  Dans ce cas, vous ne devez pas sauvegarder ces volumes à l’aide de NetApp Backup and Recovery, car ces snapshots ne seront pas déplacés vers le stockage d’objets.
* Lorsque vous créez ou modifiez une politique de sauvegarde alors qu’aucun volume n’est attribué à la politique, le nombre de sauvegardes conservées peut être au maximum de 1 018.  Après avoir attribué des volumes à la politique, vous pouvez modifier la politique pour créer jusqu'à 4 000 sauvegardes.
* Lors de la sauvegarde des volumes de protection des données (DP) :
+
** Relations avec les étiquettes SnapMirror `app_consistent` et `all_source_snapshot` ne sera pas sauvegardé dans le cloud.
** Si vous créez des copies locales de snapshots sur le volume de destination SnapMirror (quelles que soient les étiquettes SnapMirror utilisées), ces snapshots ne seront pas déplacés vers le cloud en tant que sauvegardes.  À ce stade, vous devrez créer une politique de snapshot avec les étiquettes souhaitées sur le volume DP source afin que NetApp Backup and Recovery les sauvegarde.


* Les sauvegardes de volume FlexGroup ne peuvent pas être déplacées vers un stockage d'archivage.
* Les sauvegardes de volume FlexGroup peuvent utiliser la protection DataLock et Ransomware si le cluster exécute ONTAP 9.13.1 ou une version ultérieure.
* La sauvegarde du volume SVM-DR est prise en charge avec les restrictions suivantes :
+
** Les sauvegardes sont prises en charge uniquement à partir du serveur secondaire ONTAP .
** La politique de snapshot appliquée au volume doit être l'une des politiques reconnues par NetApp Backup and Recovery, notamment quotidienne, hebdomadaire, mensuelle, etc. La politique par défaut « sm_created » (utilisée pour *Mettre en miroir tous les snapshots*) n'est pas reconnue et le volume DP ne sera pas affiché dans la liste des volumes pouvant être sauvegardés.
** SVM-DR et la sauvegarde et la récupération de volume fonctionnent de manière totalement indépendante lorsque la sauvegarde est effectuée à partir de la source ou de la destination.  La seule restriction est que SVM-DR ne réplique pas la relation cloud SnapMirror .  Dans le scénario DR, lorsque le SVM est mis en ligne dans l’emplacement secondaire, vous devez mettre à jour manuellement la relation cloud SnapMirror .


* Prise en charge de MetroCluster :
+
** Lorsque vous utilisez ONTAP 9.12.1 GA ou une version ultérieure, la sauvegarde est prise en charge lors de la connexion au système principal.  L'ensemble de la configuration de sauvegarde est transféré vers le système secondaire afin que les sauvegardes vers le cloud se poursuivent automatiquement après le basculement.  Vous n’avez pas besoin de configurer une sauvegarde sur le système secondaire (en fait, vous n’êtes pas autorisé à le faire).
** Lorsque vous utilisez ONTAP 9.12.0 et versions antérieures, la sauvegarde est prise en charge uniquement à partir du système secondaire ONTAP .
** Les sauvegardes des volumes FlexGroup ne sont pas prises en charge pour le moment.


* La sauvegarde de volume ad hoc à l'aide du bouton *Sauvegarder maintenant* n'est pas prise en charge sur les volumes de protection des données.
* Les configurations SM-BC ne sont pas prises en charge.
* ONTAP ne prend pas en charge la répartition des relations SnapMirror d'un seul volume vers plusieurs magasins d'objets ; par conséquent, cette configuration n'est pas prise en charge par NetApp Backup and Recovery.
* Le mode WORM/Compliance sur un magasin d’objets est actuellement pris en charge sur Amazon S3, Azure et StorageGRID .  Il s’agit de la fonctionnalité DataLock et elle doit être gérée à l’aide des paramètres NetApp Backup and Recovery , et non à l’aide de l’interface du fournisseur de cloud.




== Restaurer les limitations pour les volumes ONTAP

Ces limitations s'appliquent à la fois aux méthodes de recherche et de restauration et de navigation et de restauration de fichiers et de dossiers, sauf indication contraire spécifique.

* Parcourir et restaurer peut restaurer jusqu'à 100 fichiers individuels à la fois.
* Search & Restore peut restaurer 1 fichier à la fois.
* Lorsque vous utilisez ONTAP 9.13.0 ou une version ultérieure, Parcourir et restaurer et Rechercher et restaurer peuvent restaurer un dossier avec tous les fichiers et sous-dossiers qu'il contient.
+
Lorsque vous utilisez une version d' ONTAP supérieure à 9.11.1 mais antérieure à 9.13.0, l'opération de restauration ne peut restaurer que le dossier sélectionné et les fichiers de ce dossier - aucun sous-dossier ni fichier dans les sous-dossiers n'est restauré.

+
Lors de l'utilisation d'une version d' ONTAP antérieure à 9.11.1, la restauration de dossiers n'est pas prise en charge.

* La restauration de répertoire/dossier est prise en charge pour les données qui résident dans le stockage d'archives uniquement lorsque le cluster exécute ONTAP 9.13.1 et versions ultérieures.
* La restauration de répertoire/dossier est prise en charge pour les données protégées à l'aide de DataLock uniquement lorsque le cluster exécute ONTAP 9.13.1 et versions ultérieures.
* La restauration de répertoire/dossier n'est actuellement pas prise en charge à partir de réplications et/ou de snapshots locaux.
* La restauration des volumes FlexGroup vers les volumes FlexVol ou des volumes FlexVol vers les volumes FlexGroup n'est pas prise en charge.
* Le fichier en cours de restauration doit utiliser la même langue que celle du volume de destination.  Vous recevrez un message d'erreur si les langues ne sont pas les mêmes.
* La priorité de restauration _Élevée_ n’est pas prise en charge lors de la restauration de données à partir du stockage d’archivage Azure vers les systèmes StorageGRID .
* Si vous sauvegardez un volume DP, puis décidez de rompre la relation SnapMirror avec ce volume, vous ne pouvez pas restaurer les fichiers sur ce volume, sauf si vous supprimez également la relation SnapMirror ou si vous inversez la direction de SnapMirror .
* Limitations de la restauration rapide :
+
** L'emplacement de destination doit être un système Cloud Volumes ONTAP utilisant ONTAP 9.13.0 ou supérieur.
** Cette option n'est pas prise en charge avec les sauvegardes situées dans un stockage archivé.
** Les volumes FlexGroup sont pris en charge uniquement si le système source à partir duquel la sauvegarde cloud a été créée exécutait ONTAP 9.12.1 ou une version ultérieure.
** Les volumes SnapLock sont pris en charge uniquement si le système source à partir duquel la sauvegarde cloud a été créée exécutait ONTAP 9.11.0 ou une version ultérieure.



