---
sidebar: sidebar 
permalink: br-rbac-setup.html 
keywords: backup, back up, restore, recovery, aws, azure 
summary: 'Pour une sécurité renforcée, configurez l"accès pour des rôles spécifiques dans NetApp Backup and Recovery.' 
---
= Configurez le contrôle d'accès basé sur les rôles dans NetApp Backup and Recovery
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Configurez le contrôle d'accès basé sur les rôles (RBAC) dans la NetApp Console pour contrôler qui peut accéder aux ressources NetApp Backup and Recovery. Vous pouvez attribuer des rôles d'administrateur ou de lecteur aux charges de travail qui prennent en charge le RBAC. Les charges de travail qui ne prennent pas encore en charge le RBAC restent accessibles à tous les utilisateurs disposant de rôles Backup and Recovery jusqu'à ce qu'une association au niveau du projet ou de la flotte soit disponible.


NOTE: NetApp Console utilise des projets pour organiser les ressources dans des dossiers, tandis que le déploiement local de NetApp Console désigne les projets comme des flottes.

Pour contrôler l'accès aux ressources de votre organisation, effectuez ces étapes dans la page *Administration > Identité et accès* de la NetApp Console.


NOTE: Ces étapes supposent que vous disposez du rôle d'administrateur de l'organisation dans la NetApp Console.

.Étapes
. Créez la structure du projet d'identité et de contrôle d'accès.
+
En tant qu'administrateur de l'organisation, configurez la structure des dossiers et des projets où résideront les charges de travail.

. Attribuez des rôles aux utilisateurs.
+
.. Option principale :
+
Ajoutez des utilisateurs à chaque projet désigné pour les charges de travail et attribuez-leur le rôle approprié. Par exemple :

+
*** *Administrateur de l'organisation* et *Super administrateur de NetApp Backup and Recovery* : Un utilisateur disposant de ces rôles peut consulter toutes les ressources de l'ensemble des organisations, découvrir les charges de travail NetApp Backup and Recovery et les affecter à des projets (par exemple, US East ou US West).
*** *Administrateur de dossier ou de projet* et *Super administrateur de NetApp Backup and Recovery* : Un utilisateur disposant de ces rôles peut uniquement consulter les ressources de son dossier ou projet attribué, mais peut découvrir les charges de travail NetApp Backup and Recovery et les attribuer à ce projet.


.. Option alternative :
+
Au lieu d'accorder à un utilisateur un accès complet d'administrateur Backup and Recovery, vous pouvez vous attribuer le rôle de super administrateur Backup and Recovery et découvrir directement les workloads.



. Découvrez les charges de travail dans Backup and Recovery.
+
Les administrateurs de l'organisation, du dossier ou du projet découvrent les charges de travail disponibles et sélectionnent le projet approprié (par exemple, US East ou US West). Chaque charge de travail est automatiquement associée au projet sélectionné.

. Ajouter des utilisateurs aux projets.
+
Les administrateurs d'organisation, de dossier ou de projet ajoutent des utilisateurs de NetApp Console aux projets avec des charges de travail. Attribuez aux utilisateurs le rôle de lecteur de l'organisation et un rôle NetApp Backup and Recovery en fonction de leurs besoins d'accès. Les utilisateurs disposant du rôle NetApp Backup and Recovery approprié obtiennent automatiquement l'accès aux nouvelles charges de travail dans ces projets.





[[related-information]]
== Informations connexes

* link:https://docs.netapp.com/us-en/console-setup-admin/concept-identity-and-access-management.html["Découvrez la gestion des identités et des accès de la NetApp Console"^].
* link:https://docs.netapp.com/us-en/console-setup-admin/reference-iam-backup-rec-roles.html["Rôles de NetApp Backup and Recovery dans la NetApp Console"^].

