---
sidebar: sidebar 
permalink: br-start-discover-kubernetes.html 
keywords: backing up, back up, backup, backup application data, Amazon Web services, AWS, NetApp Backup and Recovery, Kubernetes 
summary: NetApp Backup and Recovery doit d’abord découvrir les charges de travail pour que vous puissiez utiliser le service. 
---
= Découvrez les charges de travail Kubernetes dans NetApp Backup and Recovery
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Découvrez les clusters Kubernetes et leurs charges de travail dans NetApp Backup and Recovery afin de pouvoir les protéger à l'aide de politiques de protection.

*Rôle Console NetApp requis* Super administrateur de sauvegarde et de restauration. Si vous protégez des données stockées sur un cluster Cloud Volumes ONTAP, le rôle d'administrateur Cloud Volumes ONTAP est également requis. En savoir plus link:reference-roles.html["Rôles et privilèges de sauvegarde et de récupération"]. https://docs.netapp.com/us-en/console-setup-admin/reference-iam-predefined-roles.html["En savoir plus sur les rôles d'accès à la NetApp Console pour tous les services"^].



[[discover-kubernetes-workloads]]
== Découvrez les charges de travail Kubernetes

Dans l'inventaire de Backup and Recovery, découvrez les clusters et charges de travail Kubernetes de votre environnement. L'ajout d'un cluster vous permet de l'enregistrer dans NetApp Backup and Recovery et de découvrir ses applications et ressources pour la protection. Vous pouvez également découvrir des ressources Kubernetes locales isolées du réseau (air-gapped) à l'aide du déploiement local NetApp Console.

[NOTE]
====
Lors de la découverte d'un cluster actuellement protégé par Trident Protect, toutes les planifications de sauvegarde utilisées avec Trident Protect sont désactivées pendant le processus de découverte, car les planifications de sauvegarde Trident Protect ne sont pas compatibles avec NetApp Backup and Recovery. Pour protéger les applications du cluster, link:br-use-policies-create.html["créer une nouvelle stratégie de protection"] ou associez les applications à une stratégie existante. Vous pouvez ensuite supprimer les planifications de sauvegarde Trident Protect si nécessaire.

====
.Étapes
. Effectuez l’une des opérations suivantes :
+
** Si vous découvrez les charges de travail Kubernetes pour la première fois, dans NetApp Backup and Recovery, sous *Charges de travail*, sélectionnez la vignette *Kubernetes*.
** Si vous avez déjà découvert des charges de travail Kubernetes, dans NetApp Backup and Recovery, sélectionnez *Inventaire* > *Charges de travail*, puis sélectionnez *Découvrir les ressources*.


. Sélectionnez le type de charge de travail *Kubernetes*.
. Saisissez un nom de cluster et choisissez un agent de console à utiliser avec le cluster.
. Vous pouvez sélectionner un dossier ou un projet pour déterminer où le contrôle d'accès s'applique à ce cluster. Si vous ne sélectionnez aucun dossier ni projet, la ressource IAM du cluster est ajoutée au niveau de l'organisation.
+
** *Dossier* : Sélectionnez cette option pour contrôler l’accès des utilisateurs aux ressources du cluster au niveau du dossier, puis sélectionnez un dossier dans la liste.
+

NOTE: Si un cluster Kubernetes ou un espace de noms est associé à un dossier, les utilisateurs doivent également disposer du rôle *Backup and Recovery viewer* pour le projet sélectionné dans le sélecteur de projet en haut à droite. Cet accès au niveau du projet permet aux utilisateurs d’ouvrir la page d’accueil de NetApp Backup and Recovery. Les rôles attribués au niveau du dossier (par exemple, Backup and Recovery backup admin) déterminent ce que les utilisateurs peuvent faire après être entrés sur la page de la charge de travail, mais ne donnent pas accès à la page en eux-mêmes. Consultez link:br-use-manage-kubernetes-access-control.html["Gérer l'accès aux ressources Kubernetes"] pour plus d’informations.

** *Projet* : Sélectionnez cette option pour contrôler l’accès des utilisateurs aux ressources du cluster au niveau du projet, puis sélectionnez un projet dans la liste.
+
https://docs.netapp.com/us-en/console-setup-admin/concept-identity-and-access-management.html#netapp-console-organizational-components["En savoir plus"^]À propos des composants organisationnels dans la NetApp Console.



. Sélectionnez *Générer les commandes d'installation*.
+
NetApp Backup and Recovery fournit des instructions qui varient selon le type d'installation que vous sélectionnez. Si vous utilisez un déploiement local NetApp Console, vous pouvez choisir des instructions pour découvrir des ressources isolées du réseau, c'est-à-dire celles qui n'ont aucune connectivité réseau externe.

. Choisissez un type d'installation pour afficher les instructions d'installation de Trident Protect sur votre cluster Kubernetes :
+
** Sélectionnez *Connecté* pour découvrir les clusters disposant d'une connectivité réseau externe. Les instructions sont adaptées aux clusters connectés.
** Sélectionnez *Air-gapped* pour découvrir les clusters sans connexion réseau externe. Les instructions sont adaptées aux clusters *air-gapped* (hors ligne).
+
[role="tabbed-block"]
====
.Découverte connectée
--
... Suivez les instructions de ligne de commande qui s'affichent dans Backup and Recovery. Ces étapes garantissent que Backup and Recovery peut interagir avec le cluster.


--
.Découverte en environnement isolé (air-gapped)
--
... Saisissez l'URL de votre registre de conteneurs Docker privé. Ce registre est utilisé pour télécharger les images de Trident Protect et de Trident Protect Connector lors de l'installation.
... Si votre registre de conteneurs privé nécessite une authentification, utilisez l'une des méthodes suivantes pour configurer les informations d'identification du registre :
+
**** Authentification au niveau du nœud : configurez les informations d’identification du registre dans l’environnement d’exécution du conteneur sur chaque nœud. Une fois configuré, tous les pods peuvent extraire des images sans nécessiter de paramètres Helm supplémentaires.
**** *Secret d'extraction d'image Kubernetes* : Créez un secret d'extraction d'image Kubernetes dans l' `trident-protect`espace de noms, puis référencez-le lors de l'étape de mise à niveau Helm dans les instructions d'installation de Trident Protect :
+
[source, console]
----
--set trident-protect.imagePullSecrets[0].name=<pull-secret-name>
--set connector.imagePullSecrets[0].name=<pull-secret-name>
----


... Suivez les instructions de ligne de commandes qui apparaissent dans Backup and Recovery, en ajoutant les informations du secret d'extraction d'image lors de l'étape Helm (si nécessaire). Ces étapes garantissent que Backup and Recovery peut interagir avec le cluster.


--
====


. Après avoir terminé les étapes d'installation de Trident Protect, sélectionnez *Découvrir*.
+
Le cluster est ajouté à l'inventaire.

. Sélectionnez *Afficher* dans la charge de travail Kubernetes associée pour voir la liste des applications, des clusters et des espaces de noms pour cette charge de travail.




[[continue-to-the-netapp-backup-and-recovery-dashboard]]
== Accéder au tableau de bord de NetApp Backup and Recovery

Suivez ces étapes pour afficher le tableau de bord NetApp Backup and Recovery et vérifier les ressources détectées.

. Dans le menu de la NetApp Console , sélectionnez *Protection* > *Sauvegarde et récupération*.
. Sélectionnez la tuile de charge de travail Kubernetes.
. Dans le menu Sauvegarde et récupération, sélectionnez *Tableau de bord*.
. Examiner l’état de santé de la protection des données.  Le nombre de charges de travail à risque ou protégées augmente en fonction des charges de travail nouvellement découvertes, protégées et sauvegardées.
+
link:br-use-dashboard.html["Découvrez ce que le tableau de bord vous montre"].


