---
sidebar: sidebar 
permalink: br-start-faq.html 
keywords: backup and recovery faq, NetApp Backup and Recovery frequently asked questions 
summary: Cette FAQ peut vous aider si vous cherchez simplement une réponse rapide à une question. 
---
= Questions fréquemment posées sur NetApp Backup and Recovery
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Cette FAQ peut vous aider si vous cherchez simplement une réponse rapide à une question.



== Déploiement

*Avez-vous besoin d'une licence pour utiliser la version préliminaire de NetApp Backup and Recovery ?*

Vous pouvez utiliser les types de licences suivants :

* Inscrivez-vous pour un essai gratuit de 30 jours.


*Comment activer NetApp Backup and Recovery?*  NetApp Backup and Recovery ne nécessite aucune activation.  L'option de sauvegarde et de récupération est automatiquement activée dans la navigation de gauche de la console.

Pour commencer, vous devez vous inscrire ou contacter votre représentant commercial NetApp pour essayer Backup and Recovery.  Ensuite, lorsque vous utilisez l’agent de console, il inclura les fonctionnalités appropriées pour le service.

Pour démarrer avec NetApp Backup and Recovery, sélectionnez « Commencer à découvrir les charges de travail » sur sa page d’accueil initiale.

* NetApp Backup and Recovery est-il disponible en modes standard, restreint et privé ?*  À l’heure actuelle, NetApp Backup and Recovery est disponible uniquement en mode standard. Restez à l’écoute pour en savoir plus.

Pour une explication sur ces modes dans tous les services de données NetApp , reportez-vous à https://docs.netapp.com/us-en/console-setup-admin/concept-modes.html["Modes de déploiement de la NetApp Console"^] .



== Accéder

*Quelle est l'URL de NetApp Backup and Recovery ?*  Pour l'URL, dans un navigateur, saisissez : https://console.netapp.com/["https://console.netapp.com/backup-and-recovery"^] pour accéder à la NetApp Console.

*Comment sont gérées les autorisations d'accès ?* Seuls les administrateurs de l'organisation ont la possibilité d'initier le service et de découvrir les charges de travail (car cela implique de s'engager à utiliser une ressource).  Les interactions ultérieures peuvent être effectuées par n’importe quel rôle.

*Quelle est la meilleure résolution d'appareil ?* La résolution de périphérique recommandée pour NetApp Backup and Recovery est de 1920 x 1080 ou supérieure.

*Quel navigateur dois-je utiliser ?* N’importe quel navigateur moderne fonctionnera.



== Interaction avec d'autres services

* NetApp Backup and Recovery est-il conscient des paramètres de protection définis dans NetApp ONTAP?*  Oui, NetApp Backup and Recovery détecte les planifications de snapshots définies dans ONTAP.

*Si vous définissez une politique à l'aide de NetApp Backup and Recovery, devez-vous effectuer les modifications futures uniquement dans Backup and Recovery ?*  Nous vous recommandons d'effectuer des modifications de stratégie à partir de NetApp Backup and Recovery.



== Charges de travail

*Qu'est-ce qui constitue une charge de travail ?* Une charge de travail est une application pour la version Preview 2025. Une charge de travail inclut tous les volumes utilisés par une seule instance d’application.  Par exemple, une instance de base de données Microsoft SQL Server déployée sur mssql3.host.com peut avoir vol1 et vol2 pour ses données et ses journaux, respectivement.  Ces volumes constituent ensemble la charge de travail pour cette instance spécifique de l'instance de base de données.

*Quelles charges de travail NetApp Backup and Recovery prend-il en charge ?*

Pour la version Preview 2025, NetApp Backup and Recovery peut identifier les charges de travail suivantes : applications Microsoft SQL Server.

*Qu'est-ce qu'une charge de travail « protégée » ?* Dans NetApp Backup and Recovery, une charge de travail affiche un état « protégé » lorsqu'une stratégie de détection principale est activée.

*Qu'est-ce qu'une charge de travail « à risque » ?* Si une charge de travail n’a pas de stratégie de détection principale activée, elle est « à risque » même si une stratégie de sauvegarde et de snapshot est activée.

*Nouvelle charge de travail ajoutée, mais n'apparaît pas encore* Si vous avez ajouté une nouvelle charge de travail à votre environnement, relancez la découverte et appliquez des politiques de protection pour protéger cette nouvelle ressource.



== Politiques de protection

* NetApp Backup and Recovery est-il conscient des paramètres de protection définis dans NetApp ONTAP?*

Oui, NetApp Backup and Recovery détecte les planifications de snapshots définies dans ONTAP et si ARP et FPolicy sont activés dans une charge de travail détectée. Les informations que vous voyez initialement dans le tableau de bord sont agrégées à partir d’autres solutions et produits NetApp .

* NetApp Backup and Recovery est-il au courant des politiques déjà définies dans SnapCenter?*

Oui, si vous avez des charges de travail gérées dans SnapCenter, les politiques gérées par ces produits sont intégrées dans NetApp Backup and Recovery.

*Pouvez-vous modifier les politiques transférées depuis SnapCenter?*

Oui, vous pouvez modifier les politiques gérées par SnapCenter dans NetApp Backup and Recovery.

*Si des politiques existent à partir d' ONTAP (déjà activées dans System Manager telles que ARP, FPolicy et les snapshots), sont-elles modifiées dans NetApp Backup and Recovery?*

Non. NetApp Backup and Recovery ne modifie aucune stratégie de détection existante (paramètres ARP, FPolicy) d' ONTAP.

*Que se passe-t-il si vous ajoutez de nouvelles politiques dans SnapCenter après vous être inscrit à NetApp Backup and Recovery?*

NetApp Backup and Recovery reconnaît toutes les nouvelles politiques créées dans SnapCenter.

*Pouvez-vous modifier les politiques d' ONTAP?*

Oui, vous pouvez modifier les politiques d’ ONTAP dans NetApp Backup and Recovery.  Vous pouvez également créer de nouvelles politiques dans NetApp Backup and Recovery et les appliquer aux charges de travail.  Cette action remplace les stratégies ONTAP existantes par les stratégies créées dans NetApp Backup and Recovery.
