---
sidebar: sidebar 
permalink: br-start-setup.html 
keywords: backup, back up, restore, recovery, aws, azure 
summary: 'Préparez un emplacement hors site, tel que StorageGRID, AWS ou Azure, et configurez les autorisations requises pour qu"il puisse servir de destination de sauvegarde.' 
---
= Configurer les destinations de sauvegarde
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Préparez un emplacement hors site, tel que StorageGRID, AWS ou Azure, et configurez les autorisations requises pour qu'il puisse servir de destination de sauvegarde.

Avant de commencer, révisezlink:concept-start-prereq.html["prérequis"] pour garantir que votre environnement est prêt.



[[prepare-the-backup-destination]]
== Préparer la destination de sauvegarde

Préparez une ou plusieurs des destinations de sauvegarde suivantes :

* StorageGRID NetApp .
+
Voir https://docs.netapp.com/us-en/storage-management-storagegrid/task-discover-storagegrid.html["Découvrez StorageGRID"^].

+
Consultez  https://docs.netapp.com/us-en/storagegrid/index.html["Documentation de StorageGRID"^] pour plus de détails sur StorageGRID.

* Amazon Web Services. Voir https://docs.netapp.com/us-en/storage-management-s3-storage/index.html["Documentation Amazon S3"^].
+
Procédez comme suit pour préparer AWS comme destination de sauvegarde :

+
** Configurez un compte dans AWS.
** Configurez les autorisations S3 dans AWS, répertoriées dans la section suivante.
** Pour plus d'informations sur la gestion de votre stockage AWS dans la Console, consultez https://docs.netapp.com/us-en/console-setup-admin/task-viewing-amazon-s3.html["Gérez vos buckets Amazon S3"^].


* Microsoft Azure.
+
** Voir https://docs.netapp.com/us-en/storage-management-blob-storage/index.html["Documentation sur le stockage Blob Azure"^].
** Configurez un compte dans Azure.
** Configure https://docs.netapp.com/us-en/console-setup-admin/reference-permissions.html["Autorisations Azure"^] dans Azure.
** Pour plus d'informations sur la gestion de votre stockage Azure dans la Console, consultez https://docs.netapp.com/us-en/storage-management-blob-storage/task-view-azure-blob-storage.html["Gérez vos comptes de stockage Azure"^].




Après avoir configuré les options dans la destination de sauvegarde elle-même, vous la configurerez ensuite comme destination de sauvegarde dans NetApp Backup and Recovery. Pour plus d'informations sur la configuration de la destination de sauvegarde dans NetApp Backup and Recovery, consultez link:br-start-discover-backup-targets.html["Découvrir les cibles de sauvegarde"].



[[set-up-s3-permissions]]
== Configurer les autorisations S3

Vous devrez configurer deux ensembles d’autorisations AWS S3 :

* Autorisations permettant à l’agent de console de créer et de gérer le compartiment S3.
* Autorisations pour le cluster ONTAP sur site afin qu’il puisse lire et écrire des données dans le bucket S3.


.Étapes
. Assurez-vous que l’agent de la console dispose des autorisations requises.  Pour plus de détails, voir https://docs.netapp.com/us-en/console-setup-admin/reference-permissions-aws.html["Autorisations de stratégie de la NetApp Console"] .
+

NOTE: Lors de la création de sauvegardes dans les régions AWS Chine, vous devez modifier le nom de ressource AWS « arn » sous toutes les sections _Resource_ dans les politiques IAM de « aws » à « aws-cn » ; par exemple `arn:aws-cn:s3:::netapp-backup-*` .

. Lorsque vous activez le service, l’assistant de sauvegarde vous invite à saisir une clé d’accès et une clé secrète.  Ces informations d’identification sont transmises au cluster ONTAP afin ONTAP puisse sauvegarder et restaurer les données dans le bucket S3.  Pour cela, vous devrez créer un utilisateur IAM avec les autorisations suivantes.
+
Voir le https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_create_for-user.html["Documentation AWS : Création d'un rôle pour déléguer des autorisations à un utilisateur IAM"^].

+
[%collapsible]
====
[source, json]
----
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Action": [
        "s3:GetObject",
        "s3:PutObject",
        "s3:DeleteObject",
        "s3:ListBucket",
        "s3:ListAllMyBuckets",
        "s3:GetBucketLocation",
        "s3:PutEncryptionConfiguration"
      ],
      "Resource": "arn:aws:s3:::netapp-backup-*",
      "Effect": "Allow",
      "Sid": "backupPolicy"
    },
    {
      "Action": [
        "s3:ListBucket",
        "s3:GetBucketLocation"
      ],
      "Resource": "arn:aws:s3:::netapp-backup*",
      "Effect": "Allow"
    },
    {
      "Action": [
        "s3:GetObject",
        "s3:PutObject",
        "s3:DeleteObject",
        "s3:ListAllMyBuckets",
        "s3:PutObjectTagging",
        "s3:GetObjectTagging",
        "s3:RestoreObject",
        "s3:GetBucketObjectLockConfiguration",
        "s3:GetObjectRetention",
        "s3:PutBucketObjectLockConfiguration",
        "s3:PutObjectRetention"
      ],
      "Resource": "arn:aws:s3:::netapp-backup*/*",
      "Effect": "Allow"
    }
  ]
}
----
====

