---
sidebar: sidebar 
permalink: br-start-login.html 
keywords: backing up, back up, backup, backup application data, Amazon Web services, AWS, NetApp Backup and Recovery, Oracle database, Microsoft SQL Server database, SAP HANA database 
summary: Vous utilisez la NetApp Console pour vous connecter au service NetApp Backup and Recovery . 
---
= Connectez-vous à NetApp Backup and Recovery
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Vous utilisez la NetApp Console pour vous connecter à NetApp Backup and Recovery.

NetApp Backup and Recovery utilise la gestion des identités et des accès pour contrôler ce que chaque utilisateur peut faire.

Pour plus de détails sur les actions que chaque rôle peut effectuer, voirlink:reference-roles.html["Rôles utilisateur de NetApp Backup and Recovery"] .

Pour vous connecter à la NetApp Console, vous pouvez utiliser vos informations d'identification du site de support NetApp ou vous inscrire pour une connexion à la NetApp Console à l'aide de votre adresse e-mail et d'un mot de passe. https://docs.netapp.com/us-en/console-setup-admin/task-logging-in.html["En savoir plus sur la connexion"^] .

*Rôle de NetApp Console requis* Rôle de super administrateur de sauvegarde et de récupération ou d'administrateur de restauration de sauvegarde et de récupération. https://docs.netapp.com/us-en/console-setup-admin/reference-iam-predefined-roles.html["En savoir plus sur les rôles d'accès à la NetApp Console pour tous les services"^] .

Pour ajouter un agent de console, vous devez disposer du rôle de super administrateur de sauvegarde et de récupération.

.Étapes
. Ouvrez un navigateur Web et accédez à la https://console.netapp.com/["NetApp Console"^] .
+
La page de connexion à la NetApp Console s’affiche.

. Connectez-vous à la console.
. Dans la navigation de gauche de la console, sélectionnez *Protection* > *Sauvegarde et récupération*.
+
** Si c'est la première fois que vous vous connectez à Backup and Recovery et que vous n'avez pas encore ajouté de système à la page *Systèmes*, Backup and Recovery affiche la page d'accueil « Bienvenue sur le nouveau NetApp Backup and Recovery» avec une option permettant d'ajouter un système. Pour plus d'informations sur l'ajout d'un système à la page *Systèmes*, veuillez consulter https://docs.netapp.com/us-en/console-setup-admin/task-quick-start-standard-mode.html["Prise en main du mode standard de la NetApp Console"^].
** Si vous vous connectez à Backup and Recovery pour la première fois et que vous avez un système dans la console mais aucune ressource découverte, la page _Bienvenue sur le nouveau NetApp Backup and Recovery_ apparaît avec une option pour *Découvrir les ressources*.


. Si vous ne l’avez pas déjà fait, sélectionnez l’option *Découvrir et gérer*.
+
** Pour les charges de travail Microsoft SQL Server, reportez-vous àlink:br-start-discover.html["Découvrez les charges de travail Microsoft SQL Server"] .
** Pour les charges de travail VMware, reportez-vous àlink:br-use-vmware-discovery.html["Découvrez les charges de travail VMware"] .
** Pour les charges de travail KVM, reportez-vous àlink:br-start-discover-kvm.html["Découvrez les charges de travail KVM"] .
** Pour les charges de travail Oracle, reportez-vous àlink:br-start-discover-oracle.html["Découvrez les charges de travail Oracle"] .
** Pour les charges de travail Hyper-V, reportez-vous àlink:br-start-discover-hyperv.html["Découvrez les charges de travail Hyper-V"] .
** Pour les charges de travail Kubernetes, reportez-vous àlink:br-start-discover-kubernetes.html["Découvrez les charges de travail Kubernetes"] .



