---
sidebar: sidebar 
permalink: br-start-discover-kubernetes.html 
keywords: backing up, back up, backup, backup application data, Amazon Web services, AWS, NetApp Backup and Recovery, Kubernetes 
summary: NetApp Backup and Recovery doit d’abord découvrir les charges de travail pour que vous puissiez utiliser le service. 
---
= Découvrez les charges de travail Kubernetes dans NetApp Backup and Recovery
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
NetApp Backup and Recovery doit découvrir les charges de travail Kubernetes avant de les protéger.

*Rôle de NetApp Console requis* Super administrateur de sauvegarde et de récupération.  En savoir plus surlink:reference-roles.html["Rôles et privilèges de sauvegarde et de récupération"] . https://docs.netapp.com/us-en/console-setup-admin/reference-iam-predefined-roles.html["En savoir plus sur les rôles d'accès à la NetApp Console pour tous les services"^] .



== Découvrez les charges de travail Kubernetes

Dans l’inventaire de sauvegarde et de récupération, découvrez les charges de travail Kubernetes dans votre environnement.  L'ajout d'une charge de travail ajoute un cluster Kubernetes à NetApp Backup and Recovery.  Vous pouvez ensuite ajouter des applications et protéger les ressources du cluster.

[NOTE]
====
Lorsque vous découvrez un cluster actuellement protégé avec Trident Protect, toutes les planifications de sauvegarde utilisées avec Trident Protect sont désactivées pendant le processus de découverte (les planifications de sauvegarde Trident Protect ne sont pas compatibles avec Backup and Recovery). Pour protéger les applications du cluster, link:br-use-policies-create.html["créer une nouvelle stratégie de protection"] ou associez les applications à une stratégie existante. Vous pouvez ensuite supprimer les planifications de sauvegarde Trident Protect si nécessaire.

====
.Étapes
. Effectuez l’une des opérations suivantes :
+
** Si vous découvrez les charges de travail Kubernetes pour la première fois, dans NetApp Backup and Recovery, sous *Charges de travail*, sélectionnez la vignette *Kubernetes*.
** Si vous avez déjà découvert des charges de travail Kubernetes, dans NetApp Backup and Recovery, sélectionnez *Inventaire* > *Charges de travail*, puis sélectionnez *Découvrir les ressources*.


. Sélectionnez le type de charge de travail *Kubernetes*.
. Saisissez un nom de cluster et choisissez un connecteur à utiliser avec le cluster.
. Suivez les instructions de la ligne de commande qui s’affichent :
+
** Créer un espace de noms Trident Protect
** Créer un secret Kubernetes
** Ajouter un dépôt Helm
** Installez ou mettez à niveau Trident Protect et le connecteur Trident Protect
+
Ces étapes garantissent que NetApp Backup and Recovery peut interagir avec le cluster.



. Une fois les étapes terminées, sélectionnez *Découvrir*.
+
Le cluster est ajouté à l'inventaire.

. Sélectionnez *Afficher* dans la charge de travail Kubernetes associée pour voir la liste des applications, des clusters et des espaces de noms pour cette charge de travail.




== Accéder au tableau de bord de NetApp Backup and Recovery

Suivez ces étapes pour afficher le tableau de bord de NetApp Backup and Recovery .

. Dans le menu de la NetApp Console , sélectionnez *Protection* > *Sauvegarde et récupération*.
. Sélectionnez une mosaïque de charge de travail (par exemple, Microsoft SQL Server).
. Dans le menu Sauvegarde et récupération, sélectionnez *Tableau de bord*.
. Examiner l’état de santé de la protection des données.  Le nombre de charges de travail à risque ou protégées augmente en fonction des charges de travail nouvellement découvertes, protégées et sauvegardées.
+
link:br-use-dashboard.html["Découvrez ce que le tableau de bord vous montre"].


