---
sidebar: sidebar 
permalink: br-start-switch-ui.html 
keywords: backing up, back up, backup, backup application data, Amazon Web services, AWS, NetApp Backup and Recovery, Oracle database, Microsoft SQL Server database, SAP HANA database 
summary: 'NetApp Backup and Recovery prend en charge plusieurs types de charges de travail, et certaines charges de travail utilisent une interface utilisateur différente. Utilisez le sélecteur de charges de travail pour passer de l"une à l"autre.' 
---
= Passer à une autre charge de travail NetApp Backup and Recovery
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
NetApp Backup and Recovery prend en charge plusieurs types de charges de travail, et certaines charges de travail utilisent une interface utilisateur différente. Utilisez le sélecteur de charges de travail pour passer de l'une à l'autre.



[[switch-to-a-different-workload]]
== Passer à une charge de travail différente

Vous pouvez basculer vers une charge de travail différente dans l'interface utilisateur de NetApp Backup and Recovery .

.Étapes
. Dans la navigation de gauche de la console, sélectionnez *Protection* > *Sauvegarde et récupération*.
. Dans le coin supérieur droit de la page, sélectionnez la liste déroulante *Changer de charge de travail*.
. Sélectionnez la charge de travail vers laquelle vous souhaitez basculer.
+
La page s'actualise et affiche la charge de travail sélectionnée.


