---
sidebar: sidebar 
permalink: br-start-login.html 
keywords: backing up, back up, backup, backup application data, Amazon Web services, AWS, NetApp Backup and Recovery, Oracle database, Microsoft SQL Server database, SAP HANA database 
summary: Vous utilisez la console NetApp pour vous connecter au service NetApp Backup and Recovery. 
---
= Connectez-vous à NetApp Backup and Recovery
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Vous utilisez la console NetApp pour vous connecter à NetApp Backup and Recovery.

NetApp Backup and Recovery utilise la gestion des identités et des accès pour régir l'accès de chaque utilisateur à des actions spécifiques.

Pour plus de détails sur les actions que chaque rôle peut effectuer, voirlink:reference-roles.html["Rôles utilisateur de NetApp Backup and Recovery"] .

Pour vous connecter à la console NetApp , vous pouvez utiliser vos informations d'identification du site de support NetApp ou vous inscrire pour une connexion à la console NetApp à l'aide de votre e-mail et d'un mot de passe. https://docs.netapp.com/us-en/console-setup-admin/task-logging-in.html["En savoir plus sur la connexion"^] .

*Rôle de console NetApp requis* Administrateur d'organisation, Administrateur de dossier ou de projet, Super administrateur de sauvegarde et de récupération, Rôle d'administrateur de restauration de sauvegarde et de récupération. https://docs.netapp.com/us-en/console-setup-admin/reference-iam-predefined-roles.html["En savoir plus sur les rôles d'accès à la console NetApp pour tous les services"^] .

Pour ajouter un agent de console, vous devez disposer du rôle d’administrateur d’organisation ou de super-administrateur de sauvegarde et de récupération.

.Étapes
. Ouvrez un navigateur Web et accédez à la https://console.netapp.com/["Console NetApp"^] .
+
La page de connexion à la console NetApp s’affiche.

. Connectez-vous à la console.
. Dans la navigation de gauche de la console, sélectionnez *Protection* > *Sauvegarde et récupération*.
+
** S'il s'agit de votre première connexion à ce service et que vous n'avez pas encore ajouté de système à la page *Systèmes*, la page d'accueil « Bienvenue dans la nouvelle solution NetApp Backup and Recovery » s'affiche et affiche une option permettant d'ajouter un système.  Pour plus de détails sur l'ajout d'un système à la page *Systèmes*, reportez-vous à https://docs.netapp.com/us-en/console-setup-admin/task-quick-start-standard-mode.html["Prise en main du mode standard de la console NetApp"^] .
** S'il s'agit de votre première connexion à ce service et que vous avez déjà ajouté un système à la page *Systèmes*, mais que vous n'avez découvert aucune ressource, la page d'accueil « Bienvenue dans la nouvelle sauvegarde et récupération NetApp » apparaît et affiche une option pour *Découvrir les ressources*.


. Si vous ne l’avez pas déjà fait, sélectionnez l’option *Découvrir et gérer*.  <<<<<<< TÊTE
+
** Pour les charges de travail Microsoft SQL Server, reportez-vous àlink:br-start-discover.html["Découvrez les charges de travail Microsoft SQL Server"] .
** Pour les charges de travail VMware, reportez-vous àlink:br-use-vmware-discovery.html["Découvrez les charges de travail VMware"] .
** Pour les charges de travail KVM, reportez-vous àlink:br-start-discover-kvm.html["Découvrez les charges de travail KVM"] .
** Pour les charges de travail Hyper-V, reportez-vous àlink:br-start-discover-hyperv.html["Découvrez les charges de travail Hyper-V"] .
** Pour les charges de travail Kubernetes, reportez-vous àlink:br-start-discover-kubernetes.html["Découvrez les charges de travail Kubernetes"] .




[]
====
+ * Pour les charges de travail Microsoft SQL Server, reportez-vous àlink:br-start-discover.html["Découvrez les charges de travail Microsoft SQL Server"] .  * Pour les charges de travail VMware, reportez-vous àlink:br-use-vmware-discovery.html["Découvrez les charges de travail VMware"] .  * Pour les charges de travail KVM, reportez-vous àlink:br-start-discover-kvm.html["Découvrez les charges de travail KVM"] .  * Pour les charges de travail Oracle, reportez-vous àlink:br-start-discover-oracle.html["Découvrez les charges de travail Oracle"] .  * Pour les charges de travail Kubernetes, reportez-vous àlink:br-start-discover-kubernetes.html["Découvrez les charges de travail Kubernetes"] .

>>>>>>> 6b2aaa82d1d2ec0ac72303b380f289e4a01ba4c6

====