---
sidebar: sidebar 
permalink: br-start-discover-kvm.html 
keywords: backing up, back up, backup, backup application data, Amazon Web services, AWS, NetApp Backup and Recovery, KVM, workloads, protect 
summary: NetApp Backup and Recovery doit d’abord découvrir les charges de travail afin que vous puissiez les protéger. 
---
= Découvrez les charges de travail KVM dans NetApp Backup and Recovery
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Découvrez les hôtes KVM et les machines virtuelles dans NetApp Backup and Recovery afin de les protéger à l'aide de politiques de protection. Votre environnement KVM doit être géré par une plateforme d'administration telle qu'Apache CloudStack avant la découverte.

*Rôle requis dans la NetApp Console* Super administrateur de NetApp Backup and Recovery. En savoir plus sur link:reference-roles.html["Rôles et privilèges de sauvegarde et de récupération"]. https://docs.netapp.com/us-en/console-setup-admin/reference-iam-predefined-roles.html["En savoir plus sur les rôles d'accès à la NetApp Console pour tous les services"^].



[[add-a-management-platform-kvm-host-and-discover-resources]]
== Ajoutez une plateforme de gestion, un hôte KVM et découvrez les ressources.

Ajoutez les informations relatives à la plateforme de gestion et à l'hôte KVM, et laissez NetApp Backup and Recovery découvrir les charges de travail.


NOTE: Après avoir ajouté un système de stockage à NetApp Console, patientez quelques minutes avant de découvrir les ressources. Découvrir les ressources immédiatement après avoir ajouté un système de stockage peut entraîner l'échec de la découverte.

.Étapes
. Dans le menu de la NetApp Console , sélectionnez *Protection* > *Sauvegarde et récupération*.
. Sous *Charges de travail*, sélectionnez la vignette *KVM*.
+
Si c'est la première fois que vous vous connectez à NetApp Backup and Recovery et que vous avez déjà un système dans la Console mais aucune ressource découverte, la page « Bienvenue dans le nouveau NetApp Backup and Recovery » apparaît avec une option pour *Découvrir les ressources*.

. Sélectionnez *Découvrir les ressources*.
. Saisissez les informations suivantes :
+
.. *Type de charge de travail* : sélectionnez *KVM*.
.. Si vous n'avez pas encore intégré votre plateforme de gestion à Backup and Recovery, sélectionnez *Ajouter une plateforme de gestion*.
+
... Saisissez les informations suivantes :
+
**** *Adresse IP ou nom de domaine complet (FQDN) de la plateforme de gestion* : Saisissez l’adresse IP ou un nom de domaine complet (FQDN) de la plateforme de gestion.
**** *Clé API* : Saisissez la clé API à utiliser pour authentifier les requêtes API.
**** *Clé secrète* : Saisissez la clé secrète à utiliser pour authentifier les requêtes API.
**** *Port* : Saisissez le port à utiliser pour la communication entre la sauvegarde et la restauration et la plateforme de gestion.
**** *Agents* : Sélectionnez un agent de console à utiliser pour faciliter la communication entre la sauvegarde et la restauration et la plateforme de gestion.


... Une fois terminé, sélectionnez *Ajouter*.


.. *Paramètres KVM* : Ajoutez un nouvel hôte KVM en saisissant les informations suivantes :
+
*** *Nom de domaine complet KVM ou adresse IP* : Saisissez le nom de domaine complet ou l’adresse IP de l’hôte.
*** *Identifiants* : Veuillez saisir le nom d’utilisateur et le mot de passe de l’hôte KVM.
*** *Agent de console* : Choisissez l’agent de console à utiliser pour la communication entre Backup and Recovery et l’hôte KVM.
*** *Numéro de port* : Saisissez le port à utiliser pour la communication entre Backup and Recovery et l’hôte KVM.
*** *Plateforme de gestion* : Si l’hôte KVM est géré et que vous avez ajouté la plateforme de gestion à Backup and Recovery, sélectionnez la plateforme de gestion dans la liste.




. Sélectionnez *Découvrir*.
+

TIP: Ce processus peut prendre quelques minutes.



.Résultat
La charge de travail KVM s'affiche dans la liste des charges de travail sur la page Inventaire.



[[continue-to-the-netapp-backup-and-recovery-dashboard]]
== Accéder au tableau de bord de NetApp Backup and Recovery

.Étapes
. Dans le menu de la NetApp Console , sélectionnez *Protection* > *Sauvegarde et récupération*.
. Sélectionnez la vignette de charge de travail KVM.
. Dans le menu Sauvegarde et récupération, sélectionnez *Tableau de bord*.
. Examiner l’état de santé de la protection des données.  Le nombre de charges de travail à risque ou protégées augmente en fonction des charges de travail nouvellement découvertes, protégées et sauvegardées.

