---
sidebar: sidebar 
permalink: br-start-discover-kvm.html 
keywords: backing up, back up, backup, backup application data, Amazon Web services, AWS, NetApp Backup and Recovery, KVM, workloads, protect 
summary: NetApp Backup and Recovery doit d’abord découvrir les charges de travail afin que vous puissiez les protéger. 
---
= Découvrez les charges de travail KVM dans NetApp Backup and Recovery
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
NetApp Backup and Recovery doit détecter les hôtes KVM et les machines virtuelles avant de les protéger. Vos hôtes KVM et vos machines virtuelles doivent être gérés par une plateforme de gestion telle qu'Apache CloudStack avant de pouvoir être ajoutés à la sauvegarde et à la restauration.

*Rôle de console requis* Super administrateur de sauvegarde et de récupération.  En savoir plus surlink:reference-roles.html["Rôles et privilèges de sauvegarde et de récupération"] . https://docs.netapp.com/us-en/console-setup-admin/reference-iam-predefined-roles.html["En savoir plus sur les rôles d'accès à la NetApp Console pour tous les services"^] .



== Ajoutez une plateforme de gestion, un hôte KVM et découvrez les ressources.

Ajoutez les informations relatives à la plateforme de gestion et à l'hôte KVM, et laissez NetApp Backup and Recovery découvrir les charges de travail.

.Étapes
. Dans le menu de la NetApp Console , sélectionnez *Protection > Sauvegarde et récupération*.
. Sous *Charges de travail*, sélectionnez la vignette *KVM*.
+
Si vous vous connectez à Backup and Recovery pour la première fois et que vous avez un système dans la console mais aucune ressource découverte, la page _Bienvenue sur le nouveau NetApp Backup and Recovery_ apparaît avec une option pour *Découvrir les ressources*.

. Sélectionnez *Découvrir les ressources*.
. Saisissez les informations suivantes :
+
.. *Type de charge de travail* : sélectionnez *KVM*.
.. Si vous n'avez pas encore intégré votre plateforme de gestion à Backup and Recovery, sélectionnez *Ajouter une plateforme de gestion*.
+
... Saisissez les informations suivantes :
+
**** *Adresse IP ou nom de domaine complet de la plateforme de gestion* : Saisissez l’adresse IP ou le nom de domaine complet de la plateforme de gestion.
**** *Clé API* : Saisissez la clé API à utiliser pour authentifier les requêtes API.
**** *Clé secrète* : Saisissez la clé secrète à utiliser pour authentifier les requêtes API.
**** *Port* : Saisissez le port à utiliser pour la communication entre la sauvegarde et la restauration et la plateforme de gestion.
**** *Agents* : Sélectionnez un agent de console à utiliser pour faciliter la communication entre la sauvegarde et la restauration et la plateforme de gestion.


... Une fois terminé, sélectionnez *Ajouter*.


.. *Paramètres KVM* : Ajoutez un nouvel hôte KVM en saisissant les informations suivantes :
+
*** *Nom de domaine complet KVM ou adresse IP* : Saisissez le nom de domaine complet ou l’adresse IP de l’hôte.
*** *Identifiants* : Veuillez saisir le nom d’utilisateur et le mot de passe de l’hôte KVM.
*** *Agent de console* : Choisissez l’agent de console à utiliser pour la communication entre Backup and Recovery et l’hôte KVM.
*** *Numéro de port* : Saisissez le port à utiliser pour la communication entre Backup and Recovery et l’hôte KVM.
*** *Plateforme de gestion* : Si l’hôte KVM est géré et que vous avez ajouté la plateforme de gestion à Backup and Recovery, sélectionnez la plateforme de gestion dans la liste.




. Sélectionnez *Découvrir*.
+

TIP: Ce processus peut prendre quelques minutes.



.Résultat
La charge de travail KVM s'affiche dans la liste des charges de travail sur la page Inventaire.



== Accéder au tableau de bord de NetApp Backup and Recovery

.Étapes
. Dans le menu de la NetApp Console , sélectionnez *Protection* > *Sauvegarde et récupération*.
. Sélectionnez une mosaïque de charge de travail (par exemple, Microsoft SQL Server).
. Dans le menu Sauvegarde et récupération, sélectionnez *Tableau de bord*.
. Examiner l’état de santé de la protection des données.  Le nombre de charges de travail à risque ou protégées augmente en fonction des charges de travail nouvellement découvertes, protégées et sauvegardées.

