---
sidebar: sidebar 
permalink: br-start-login.html 
keywords: backing up, back up, backup, backup application data, Amazon Web services, AWS, NetApp Backup and Recovery, Oracle database, Microsoft SQL Server database, SAP HANA database 
summary: Vous utilisez la NetApp Console pour vous connecter au service NetApp Backup and Recovery . 
---
= Connectez-vous à NetApp Backup and Recovery
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Connectez-vous à NetApp Backup and Recovery depuis NetApp Console pour découvrir les charges de travail et gérer les opérations de protection.

NetApp Backup and Recovery utilise la gestion des identités et des accès pour contrôler ce que chaque utilisateur peut faire.

Pour plus de détails sur les actions que chaque rôle peut effectuer, voirlink:reference-roles.html["Rôles utilisateur de NetApp Backup and Recovery"] .

Pour vous connecter à la NetApp Console, vous pouvez utiliser vos identifiants du site d'assistance NetApp, ou vous inscrire pour un compte NetApp Console en utilisant votre adresse e-mail et un mot de passe. https://docs.netapp.com/us-en/console-setup-admin/task-logging-in.html["En savoir plus sur la connexion"^]

*Rôle requis de la console NetApp* Super administrateur de sauvegarde et de restauration ou administrateur de restauration de sauvegarde et de restauration. Si vous protégez des données stockées sur un cluster Cloud Volumes ONTAP, le rôle d’administrateur Cloud Volumes ONTAP est également requis. https://docs.netapp.com/us-en/console-setup-admin/reference-iam-predefined-roles.html["En savoir plus sur les rôles d'accès à la NetApp Console pour tous les services"^]

Pour ajouter un agent de console, vous devez disposer du rôle de super administrateur de sauvegarde et de récupération.

.Étapes
. Effectuez l’une des opérations suivantes :
+
** Si vous utilisez la NetApp Console, ouvrez un navigateur Web et accédez à  https://console.netapp.com/["NetApp Console"^].
** Si vous utilisez le déploiement local de NetApp Console, ouvrez un navigateur web et accédez à l'adresse IP de l'interface utilisateur web de votre déploiement local Console.
+
La page de connexion à la NetApp Console s’affiche.



. Connectez-vous à la console.
. Dans la navigation de gauche de la console, sélectionnez *Protection* > *Sauvegarde et récupération*.
+
** Si vous vous connectez à Backup and Recovery pour la première fois et que vous n'avez pas encore ajouté de système à la page *Systèmes*, le service Backup and Recovery affiche la page d'accueil « Bienvenue dans la nouvelle NetApp Backup and Recovery » avec une option pour ajouter un système. Pour plus d'informations sur l'ajout d'un système à la page *Systèmes*, consultez  https://docs.netapp.com/us-en/console-setup-admin/task-quick-start-standard-mode.html["Prise en main du mode standard de la NetApp Console"^].
** Si vous vous connectez à Backup and Recovery pour la première fois et que vous avez un système dans la console mais aucune ressource découverte, la page _Bienvenue sur le nouveau NetApp Backup and Recovery_ apparaît avec une option pour *Découvrir les ressources*.


. Si vous ne l'avez pas déjà fait, sélectionnez *Discover and manage*.
+
** Pour les charges de travail Microsoft SQL Server, voir link:br-start-discover.html["Découvrez les charges de travail Microsoft SQL Server"].
** Pour les charges de travail VMware, voir link:br-use-vmware-discovery.html["Découvrez les charges de travail VMware"].
** Pour les charges de travail KVM, voir link:br-start-discover-kvm.html["Découvrez les charges de travail KVM"].
** Pour les charges de travail Oracle Database, voir link:br-start-discover-oracle.html["Découvrez les charges de travail Oracle Database"].
** Pour les charges de travail Hyper-V, voir link:br-start-discover-hyperv.html["Découvrez les charges de travail Hyper-V"].
** Pour les charges de travail Kubernetes, voir link:br-start-discover-kubernetes.html["Découvrez les charges de travail Kubernetes"].



