---
sidebar: sidebar 
permalink: br-use-oracle-restore.html 
keywords: restore, vm, oracle, databases, snapshots, object storage, cloud storage, backing up, back up, backup, backup application data, Amazon Web services, AWS, NetApp Backup and Recovery, Oracle database, Microsoft SQL Server database, SAP HANA database 
summary: Protégez vos charges de travail Oracle Database avec NetApp Backup and Recovery. 
---
= Restaurez les charges de travail de base de données Oracle avec NetApp Backup and Recovery
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Restaurez les charges de travail de la base de données Oracle à partir d'instantanés, de sauvegardes répliquées sur un stockage secondaire ou de sauvegardes stockées dans un stockage objet à l'aide de NetApp Backup and Recovery.

.Restaurer à partir de ces emplacements
Vous pouvez restaurer des bases de données à partir de différents emplacements de départ :

* Restaurer à partir d'un emplacement principal (instantané local)
* Restaurer à partir d'une ressource répliquée sur un stockage secondaire
* Restaurer à partir d'une sauvegarde de stockage d'objets


.Restaurer ces points
Vous pouvez restaurer les données à l'emplacement d'origine ; la restauration vers un autre emplacement n'est pas disponible dans cette version d'aperçu privée.

* Restaurer à l'emplacement d'origine




[[how-oracle-database-restore-works]]
== Comment fonctionne la restauration d'une base de données Oracle

Lorsque vous restaurez des charges de travail Oracle Database, les opérations suivantes se produisent :

* Lorsque vous restaurez une base de données à partir d'un snapshot local, NetApp Backup and Recovery crée une _nouvelle_ ressource à l'aide des données de la sauvegarde.
* Lorsque vous effectuez une restauration à partir d’un stockage répliqué, vous pouvez le restaurer à l’emplacement d’origine.
* Lorsque vous restaurez une sauvegarde à partir du stockage d'objets, vous pouvez restaurer les données vers le stockage source ou vers un système ONTAP local et récupérer la base de données à partir de là.


À partir de la page Restaurer (également appelée Rechercher et restaurer), vous pouvez restaurer une base de données, même si vous ne vous souvenez pas du nom exact, de l'emplacement où elle réside ou de la date à laquelle elle était en bon état pour la dernière fois.  Vous pouvez rechercher la base de données à l'aide de filtres.



[[restore-an-oracle-database]]
== Restaurer une base de données Oracle

Selon vos besoins, restaurez une base de données Oracle à un point précis dans le temps, à un numéro de modification système (SCN) spécifique ou à son dernier état fonctionnel. Vous pouvez également restaurer la base de données à partir d'instantanés et ignorer le processus de récupération automatique, par exemple si vous souhaitez effectuer la récupération manuellement. Vous pouvez rechercher la base de données par son nom ou à l'aide de filtres spécifiques.

*Rôle requis de la console NetApp* Rôle de super administrateur de NetApp Backup and Recovery ou rôle d'administrateur de restauration de NetApp Backup and Recovery. https://docs.netapp.com/us-en/console-setup-admin/reference-iam-predefined-roles.html["En savoir plus sur les rôles d'accès à la NetApp Console pour tous les services"^].

[NOTE]
====
Si vous restaurez des PDB ou des espaces de tables à un point précis dans le temps ou un SCN :

* Sélectionnez une seule PDB. La restauration à un point précis dans le temps n'est pas compatible avec la restauration de plusieurs PDB.
* `PDB$SEED` ne peut pas être sélectionné pour la restauration à un point précis dans le temps.
* La restauration du fichier de contrôle ne peut pas être combinée avec la restauration à un point précis dans le temps des PDB ou des espaces de tables PDB.
* Assurez-vous que la sauvegarde des données et les sauvegardes de journaux requises sont cataloguées.
* Les  `SYSTEM`, `SYSAUX`, et  `UNDO` espaces de tables ne peuvent pas être sélectionnés.
* Vérifiez que la sauvegarde des données et les sauvegardes de journaux requises sont cataloguées.


====
.Étapes
. Dans le menu de la NetApp Console , sélectionnez *Protection > Sauvegarde et récupération*.
. Dans le menu NetApp Backup and Recovery , sélectionnez *Restaurer*.
. Dans la liste déroulante à droite du champ de recherche de nom, sélectionnez *Oracle*.
. Saisissez le nom de la base de données que vous souhaitez restaurer ou filtrez l'hôte de base de données sur lequel se trouve la base de données que vous souhaitez restaurer.
+
Une liste d'instantanés correspondant à vos critères de recherche apparaît.

. Sélectionnez le bouton *Restaurer* pour la base de données que vous souhaitez restaurer.
. Choisissez une option de restauration :
+
[role="tabbed-block"]
====
.Restaurer à un moment précis
--
.. Sélectionnez *Restaurer à un moment précis*.
.. Sélectionnez *Suivant*.
.. Choisissez une date dans la liste déroulante et sélectionnez *Rechercher*.
+
L'instantané le plus proche de la date et de l'heure spécifiées est affiché.

.. Vous pouvez également sélectionner *Afficher les sauvegardes de journaux* pour consulter les sauvegardes de journaux associées.
+
... Vérifiez que les sauvegardes des journaux sont montées.


.. Si l'instantané est stocké à plusieurs emplacements, sélectionnez un emplacement source à utiliser et ajoutez ou vérifiez les détails de l'emplacement.
.. Sélectionnez *Suivant*.


--
.Restaurer vers un numéro de modification système spécifique (SCN)
--
.. Sélectionnez *Restaurer vers un numéro de modification système spécifique (SCN)*.
.. Sélectionnez *Suivant*.
.. Saisissez le SCN à utiliser comme point de restauration et sélectionnez *Rechercher*.
+
L'instantané le plus proche pour le SCN spécifié est affiché.

.. Vous pouvez également sélectionner *Afficher les sauvegardes de journaux* pour consulter les sauvegardes de journaux associées.
+
... Vérifiez que les sauvegardes des journaux sont montées.


.. Si l'instantané est stocké à plusieurs emplacements, sélectionnez un emplacement source à utiliser et ajoutez ou vérifiez les détails de l'emplacement.
.. Sélectionnez *Suivant*.


--
.Restaurer la dernière sauvegarde (dernier état correct)
--
.. Sélectionnez *Restaurer vers la dernière sauvegarde*.
.. Sélectionnez *Suivant*.
+
La dernière capture instantanée est affichée. L'opération de restauration récupère le dernier état fonctionnel à l'aide de toutes les sauvegardes de journaux disponibles.

.. Vous pouvez également sélectionner *Afficher les sauvegardes de journaux* pour consulter les sauvegardes de journaux associées.
+
... Vérifiez que les sauvegardes des journaux sont montées.


.. Si l'instantané est stocké à plusieurs emplacements, sélectionnez un emplacement source à utiliser et ajoutez ou vérifiez les détails de l'emplacement.
.. Sélectionnez *Suivant*.


--
.Restaurer à partir d'instantanés sans récupération
--
.. Sélectionnez *Restaurer à partir d'instantanés sans récupération*.
+
Sélectionner cette option signifie que la base de données sera restaurée à partir d'instantanés, mais la restauration de la base de données est ignorée (les sauvegardes des journaux ne sont pas appliquées).

.. Sélectionnez *Suivant*.
+
Les instantanés disponibles sont affichés.

.. Sélectionnez un instantané dans la liste et sélectionnez *Suivant*.
.. Si l'instantané est stocké à plusieurs emplacements, sélectionnez un emplacement source à utiliser et ajoutez ou vérifiez les détails de l'emplacement.
.. Sélectionnez *Suivant*.


--
====
. Choisissez la destination et les paramètres de restauration :
+
[role="tabbed-block"]
====
.Restaurer à l'emplacement d'origine
--
.. Dans la section *Paramètres de destination*, procédez comme suit :
+
... Pour les bases de données RAC, sélectionnez le nœud RAC sur lequel exécuter la restauration. Cette option apparaît uniquement pour les bases de données RAC.
... Sélectionnez ce que vous souhaitez restaurer :
+
**** Sélectionnez *Tous les fichiers de données* pour restaurer l'intégralité de la base de données ou de la base de données conteneur (CDB).
**** Sélectionnez *Bases de données enfichables (PDB)* pour restaurer une ou plusieurs PDB à partir d'une CDB sans affecter les autres PDB du conteneur. Sélectionnez ensuite les PDB dans la liste.
**** Sélectionnez *Espaces de tables de base de données enfichable (PDB)* (affichés sous le nom *Espaces de tables* pour une base de données non-CDB) pour restaurer des espaces de tables PDB spécifiques. Ensuite, sélectionnez la PDB et les espaces de tables.


... Vous pouvez activer l'option *Fichiers de contrôle* pour restaurer également les fichiers de contrôle de la base de données. Cette option ne peut pas être sélectionnée pour la restauration à un point précis dans le temps ou la restauration SCN des PDB ou des espaces de tables PDB.
... Vous pouvez, si vous le souhaitez, activer l’option *Modifier l’état de la base de données si nécessaire pour la restauration et la récupération* afin de permettre à NetApp Backup and Recovery de gérer l’état de la base de données en fonction du type de récupération.
... Vous pouvez activer l'option *Forcer la restauration sur place* pour effectuer une restauration sur place lorsque de nouveaux fichiers de données ont été ajoutés après la sauvegarde, ou lorsque des LUN ont été ajoutés, supprimés ou recréés dans un groupe de disques LVM. Cette option remplace la vérification des fichiers externes ; la restauration de la base de données se poursuit en utilisant l'option de restauration que vous avez sélectionnée.
... Spécifiez les emplacements des fichiers journaux d'archivage externes dans le champ *Emplacements des fichiers journaux d'archivage externes* si vous restaurez des PDB ou des espaces de tables à un point précis dans le temps ou à un SCN, et que les journaux d'archivage ne se trouvent pas à l'emplacement configuré. Saisissez un chemin de système de fichiers qui commence par  `/` ou un groupe de disques ASM qui commence par  `+`. Utilisez les boutons « plus » et « moins » à côté du champ de saisie de texte pour ajouter ou supprimer des emplacements. Ce champ n'apparaît pas lorsque vous effectuez une restauration à partir de snapshots sans restauration.
... Vous pouvez, si vous le souhaitez, activer l’option *Ouvrir la base de données ou la base de données conteneur en mode LECTURE-ÉCRITURE après la restauration de la base de données* et sélectionner une sous-option correspondant à l’étendue de la restauration (ces options n’apparaissent pas lors de la restauration à partir d’instantanés sans restauration de la base de données) :
+
**** *Tous les fichiers de données* : Ouvrez la base de données ou la base de données conteneur en mode LECTURE-ÉCRITURE après la restauration de la base de données.
**** *PDB ou espaces de tables PDB* : Ouvrez les bases de données enfichables en mode LECTURE-ÉCRITURE après la restauration de la base de données.
**** *Espaces de tables non-CDB* : Mettez les espaces de tables en ligne après la restauration.




.. Dans la section *Prescripts and postscripts*, procédez comme suit :
+
... *Script préalable* : Vous pouvez activer cette option et saisir le chemin complet d’un script à exécuter avant l’opération de restauration, ainsi que les arguments que ce script accepte.
... *Postscript* : Activez éventuellement cette option et saisissez le chemin complet d'un script qui doit être exécuté après l'opération de restauration et tous les arguments que le script prend.
... Choisissez une durée d'exécution pour le script. Si le script ne parvient pas à s'exécuter dans ce délai, la restauration se poursuivra malgré tout.




--
.Restaurer vers un autre emplacement
--
Non disponible pour les charges de travail Oracle Database dans cette version préliminaire.

--
====
. Sélectionnez *Restaurer*.

