---
sidebar: sidebar 
permalink: br-use-vmware-protect-overview.html 
keywords: backing up, back up, backup, backup application data, Amazon Web services, AWS, NetApp Backup and Recovery, Oracle database, Microsoft SQL Server database, SAP HANA database 
summary: Protégez vos charges de travail VMware avec NetApp Backup and Recovery. 
---
= Protégez les charges de travail VMware avec NetApp Backup and Recovery
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Utilisez NetApp Backup and Recovery pour protéger les machines virtuelles VMware et les datastores. Vous pouvez créer des sauvegardes rapides, économes en espace, cohérentes en cas de panne et cohérentes au niveau des machines virtuelles, les stocker sur des cibles de sauvegarde prises en charge et restaurer les charges de travail VMware sur un hôte VMware sur site.


NOTE: Cette version de NetApp Backup and Recovery prend uniquement en charge VMware vCenter et ne détecte pas les vVols ou les machines virtuelles sur les vVols.

Utilisez NetApp Backup and Recovery pour mettre en œuvre une stratégie 3-2-1 avec 3 copies de vos données sources sur 2 systèmes de stockage différents et 1 copie dans le cloud. Les avantages de l’approche 3-2-1 sont les suivants :

* Plusieurs copies de données protègent contre les menaces de cybersécurité internes et externes.
* L’utilisation de différents types de supports vous aide à récupérer si l’un d’eux tombe en panne.
* Vous pouvez rapidement restaurer à partir de la copie locale et utiliser les copies hors site si la copie locale est compromise.


Vous pouvez utiliser NetApp Backup and Recovery pour effectuer les tâches suivantes liées aux charges de travail VMware :

* link:br-use-vmware-discovery.html["Découvrez les charges de travail VMware"]
* link:br-use-vmware-protection-groups.html["Créer et gérer des groupes de protection pour les charges de travail VMware"]
* link:br-use-vmware-backup.html["Sauvegarder les charges de travail VMware"]
* link:br-use-vmware-restore.html["Restaurer les charges de travail VMware"]

