---
sidebar: sidebar 
permalink: br-use-mssql-protect-overview.html 
keywords: backing up, restoring, back up, backup, restore, cloud volumes ontap, aws, azure, s3, blob, google cloud, storagegrid, back up volumes, cloud backup, restore volumes, cost, on-premises ontap, onprem, applications, virtual machines, backup and recovery 
summary: 'Protégez les données de vos applications Microsoft SQL Server depuis les systèmes ONTAP locaux vers Amazon Web Services, Microsoft Azure ou StorageGRID à l"aide de NetApp Backup and Recovery.' 
---
= Présentation de la protection des charges de travail Microsoft SQL à l'aide de NetApp Backup and Recovery
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Sauvegardez les données de votre application Microsoft SQL Server à partir de systèmes ONTAP locaux vers AWS, Azure ou StorageGRID à l'aide de NetApp Backup and Recovery.  Le système crée et stocke automatiquement des sauvegardes dans votre compte cloud, conformément à vos politiques.  Utilisez une stratégie 3-2-1 : conservez trois copies de vos données sur deux systèmes de stockage et une copie dans le cloud.

Les avantages de l’approche 3-2-1 incluent :

* Plusieurs copies de données protègent contre les menaces de cybersécurité internes et externes.
* L’utilisation de différents types de supports vous aide à récupérer si l’un d’eux tombe en panne.
* Vous pouvez restaurer rapidement à partir de la copie sur site et utiliser les copies hors site si la copie sur site est compromise.


NetApp Backup and Recovery utilise NetApp SnapMirror pour synchroniser les sauvegardes en créant des instantanés et en les transférant vers les emplacements de sauvegarde.

Vous pouvez faire ce qui suit pour protéger vos données :

* link:concept-start-prereq-snapcenter-import.html["Configurer des éléments supplémentaires en cas d'importation depuis SnapCenter"]
* link:br-start-discover.html["Découvrez les charges de travail Microsoft SQL Server et importez éventuellement des ressources SnapCenter"]
* link:br-use-mssql-backup.html["Sauvegardez les charges de travail avec des snapshots locaux sur le stockage principal ONTAP local"]
* link:br-use-mssql-backup.html["Répliquer les charges de travail vers le stockage secondaire ONTAP"]
* link:br-use-mssql-backup.html["Sauvegarder les charges de travail vers un emplacement de stockage d'objets"]
* link:br-use-mssql-backup.html["Sauvegardez les charges de travail maintenant"]
* link:br-use-mssql-restore.html["Restaurer les charges de travail"]
* link:br-use-mssql-clone.html["Cloner les charges de travail"]
* link:br-use-manage-inventory.html["Gérer l'inventaire des charges de travail"]
* link:br-use-manage-snapshots.html["Gérer les instantanés"]


Pour sauvegarder les charges de travail, vous créez des stratégies qui gèrent les opérations de sauvegarde et de restauration. Voirlink:br-use-policies-create.html["Créer des politiques"] pour plus d'informations.

.Destinations de sauvegarde prises en charge
NetApp Backup and Recovery vous permet de sauvegarder des instances et des bases de données Microsoft SQL Server à partir des systèmes sources suivants vers les systèmes secondaires et le stockage objet suivants, chez les fournisseurs de cloud public et privé. Les instantanés résident sur le système source.

[cols="33,33,33"]
|===
| Système source | Système secondaire (réplication) | Magasin d'objets de destination (sauvegarde) 


| Cloud Volumes ONTAP dans AWS | Cloud Volumes ONTAP dans le système ONTAP sur site AWS | Amazon S3 ONTAP S3 


| Cloud Volumes ONTAP dans Azure | Cloud Volumes ONTAP dans le système ONTAP sur site Azure | Azure Blob ONTAP S3 


| Système ONTAP sur site | Cloud Volumes ONTAP Système ONTAP sur site | Amazon S3 Azure Blob NetApp StorageGRID ONTAP S3 


| Amazon FSx for NetApp ONTAP | Amazon FSx for NetApp ONTAP | N / A 
|===
.Destinations de restauration prises en charge
Vous pouvez restaurer des instances et des bases de données Microsoft SQL Server à partir d’une sauvegarde qui réside dans le stockage principal ou un système secondaire (un volume répliqué) ou dans le stockage d’objets (un fichier de sauvegarde) sur les systèmes suivants. Les instantanés résident sur le système source et ne peuvent être restaurés que sur ce même système.

[cols="33,33,33"]
|===
2+| À partir de l'emplacement du fichier de sauvegarde | Vers le système de destination 


| *Magasin d'objets (sauvegarde)* | *Système secondaire (réplication)* |  


| Amazon S3 | Cloud Volumes ONTAP dans le système ONTAP sur site AWS | Volumes cloud dans le système ONTAP sur site AWS ONTAP S3 


| Azure Blob | Cloud Volumes ONTAP dans le système ONTAP sur site Azure | Cloud Volumes ONTAP dans Azure, système ONTAP local , ONTAP S3 


| StorageGRID | Cloud Volumes ONTAP Système ONTAP sur site | Système ONTAP sur site ONTAP S3 
|===

NOTE: Les références aux « systèmes ONTAP sur site » incluent les systèmes FAS et AFF .
