---
sidebar: sidebar 
permalink: br-use-kvm-protect-overview.html 
keywords: backing up, restoring, back up, backup, restore, cloud volumes ontap, aws, azure, s3, blob, google cloud, storagegrid, back up volumes, cloud backup, restore volumes, cost, on-premises ontap, onprem, applications, virtual machines, backup and recovery 
summary: Vous pouvez protéger les machines virtuelles KVM des systèmes ONTAP sur site vers Amazon Web Services, Microsoft Azure, Google Cloud Platform et StorageGRID, garantissant ainsi la protection de vos données. 
---
= Flux de travail de protection KVM avec NetApp Backup and Recovery
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Protégez vos machines virtuelles KVM gérées et vos pools de stockage avec NetApp Backup and Recovery. Le service offre des opérations de sauvegarde et de restauration rapides, économes en espace, cohérentes en cas de panne et cohérentes au niveau des machines virtuelles.

Vos hôtes KVM et vos machines virtuelles doivent être gérés par une plateforme telle qu'Apache CloudStack avant que vous puissiez les protéger avec NetApp Backup and Recovery.

Utilisez NetApp Backup and Recovery pour mettre en œuvre une stratégie de protection 3-2-1, où vous disposez de 3 copies de vos données sources sur 2 systèmes de stockage différents ainsi que d'une copie dans le cloud. Les avantages de l’approche 3-2-1 incluent :

* Plusieurs copies de données protègent contre les menaces de cybersécurité internes et externes.
* L'utilisation de différents types de supports vous aide à récupérer si un type tombe en panne.
* Vous pouvez restaurer rapidement à partir de la copie sur site et utiliser les copies hors site si la copie sur site est compromise.


Vous pouvez utiliser NetApp Backup and Recovery pour effectuer les tâches suivantes pour les charges de travail KVM :

* link:br-start-discover-kvm.html["Découvrez les charges de travail KVM"]
* link:br-use-kvm-protection-groups.html["Créer et gérer des groupes de protection pour les charges de travail KVM"]
* link:br-use-kvm-backup.html["Sauvegarder les charges de travail KVM"]
* link:br-use-kvm-restore.html["Restaurer les charges de travail KVM"]

