---
sidebar: sidebar 
permalink: br-use-kvm-restore.html 
keywords: restore, vm, kvm, virtual machine, snapshots, object storage, cloud storage, backing up, back up, backup, backup application data, Amazon Web services, AWS, NetApp Backup and Recovery, Oracle database, Microsoft SQL Server database, SAP HANA database 
summary: Protégez vos charges de travail KVM avec NetApp Backup and Recovery. 
---
= Restaurer les machines virtuelles KVM avec NetApp Backup and Recovery
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Restaurez des machines virtuelles KVM à partir d'instantanés, d'une sauvegarde de groupe de protection répliquée sur un stockage secondaire ou de sauvegardes stockées dans un stockage objet à l'aide de NetApp Backup and Recovery.

.Restaurer à partir de ces emplacements
Vous pouvez restaurer des machines virtuelles à partir de différents emplacements de départ :

* Restaurer à partir d'un emplacement principal (instantané local)
* Restaurer à partir d'une ressource répliquée sur un stockage secondaire
* Restaurer à partir d'une sauvegarde de stockage d'objets


.Restaurer ces points
Vous pouvez restaurer les données à ces points :

* Restaurer à l'emplacement d'origine


.Considérations relatives à la restauration à partir du stockage d'objets
Si vous sélectionnez un fichier de sauvegarde dans le stockage d'objets et que la protection contre les ransomwares est active pour cette sauvegarde (si vous avez activé DataLock et Ransomware Resilience dans la stratégie de sauvegarde), vous êtes invité à exécuter une vérification d'intégrité supplémentaire sur le fichier de sauvegarde avant de restaurer les données.  Nous vous recommandons d'effectuer l'analyse.


TIP: Des frais de sortie supplémentaires seront facturés par votre fournisseur de cloud pour accéder au contenu du fichier de sauvegarde.



== Comment fonctionne la restauration des machines virtuelles

Lorsque vous restaurez des machines virtuelles, les événements suivants se produisent :

* Lorsque vous restaurez une charge de travail à partir d'un fichier de sauvegarde local, NetApp Backup and Recovery crée une _nouvelle_ ressource à l'aide des données de la sauvegarde.
* Lorsque vous effectuez une restauration à partir d’une machine virtuelle répliquée, vous pouvez la restaurer sur le système d’origine ou sur un système ONTAP local.
* Lorsque vous restaurez une sauvegarde à partir du stockage d’objets, vous pouvez restaurer les données sur le système d’origine ou sur un système ONTAP local.


À partir de la page Restaurer (également appelée Rechercher et restaurer), vous pouvez restaurer une machine virtuelle, même si vous ne vous souvenez pas du nom exact, de l'emplacement où elle réside ou de la date à laquelle elle était en bon état pour la dernière fois. Vous pouvez rechercher l'instantané à l'aide de filtres.



== Restaurer les machines virtuelles à partir de l'option Restaurer (Rechercher et restaurer)

Restaurez les machines virtuelles KVM à l’aide de l’option Restaurer. Vous pouvez rechercher l'instantané par son nom ou en utilisant des filtres.

*Rôle de console requis* Rôle de super administrateur de sauvegarde et de récupération ou d'administrateur de restauration de sauvegarde et de récupération. https://docs.netapp.com/us-en/console-setup-admin/reference-iam-predefined-roles.html["En savoir plus sur les rôles d'accès à la NetApp Console pour tous les services"^] .

.Étapes
. Dans le menu de la NetApp Console , sélectionnez *Protection > Sauvegarde et récupération*.
. Dans le menu NetApp Backup and Recovery , sélectionnez *Restaurer*.
. Dans la liste déroulante à droite du champ de recherche de nom, sélectionnez *KVM*.
. Saisissez le nom de la machine virtuelle que vous souhaitez restaurer ou filtrez l’hôte de la machine virtuelle ou le pool de stockage où se trouve la ressource que vous souhaitez restaurer.
+
Une liste d'instantanés correspondant à vos critères de recherche apparaît.

. Sélectionnez le bouton *Restaurer* pour l’instantané que vous souhaitez restaurer.
+
Une liste de points de restauration possibles apparaît.

. Sélectionnez le point de restauration que vous souhaitez utiliser.
. Sélectionnez un emplacement source d’instantané.


. Sélectionnez *Suivant* pour continuer.
. Choisissez la destination et les paramètres de restauration :


[discrete]
===== Sélection de la destination

[role="tabbed-block"]
====
.Restaurer à l'emplacement d'origine
--
. *Activer la restauration rapide* : sélectionnez cette option pour effectuer une opération de restauration rapide. Les volumes et données restaurés seront disponibles immédiatement. N'utilisez pas cette option sur des volumes nécessitant des performances élevées, car pendant le processus de restauration rapide, l'accès aux données peut être plus lent que d'habitude.
. *Options de pré-restauration* : saisissez le chemin complet d'un script qui doit être exécuté avant l'opération de restauration et tous les arguments que le script prend.
. *Options post-restauration*:
+
** *Redémarrer la machine virtuelle* : sélectionnez cette option pour redémarrer la machine virtuelle une fois l'opération de restauration terminée et une fois le script de post-restauration appliqué.
** *Postscript* : Saisissez le chemin complet d'un script qui doit être exécuté après l'opération de restauration et tous les arguments que le script prend.


. Section *Notification* :
+
** *Activer les notifications par e-mail* : sélectionnez cette option pour recevoir des notifications par e-mail concernant l'opération de restauration et indiquez le type de notifications que vous souhaitez recevoir.


. Sélectionnez *Restaurer*.


--
.Restaurer vers un autre emplacement
--
Non disponible pour les charges de travail KVM.

--
====