---
sidebar: sidebar 
permalink: br-use-oracle-restore.html 
keywords: restore, vm, oracle, databases, snapshots, object storage, cloud storage, backing up, back up, backup, backup application data, Amazon Web services, AWS, NetApp Backup and Recovery, Oracle database, Microsoft SQL Server database, SAP HANA database 
summary: Protégez vos charges de travail Oracle Database avec NetApp Backup and Recovery. 
---
= Restaurez les charges de travail de base de données Oracle avec NetApp Backup and Recovery
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Restaurez les charges de travail de la base de données Oracle à partir d'instantanés, de sauvegardes répliquées sur un stockage secondaire ou de sauvegardes stockées dans un stockage objet à l'aide de NetApp Backup and Recovery.

.Restaurer à partir de ces emplacements
Vous pouvez restaurer des bases de données à partir de différents emplacements de départ :

* Restaurer à partir d'un emplacement principal (instantané local)
* Restaurer à partir d'une ressource répliquée sur un stockage secondaire
* Restaurer à partir d'une sauvegarde de stockage d'objets


.Restaurer ces points
Vous pouvez restaurer les données à l'emplacement d'origine ; la restauration vers un autre emplacement n'est pas disponible dans cette version d'aperçu privée.

* Restaurer à l'emplacement d'origine




[[how-oracle-database-restore-works]]
== Comment fonctionne la restauration d'une base de données Oracle

Lorsque vous restaurez des charges de travail Oracle Database, les opérations suivantes se produisent :

* Lorsque vous restaurez une base de données à partir d'un snapshot local, NetApp Backup and Recovery crée une _nouvelle_ ressource à l'aide des données de la sauvegarde.
* Lorsque vous effectuez une restauration à partir d’un stockage répliqué, vous pouvez le restaurer à l’emplacement d’origine.
* Lorsque vous restaurez une sauvegarde à partir du stockage d'objets, vous pouvez restaurer les données vers le stockage source ou vers un système ONTAP local et récupérer la base de données à partir de là.


À partir de la page Restaurer (également appelée Rechercher et restaurer), vous pouvez restaurer une base de données, même si vous ne vous souvenez pas du nom exact, de l'emplacement où elle réside ou de la date à laquelle elle était en bon état pour la dernière fois.  Vous pouvez rechercher la base de données à l'aide de filtres.



[[restore-an-oracle-database]]
== Restaurer une base de données Oracle

Selon vos besoins, restaurez une base de données Oracle à un point précis dans le temps, à un numéro de modification système (SCN) spécifique ou à son dernier état fonctionnel. Vous pouvez également restaurer la base de données à partir d'instantanés et ignorer le processus de récupération automatique, par exemple si vous souhaitez effectuer la récupération manuellement. Vous pouvez rechercher la base de données par son nom ou à l'aide de filtres spécifiques.

*Rôle requis de la console NetApp* Rôle de super administrateur de NetApp Backup and Recovery ou rôle d'administrateur de restauration de NetApp Backup and Recovery. https://docs.netapp.com/us-en/console-setup-admin/reference-iam-predefined-roles.html["En savoir plus sur les rôles d'accès à la NetApp Console pour tous les services"^].

.Étapes
. Dans le menu de la NetApp Console , sélectionnez *Protection > Sauvegarde et récupération*.
. Dans le menu NetApp Backup and Recovery , sélectionnez *Restaurer*.
. Dans la liste déroulante à droite du champ de recherche de nom, sélectionnez *Oracle*.
. Saisissez le nom de la base de données que vous souhaitez restaurer ou filtrez l'hôte de base de données sur lequel se trouve la base de données que vous souhaitez restaurer.
+
Une liste d'instantanés correspondant à vos critères de recherche apparaît.

. Sélectionnez le bouton *Restaurer* pour la base de données que vous souhaitez restaurer.
. Choisissez une option de restauration :
+
[role="tabbed-block"]
====
.Restaurer à un moment précis
--
.. Sélectionnez *Restaurer à un moment précis*.
.. Sélectionnez *Suivant*.
.. Choisissez une date dans la liste déroulante et sélectionnez *Rechercher*.
+
Une liste des instantanés correspondants à la date spécifiée s'affiche.



--
.Restaurer vers un numéro de modification système spécifique (SCN)
--
.. Sélectionnez *Restaurer vers un numéro de modification système spécifique (SCN)*.
.. Sélectionnez *Suivant*.
.. Saisissez le SCN à utiliser comme point de restauration et sélectionnez *Rechercher*.
+
Une liste des instantanés correspondants pour le SCN spécifié s'affiche.



--
.Restaurer la dernière sauvegarde (dernier état correct)
--
.. Sélectionnez *Restaurer vers la dernière sauvegarde*.
.. Sélectionnez *Suivant*.
+
Les dernières sauvegardes complètes et journaux sont affichés.



--
.Restaurer à partir d'instantanés sans récupération
--
.. Sélectionnez *Restaurer à partir d'instantanés sans récupération*.
.. Sélectionnez *Suivant*.
+
Les instantanés correspondants sont affichés.



--
====
. Sélectionnez un emplacement source d’instantané.
. Sélectionnez *Suivant* pour continuer.
. Choisissez la destination et les paramètres de restauration :


[discrete]
===== Sélection de la destination

[role="tabbed-block"]
====
.Restaurer à l'emplacement d'origine
--
[NOTE]
====
Si vous restaurez des PDB ou des espaces de tables PDB à un point précis dans le temps ou à un SCN spécifique :

* Sélectionnez une seule PDB. La restauration à un point précis dans le temps n'est pas compatible avec la restauration de plusieurs PDB.
* La base de données PDB$SEED ne peut pas être sélectionnée pour la récupération à un point précis dans le temps.
* La restauration du fichier de contrôle ne peut pas être combinée avec la récupération à un point précis dans le temps des PDB ou des espaces de tables.
* Assurez-vous que la sauvegarde des données et les sauvegardes de journaux requises sont cataloguées.


====
. *Paramètres de destination*:
. Sélectionnez ce que vous souhaitez restaurer :
+
** Sélectionnez *Tous les fichiers de données* pour restaurer l'intégralité de la base de données ou de la base de données conteneur (CDB).
** Sélectionnez *Bases de données enfichables (PDB)* pour restaurer une ou plusieurs PDB à partir d'une CDB sans affecter les autres PDB du conteneur. Sélectionnez ensuite les PDB dans la liste.
** Sélectionnez *Espaces de tables de base de données enfichable (PDB)* (affichés sous le nom *Espaces de tables* pour une base de données non-CDB) pour restaurer des espaces de tables PDB spécifiques. Ensuite, sélectionnez la PDB et les espaces de tables.


. Vous pouvez activer l'option *fichiers de contrôle* pour restaurer également les fichiers de contrôle de la base de données. Cette option n'est pas disponible pour la restauration à un point précis dans le temps ou la restauration SCN des PDB ou des espaces de tables PDB.
. Vous pouvez, si vous le souhaitez, activer l’option *Modifier l’état de la base de données si nécessaire pour la restauration et la récupération* afin de permettre à NetApp Backup and Recovery de gérer l’état de la base de données en fonction du type de récupération.
. Vous pouvez activer l'option *Forcer la restauration sur place* pour utiliser une méthode de restauration plus rapide pour les bases de données SAN/ASM, en ignorant la vérification de validation des fichiers externes. La base de données et le groupe de disques ASM sont restaurés au point de création de la sauvegarde.
. Spécifiez l'emplacement des fichiers journaux d'archivage externes si vous restaurez des PDB ou des espaces de tables PDB à un point précis dans le temps ou à un SCN spécifique. Indiquez l'emplacement où RMAN crée l'instance auxiliaire pour effectuer la récupération. Saisissez un chemin de système de fichiers commençant par « / » ou un groupe de disques ASM commençant par « + ». Utilisez les boutons « plus » et « moins » situés à côté du champ de saisie de texte pour ajouter ou supprimer des emplacements.
. Vous pouvez activer l’option *Ouvrir la base de données ou base de données conteneur en mode LECTURE-ÉCRITURE après la récupération* pour ouvrir les bases de données en mode LECTURE-ÉCRITURE après leur restauration. Cela remet les espaces de tables restaurés en ligne.
. *Prescripts et postscripts* :
+
** *Script préalable* : Vous pouvez activer cette option et saisir le chemin complet d’un script à exécuter avant l’opération de restauration, ainsi que les arguments que ce script accepte.
** *Postscript* : Activez éventuellement cette option et saisissez le chemin complet d'un script qui doit être exécuté après l'opération de restauration et tous les arguments que le script prend.


. Choisissez une durée d'exécution pour le script. Si le script ne parvient pas à s'exécuter dans ce délai, la restauration se poursuivra malgré tout.
. Sélectionnez *Restaurer*.


--
.Restaurer vers un autre emplacement
--
Non disponible pour les charges de travail Oracle Database dans cette version préliminaire.

--
====