---
sidebar: sidebar 
permalink: br-use-kvm-restore.html 
keywords: restore, vm, kvm, virtual machine, snapshots, object storage, cloud storage, backing up, back up, backup, backup application data, Amazon Web services, AWS, NetApp Backup and Recovery, Oracle database, Microsoft SQL Server database, SAP HANA database 
summary: Protégez vos charges de travail KVM avec NetApp Backup and Recovery. 
---
= Restaurer les machines virtuelles KVM avec NetApp Backup and Recovery
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Restaurez des machines virtuelles KVM à partir d'instantanés, d'une sauvegarde de groupe de protection répliquée sur un stockage secondaire ou de sauvegardes stockées dans un stockage objet à l'aide de NetApp Backup and Recovery.

.Restaurer à partir de ces emplacements
Vous pouvez restaurer des machines virtuelles à partir de différents emplacements de départ :

* Restaurer à partir d'un emplacement principal (instantané local)
* Restaurer à partir d'une ressource répliquée sur un stockage secondaire
* Restaurer à partir d'une sauvegarde de stockage d'objets


.Restaurer ces points
Vous pouvez restaurer les données à ces points :

* Restaurer à l'emplacement d'origine
* Restaurer à un autre emplacement


.Considérations relatives à la restauration à partir du stockage d'objets
Si vous sélectionnez un fichier de sauvegarde dans le stockage d'objets et que la protection contre les ransomwares est active pour cette sauvegarde (si vous avez activé DataLock et Ransomware Resilience dans la stratégie de sauvegarde), vous êtes invité à exécuter une vérification d'intégrité supplémentaire sur le fichier de sauvegarde avant de restaurer les données.  Nous vous recommandons d'effectuer l'analyse.


TIP: Des frais de sortie supplémentaires seront facturés par votre fournisseur de cloud pour accéder au contenu du fichier de sauvegarde.



== Comment fonctionne la restauration des machines virtuelles

Lorsque vous restaurez des machines virtuelles, les événements suivants se produisent :

* Lorsque vous restaurez une charge de travail à partir d'un fichier de sauvegarde local, NetApp Backup and Recovery crée une _nouvelle_ ressource à l'aide des données de la sauvegarde.
* Lorsque vous effectuez une restauration à partir d’une machine virtuelle répliquée, vous pouvez la restaurer sur le système d’origine ou sur un système ONTAP local.
* Lorsque vous restaurez une sauvegarde à partir du stockage d’objets, vous pouvez restaurer les données sur le système d’origine ou sur un système ONTAP local.


Depuis la page Restaurer, vous pouvez restaurer une machine virtuelle, même si vous ne vous souvenez pas de son nom exact, de son emplacement ou de la date à laquelle elle était en bon état. Vous pouvez rechercher l'instantané à l'aide de filtres.



== Restaurez les machines virtuelles KVM

Restaurez les machines virtuelles KVM à l'aide du menu Restaurer. Vous pouvez rechercher l'instantané par son nom ou à l'aide de filtres.

*Rôle de console requis* Rôle de super administrateur de sauvegarde et de récupération ou d'administrateur de restauration de sauvegarde et de récupération. https://docs.netapp.com/us-en/console-setup-admin/reference-iam-predefined-roles.html["En savoir plus sur les rôles d'accès à la NetApp Console pour tous les services"^] .

.Étapes
. Dans le menu de la NetApp Console , sélectionnez *Protection > Sauvegarde et récupération*.
. Dans le menu NetApp Backup and Recovery , sélectionnez *Restaurer*.
. Dans la liste déroulante à droite du champ de recherche de nom, sélectionnez *KVM*.
. Saisissez le nom de la machine virtuelle que vous souhaitez restaurer ou filtrez l’hôte de la machine virtuelle ou le pool de stockage où se trouve la ressource que vous souhaitez restaurer.
+
Une liste d'instantanés correspondant à vos critères de recherche apparaît.

. Sélectionnez le bouton *Restaurer* pour l’instantané que vous souhaitez restaurer.
+
Une liste de points de restauration possibles apparaît.

. Sélectionnez le point de restauration que vous souhaitez utiliser.
. Sélectionnez un emplacement source d’instantané.
. Sélectionnez *Suivant* pour continuer.
. Choisissez la destination et les paramètres de restauration :
+
[discrete]
===== Sélection de la destination

+
[role="tabbed-block"]
====
.Restaurer à l'emplacement d'origine
--
.. Sélectionnez le volet *Emplacement d'origine*.
.. Dans la section *Options post-restauration*, activez l'option *Redémarrer la machine virtuelle* pour redémarrer la machine virtuelle une fois l'opération de restauration terminée.


--
.Restaurer vers un autre emplacement
--
.. Sélectionnez le volet *Emplacement alternatif*.
.. Dans la section *Paramètres Cloudstack*, veuillez fournir les informations suivantes :
+
*** *Zone* : Choisissez une zone de destination CloudStack dans la liste.
*** *Pod* : Choisissez un pod de destination dans la zone sélectionnée à partir de la liste.
*** *Cluster* : Choisissez un cluster de destination au sein du pod sélectionné dans la liste.
*** *Hôte* : Choisissez un hôte de destination dans le cluster à partir de la liste.
*** *Pool de stockage* : Choisissez un pool de stockage de destination dans la liste (le volume de destination doit se trouver ici).
*** *Réseau* : Sélectionnez le réseau auquel la machine virtuelle restaurée sera connectée.
*** *Nom de la machine virtuelle* : Saisissez un nom pour la machine virtuelle à restaurer.
*** *Nom d'affichage* : Saisissez le nom qui doit s'afficher pour cette VM dans Backup and Recovery.
*** *Chemin du pool de stockage* : Saisissez le chemin du pool de stockage où les volumes de la machine virtuelle seront stockés.


.. Choisissez une offre de service qui définit votre niveau préféré d'allocation de ressources dans la liste *Sélectionnez une offre de service*.
.. Activez l'option *Forcé* pour importer la machine virtuelle restaurée même si une ou plusieurs adresses MAC des cartes réseau de la machine virtuelle sont déjà présentes. Si une adresse MAC existe déjà, une nouvelle adresse MAC est générée pour cette carte réseau.
.. Dans la section *Options après restauration*, considérez les options suivantes :
+
*** *Redémarrer la machine virtuelle* : Activez cette option pour démarrer la nouvelle machine virtuelle après sa restauration.




--
====
. Sélectionnez *Restaurer*.

