---
sidebar: sidebar 
permalink: br-use-manage-overview.html 
keywords: backing up, restoring, back up, backup, restore, cloud volumes ontap, aws, azure, s3, blob, google cloud, storagegrid, back up volumes, cloud backup, restore volumes, cost, on-premises ontap, onprem, applications, virtual machines, backup and recovery 
summary: 'Vous pouvez sauvegarder les données des applications Microsoft SQL Server à partir des systèmes ONTAP locaux vers Amazon Web Services, Microsoft Azure, Google Cloud Platform et StorageGRID, garantissant ainsi la protection de vos données. Les sauvegardes sont automatiquement générées et stockées dans un magasin d’objets sur votre compte cloud public ou privé.  Vous pouvez mettre en œuvre une stratégie 3-2-1, où vous disposez de 3 copies de vos données sources sur 2 systèmes de stockage différents ainsi que d"une copie dans le cloud.' 
---
= Présentation de la gestion des ressources avec NetApp Backup and Recovery
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
La gestion des ressources dans NetApp Backup and Recovery est essentielle pour garantir la protection de vos données.  Vous pouvez gérer des ressources telles que des sauvegardes, des bases de données, des instances, des hôtes d’applications et des environnements de travail.  Vous pouvez afficher, modifier et supprimer les paramètres de protection de vos ressources.

Vous pouvez accomplir les tâches suivantes liées à la gestion de vos ressources :

* link:br-use-manage-inventory.html["Gérer l'inventaire"] .
* link:br-use-manage-snapshots.html["Gérer les instantanés"] .
* link:br-use-manage-kubernetes-clusters.html["Gérer les clusters Kubernetes"] .
* link:br-use-manage-kubernetes-applications.html["Gérer les applications Kubernetes"] .

