---
sidebar: sidebar 
permalink: br-use-restore-kubernetes-applications.html 
keywords: backing up, restoring, back up, backup, restore, cloud volumes ontap, aws, azure, s3, blob, google cloud, storagegrid, back up volumes, cloud backup, restore volumes, cost, on-premises ontap, onprem, applications, virtual machines, backup and recovery 
summary: NetApp Backup and Recovery vous permet de restaurer les applications que vous avez protégées avec une politique de protection. 
---
= Restaurez les applications Kubernetes à l'aide de l'interface utilisateur Web
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
NetApp Backup and Recovery vous permet de restaurer les applications que vous avez protégées avec une politique de protection. Pour restaurer une application, celle-ci doit disposer d'au moins un point de restauration. Un point de restauration est constitué soit de l'instantané local, soit de la sauvegarde dans le magasin d'objets (ou des deux). Vous pouvez restaurer une application à partir de l'archive locale, secondaire ou du magasin d'objets.

.Avant de commencer
Si vous restaurez une application qui a été sauvegardée à l'aide de Trident Protect, assurez-vous que Trident Protect est installé sur les clusters source et de destination.

.Rôle de NetApp Console requis
Administrateur d'organisation ou administrateur SnapCenter . link:reference-roles.html["En savoir plus sur les rôles d'accès à NetApp Backup and Recovery"] . https://docs.netapp.com/us-en/console-setup-admin/reference-iam-predefined-roles.html["En savoir plus sur les rôles d'accès à la NetApp Console pour tous les services"^] .

.Étapes
. Dans le menu NetApp Backup and Recovery, sélectionnez *Restaurer*.
. Choisissez une application Kubernetes dans la liste, et sélectionnez *Afficher et restaurer* pour cette application.
+
La liste des points de restauration apparaît.

. Sélectionnez le bouton *Restore* pour le point de restauration que vous souhaitez utiliser.


[discrete]
===== Paramètres généraux

. Choisissez l'emplacement source à partir duquel effectuer la restauration.
. Choisissez le cluster de destination dans la liste *Cluster*.
+

NOTE: La restauration d'un instantané local créé par Trident Protect vers un cluster différent n'est pas prise en charge pour le moment.

. Choisissez de restaurer vers les espaces de noms d'origine ou vers de nouveaux espaces de noms.
. Si vous avez choisi de restaurer dans de nouveaux espaces de noms, saisissez le ou les espaces de noms de destination à utiliser.
. Sélectionnez *Suivant*.


[discrete]
===== Sélection des ressources

. Choisissez si vous souhaitez restaurer toutes les ressources associées à l'application ou utiliser un filtre pour sélectionner des ressources spécifiques à restaurer :


[role="tabbed-block"]
====
.Restaurer toutes les ressources
--
. Sélectionnez *Restaurer toutes les ressources*.
. Sélectionnez *Suivant*.


--
.Restaurer des ressources spécifiques
--
. Sélectionnez *Ressources sélectives*.
. Choisissez le comportement du filtre de ressources.  Si vous choisissez *Inclure*, les ressources que vous sélectionnez sont restaurées.  Si vous choisissez *Exclure*, les ressources que vous sélectionnez ne sont pas restaurées.
. Sélectionnez *Ajouter des règles* pour ajouter des règles qui définissent des filtres pour la sélection des ressources.  Vous avez besoin d’au moins une règle pour filtrer les ressources.
+
Chaque règle peut filtrer selon des critères tels que l'espace de noms de la ressource, les étiquettes, le groupe, la version et le type.

. Sélectionnez *Enregistrer* pour enregistrer chaque règle.
. Lorsque vous avez ajouté toutes les règles dont vous avez besoin, sélectionnez *Rechercher* pour voir les ressources disponibles dans l'archive de sauvegarde qui correspondent à vos critères de filtre.
+

NOTE: Les ressources affichées sont les ressources qui existent actuellement sur le cluster.

. Lorsque vous êtes satisfait des résultats, sélectionnez *Suivant*.


--
====
[discrete]
===== Paramètres de destination

. Développez la section *Paramètres de destination* et choisissez de restaurer soit vers la classe de stockage par défaut, une autre classe de stockage, ou, si vous restaurez vers un autre cluster, de mapper les classes de stockage au cluster de destination.
. Si vous avez choisi de restaurer vers une classe de stockage différente, sélectionnez une classe de stockage de destination correspondant à chaque classe de stockage source.
. Optionnellement, si vous restaurez une sauvegarde ou un instantané créé avec Trident Protect, consultez les détails du AppVault utilisé comme compartiment de stockage pour l'opération de restauration. S'il y a un changement dans votre environnement ou dans le statut du AppVault, sélectionnez *Sync App Vault* pour actualiser les détails.
+

NOTE: Si vous devez créer un AppVault sur un cluster Kubernetes pour faciliter la restauration d'une sauvegarde ou d'un instantané créé à l'aide de Trident Protect, reportez-vous à  https://docs.netapp.com/us-en/trident/trident-protect/trident-protect-appvault-custom-resources.html["Utilisez les objets Trident Protect AppVault pour gérer les compartiments"].

. Vous pouvez également développer la section *Scripts de restauration* et activer l'option *Postscript* pour choisir un modèle de hook d'exécution qui s'exécutera une fois l'opération de restauration terminée. Si nécessaire, saisissez les arguments requis par le script et ajoutez des sélecteurs d'étiquettes pour filtrer les ressources en fonction des étiquettes de ressource.
. Sélectionnez *Restaurer*.

