---
sidebar: sidebar 
permalink: br-use-hyperv-restore.html 
keywords: restore, vm, virtual machine, snapshots, object storage, cloud storage, backing up, back up, backup, Amazon Web services, AWS, NetApp Backup and Recovery 
summary: Protégez vos charges de travail Hyper-V avec NetApp Backup and Recovery. 
---
= Restaurer les charges de travail Hyper-V avec NetApp Backup and Recovery
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Restaurez les charges de travail Hyper-V à partir d'instantanés, d'une sauvegarde de charge de travail répliquée sur un stockage secondaire ou de sauvegardes stockées dans un stockage objet à l'aide de NetApp Backup and Recovery.

.Restaurer à partir de ces emplacements
Vous pouvez restaurer des charges de travail à partir de différents emplacements de départ :

* Restaurer à partir d'un emplacement principal (instantané local)
* Restaurer à partir d'une ressource répliquée sur un stockage secondaire
* Restaurer à partir d'une sauvegarde de stockage d'objets


.Restaurer ces points
Vous pouvez restaurer les données à ces points :

* Restaurer à l'emplacement d'origine
* Restaurer à un autre emplacement


.Considérations relatives à la restauration à partir du stockage d'objets
Si vous sélectionnez un fichier de sauvegarde dans le stockage d'objets et que la protection contre les ransomwares est active pour cette sauvegarde (si vous avez activé DataLock et Ransomware Resilience dans la stratégie de sauvegarde), vous êtes invité à exécuter une vérification d'intégrité supplémentaire sur le fichier de sauvegarde avant de restaurer les données.  Nous vous recommandons d'effectuer l'analyse.


TIP: Des frais de sortie supplémentaires seront facturés par votre fournisseur de cloud pour accéder au contenu du fichier de sauvegarde.



== Comment fonctionne la restauration des charges de travail

Lorsque vous restaurez des charges de travail, les événements suivants se produisent :

* Lorsque vous restaurez une charge de travail à partir d'un fichier de sauvegarde local, NetApp Backup and Recovery crée une _nouvelle_ ressource à l'aide des données de la sauvegarde.
* Lorsque vous effectuez une restauration à partir d’une charge de travail répliquée, vous pouvez restaurer la charge de travail sur le système d’origine ou sur un système ONTAP local.


À partir de la page Restaurer (également appelée Rechercher et restaurer), vous pouvez restaurer une ressource, même si vous ne vous souvenez pas du nom exact, de l'emplacement où elle réside ou de la date à laquelle elle était en bon état pour la dernière fois. Vous pouvez rechercher l'instantané à l'aide de filtres.



== Restaurer les données de charge de travail à partir de l'option Restaurer (Rechercher et restaurer)

Restaurez les charges de travail Hyper-V à l’aide de l’option Restaurer. Vous pouvez rechercher l'instantané par son nom ou en utilisant des filtres.

*Rôle de console requis* Rôle de super administrateur de sauvegarde et de récupération ou d'administrateur de restauration de sauvegarde et de récupération. https://docs.netapp.com/us-en/console-setup-admin/reference-iam-predefined-roles.html["En savoir plus sur les rôles d'accès à la NetApp Console pour tous les services"^] .

.Étapes
. Dans le menu NetApp Backup and Recovery , sélectionnez *Restaurer*.
. Dans la liste déroulante à droite du champ de recherche de nom, sélectionnez *Hyper-V*.
. Saisissez le nom de la ressource que vous souhaitez restaurer ou filtrez le nom de la machine virtuelle, l’hôte de la machine virtuelle ou le pool de stockage où se trouve la ressource que vous souhaitez restaurer.
+
Une liste d'instantanés correspondant à vos critères de recherche apparaît.

. Sélectionnez le bouton *Restaurer* pour l’instantané que vous souhaitez restaurer.
+
Une liste de points de restauration possibles apparaît.

. Sélectionnez le point de restauration que vous souhaitez utiliser.
. Sélectionnez un emplacement source d’instantané.
. Sélectionnez *Suivant* pour continuer.
. Choisissez la destination et les paramètres de restauration :


[discrete]
===== Sélection de la destination

[role="tabbed-block"]
====
.Restaurer à l'emplacement d'origine
--
Lorsque vous restaurez l'emplacement d'origine, vous pouvez consulter les paramètres de destination en développant la section *Paramètres de destination*, mais vous ne pouvez pas les modifier.

. Dans la section *Options post-restauration*, considérez l'option suivante :
+
** *Démarrer la machine virtuelle* : Activez cette option pour démarrer la nouvelle machine virtuelle après sa restauration.


. Sélectionnez *Restaurer*.


--
.Restaurer vers un autre emplacement
--
. Dans la section *Paramètres de destination*, saisissez les informations suivantes :
+
** *Nom de domaine complet ou adresse IP Hyper-V* : Saisissez le nom de domaine complet ou l’adresse IP de l’hôte Hyper-V de destination.
** *Réseau* : Sélectionnez le réseau de destination sur lequel vous souhaitez restaurer l’instantané.
** *Nom de la machine virtuelle* : Saisissez le nom de la machine virtuelle que vous souhaitez restaurer.
** *Emplacement de destination* : Saisissez le dossier de destination ou le partage CIFS qui doit contenir les données restaurées.


. Dans la section *Options de pré-restauration*, considérez les options suivantes :
+
** *Restauration rapide* : Activez cette option pour rendre la machine virtuelle restaurée immédiatement disponible. Seuls les fichiers nécessaires au fonctionnement de la machine virtuelle sont restaurés à partir du stockage d'objets, et non la totalité du volume.


. Dans la section *Options après restauration*, considérez les options suivantes :
+
** *Démarrer la machine virtuelle* : Activez cette option pour démarrer la nouvelle machine virtuelle après sa restauration.


. Sélectionnez *Restaurer*.


--
====