---
sidebar: sidebar 
permalink: br-use-reports.html 
keywords: backing up, back up, backup, backup on-prem ontap, policy, policies, backup policies, cloud backup, aws, aws s3, azure, google cloud 
summary: 'Dans NetApp Backup and Recovery, créez des rapports pour afficher l"état de vos sauvegardes, y compris le nombre de sauvegardes, le nombre de sauvegardes réussies et le nombre de sauvegardes ayant échoué.  Vous pouvez également afficher les détails de chaque sauvegarde, y compris le type de sauvegarde, le système de stockage utilisé pour la sauvegarde et l"heure de la sauvegarde.' 
---
= Créez des rapports de protection Microsoft SQL Server dans NetApp Backup and Recovery
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Créez des rapports pour les charges de travail Microsoft SQL Server dans NetApp Backup and Recovery afin d’examiner l’état et les détails des sauvegardes, notamment le nombre de sauvegardes réussies et échouées, les types de sauvegarde, les systèmes de stockage et les horodatages.



[[create-a-protection-report]]
== Créer un rapport de protection

*Rôle requis dans la NetApp Console* visionneuse de stockage, super administrateur de sauvegarde et de restauration, administrateur de sauvegarde et de restauration, administrateur de restauration, administrateur de clonage. Si vous protégez des données stockées sur un cluster Cloud Volumes ONTAP, le rôle d’administrateur Cloud Volumes ONTAP est également requis. En savoir plus link:reference-roles.html["Rôles et privilèges de sauvegarde et de récupération"]. https://docs.netapp.com/us-en/console-setup-admin/reference-iam-predefined-roles.html["En savoir plus sur les rôles d'accès à la NetApp Console pour tous les services"^].

.Étapes
. Dans le menu NetApp Backup and Recovery, sélectionnez *Rapports*.
. Sélectionnez *Créer un rapport*.
. Saisissez les détails de la portée du rapport :
+
** *Nom du rapport* : saisissez un nom unique pour le rapport.
** *Type de rapport* : Choisissez si vous souhaitez un rapport par compte ou par charge de travail (Microsoft SQL Server).
** *Sélectionner l'hôte* : si vous avez sélectionné par charge de travail, sélectionnez l'hôte pour lequel vous souhaitez générer le rapport.
** *Sélectionner le contenu* : Choisissez si vous souhaitez que le rapport inclue un résumé de toutes les sauvegardes ou les détails de chaque sauvegarde.  (Si vous avez choisi « Par compte »)


. Saisissez la période concernée : choisissez si vous souhaitez que le rapport inclue les données du dernier jour, des 7 derniers jours, des 30 derniers jours, du dernier trimestre ou de la dernière année.
. Saisissez les informations de livraison du rapport : si vous souhaitez que le rapport soit envoyé par e-mail, sélectionnez *Envoyer le rapport par e-mail*. Saisissez l’adresse e-mail à laquelle vous souhaitez que le rapport soit envoyé.
+
Configurez les notifications par e-mail sur la page Paramètres. Pour plus d'informations sur la configuration des notifications par e-mail, consultez link:br-start-configure.html["Configurer les paramètres"].


