---
sidebar: sidebar 
permalink: br-use-oracle-protect-overview.html 
keywords: backing up, restoring, back up, backup, restore, cloud volumes ontap, aws, azure, s3, blob, google cloud, storagegrid, back up volumes, cloud backup, restore volumes, cost, on-premises ontap, onprem, applications, virtual machines, backup and recovery 
summary: Vous pouvez protéger les machines virtuelles Oracle des systèmes ONTAP sur site vers Amazon Web Services, Microsoft Azure, Google Cloud Platform et StorageGRID, garantissant ainsi la protection de vos données. 
---
= Protégez les charges de travail de base de données Oracle avec NetApp Backup and Recovery
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Utilisez NetApp Backup and Recovery pour protéger les charges de travail et journaux Oracle Database avec des sauvegardes et restaurations rapides, économes en espace, cohérentes après panne et cohérentes au niveau de la base de données. Vous pouvez sauvegarder les charges de travail sur AWS S3, StorageGRID, Azure Blob ou ONTAP S3 et restaurer les sauvegardes sur un hôte Oracle local.

Utilisez NetApp Backup and Recovery pour mettre en œuvre une stratégie de protection 3-2-1, où vous disposez de 3 copies de vos données sources sur 2 systèmes de stockage différents ainsi que d'une copie dans le cloud. Les avantages de l’approche 3-2-1 incluent :

* Plusieurs copies de données protègent contre les menaces de cybersécurité internes et externes.
* L’utilisation de différents types de supports vous aide à récupérer si l’un d’eux tombe en panne.
* Vous pouvez restaurer rapidement à partir de la copie sur site et utiliser les copies hors site si la copie sur site est compromise.


Vous pouvez utiliser NetApp Backup and Recovery pour effectuer les tâches suivantes liées aux charges de travail d'Oracle Database :

* link:br-start-discover-oracle.html["Découvrez les charges de travail Oracle Database"]
* link:br-use-oracle-protection-groups.html["Gérer les groupes de protection pour les charges de travail Oracle Database"]
* link:br-use-oracle-backup.html["Sauvegardez les charges de travail Oracle Database"]
* link:br-use-oracle-clone.html["Cloner les charges de travail de base de données Oracle"]
* link:br-use-oracle-restore.html["Restaurer les charges de travail Oracle Database"]

