---
sidebar: sidebar 
permalink: br-use-settings-advanced.html 
keywords: backing up, restoring, back up, backup, restore, cloud volumes ontap, aws, azure, s3, blob, google cloud, storagegrid, back up volumes, cloud backup, restore volumes, cost, on-premises ontap, onprem, applications, virtual machines, backup and recovery 
summary: 'Certains paramètres avancés peuvent être utiles pour maintenir votre environnement de sauvegarde et de récupération.  Vous pouvez configurer des paramètres avancés pour gérer votre inventaire, supprimer des sauvegardes, désenregistrer des ressources, supprimer des relations, déprotéger des ressources pour arrêter les frais de service, définir le taux de transfert maximal pour la relation SnapMirror , exporter des copies d"instantanés vers un magasin d"objets, activer la suppression automatique annuelle des instantanés, activer le mode de maintenance et mettre à jour le plug-in d"application.' 
---
= Configurer les paramètres avancés dans NetApp Backup and Recovery
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Certains paramètres avancés peuvent être utiles pour maintenir votre environnement de sauvegarde et de récupération.  Vous pouvez configurer des paramètres avancés pour gérer votre inventaire, supprimer des sauvegardes, désenregistrer des ressources, supprimer des relations, déprotéger des ressources pour arrêter les frais de service, définir le taux de transfert maximal pour la relation SnapMirror , exporter des copies d'instantanés vers un magasin d'objets, activer la suppression automatique annuelle des instantanés, activer le mode de maintenance et mettre à jour le plug-in d'application.

Configurez les paramètres avancés de NetApp Backup and Recovery des manières suivantes :

* Supprimer les sauvegardes.
* Annuler l'enregistrement des sauvegardes, des bases de données, des instances ou des hôtes d'application.
* Supprimer les relations.
* Déprotégez les bases de données, les instances, les hôtes d’application et les environnements de travail pour arrêter les frais de service.
* Définissez le taux de transfert maximal pour la relation SnapMirror : gérez l'utilisation de la bande passante, en vous assurant que les opérations SnapMirror n'interfèrent pas avec d'autres activités réseau.
* Exportez des copies instantanées vers un magasin d'objets pour initialiser les sauvegardes dans le cloud en déplaçant les anciennes copies instantanées vers la copie de sauvegarde de base.
* Activer la suppression automatique annuelle des instantanés
* Activez le mode maintenance pour que les mises à jour ou les tâches de maintenance puissent être effectuées.
* Mettre à jour le plugin d'application.




== Supprimer les sauvegardes

Vous pouvez supprimer des sauvegardes pour libérer de l'espace dans votre stockage.

. Dans la console NetApp Backup and Recovery , sélectionnez **Paramètres**.
. Sélectionnez **Paramètres avancés**.
. Sélectionnez **Supprimer les sauvegardes**.
. Sélectionnez la sauvegarde que vous souhaitez supprimer.
. Sélectionnez **Supprimer**.




== Annuler l'enregistrement des sauvegardes, des bases de données, des instances ou des hôtes d'application

Vous pouvez désinscrire des sauvegardes, des bases de données, des instances ou des hôtes d'application pour les supprimer de l'inventaire.

. Dans la console NetApp Backup and Recovery , sélectionnez **Paramètres**.
. Sélectionnez **Paramètres avancés**.
. Sélectionnez **Désinscrire les ressources**.
. Sélectionnez la ressource dont vous souhaitez annuler l’enregistrement.
. Sélectionnez **Désinscrire**.




== Supprimer les relations

Vous pouvez supprimer des relations pour les retirer de l'inventaire.

. Dans la console NetApp Backup and Recovery , sélectionnez **Paramètres**.
. Sélectionnez **Paramètres avancés**.
. Sélectionnez **Supprimer les relations**.
. Sélectionnez la relation que vous souhaitez supprimer.
. Sélectionnez **Supprimer**.




== Déprotégez les bases de données, les instances, les hôtes d'application et les environnements de travail

Vous pouvez déprotéger les bases de données, les instances, les hôtes d'application et les environnements de travail pour arrêter les frais de service.

. Dans la console NetApp Backup and Recovery , sélectionnez **Paramètres**.
. Sélectionnez **Paramètres avancés**.
. Sélectionnez **Déprotéger les ressources**.




== Définir le taux de transfert maximal pour la relation SnapMirror

Vous pouvez définir le taux de transfert maximal pour la relation SnapMirror afin de gérer l'utilisation de la bande passante, garantissant ainsi que les opérations SnapMirror n'interfèrent pas avec d'autres activités réseau.

. Dans la console NetApp Backup and Recovery , sélectionnez **Paramètres**.
. Sélectionnez **Paramètres avancés**.
. Sélectionnez **Définir le taux de transfert maximal pour la relation SnapMirror **.
. Entrez le taux de transfert maximal.
. Sélectionnez **Enregistrer**.




== Exporter des copies instantanées vers un magasin d'objets

Vous pouvez exporter des copies instantanées vers un magasin d'objets pour initialiser les sauvegardes dans le cloud en déplaçant les anciennes copies instantanées vers la copie de sauvegarde de base.

. Dans la console NetApp Backup and Recovery , sélectionnez **Paramètres**.
. Sélectionnez **Paramètres avancés**.
. Sélectionnez **Exporter des copies instantanées vers un magasin d'objets**.
. Sélectionnez la copie instantanée que vous souhaitez exporter.
. Sélectionnez **Exporter**.




== Activer la suppression automatique annuelle des instantanés

Vous pouvez activer la suppression automatique des instantanés annuels pour supprimer les instantanés datant de plus d'un an.

. Dans la console NetApp Backup and Recovery , sélectionnez **Paramètres**.
. Sélectionnez **Paramètres avancés**.
. Sélectionnez **Activer la suppression automatique des instantanés annuels**.
. Sélectionnez **Activer**.




== Activer le mode maintenance

Vous pouvez activer le mode maintenance afin que les mises à jour ou les tâches de maintenance puissent être effectuées.

. Dans la console NetApp Backup and Recovery , sélectionnez **Paramètres**.
. Sélectionnez **Paramètres avancés**.
. Sélectionnez **Activer le mode maintenance**.
. Sélectionnez **Activer**.




== Mettre à jour le plugin d'application

Vous pouvez mettre à jour le plugin d'application pour vous assurer que les dernières fonctionnalités sont disponibles.

. Dans la console NetApp Backup and Recovery , sélectionnez **Paramètres**.
. Sélectionnez **Paramètres avancés**.
. Sélectionnez **Mettre à jour le plug-in d’application**.
. Sélectionnez **Mettre à jour**.

