---
sidebar: sidebar 
permalink: br-use-back-up-now-kubernetes-applications-web-ui.html 
keywords: backing up, restoring, back up, backup, restore, cloud volumes ontap, aws, azure, s3, blob, google cloud, storagegrid, back up volumes, cloud backup, restore volumes, cost, on-premises ontap, onprem, applications, virtual machines, backup and recovery, snapcenter 
summary: 'Créez manuellement des sauvegardes à la demande d"applications Kubernetes à l"aide de l"interface web NetApp Backup and Recovery.' 
---
= Sauvegardez une application Kubernetes à l'aide de l'interface web NetApp Backup and Recovery
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Utilisez l'interface web pour effectuer une sauvegarde à la demande d'une application Kubernetes.

*Rôle de NetApp Console requis*

Super administrateur NetApp Backup and Recovery ou administrateur de sauvegarde NetApp Backup and Recovery. link:reference-roles.html["En savoir plus sur les rôles d'accès à NetApp Backup and Recovery"]. https://docs.netapp.com/us-en/console-setup-admin/reference-iam-predefined-roles.html["En savoir plus sur les rôles d'accès à la NetApp Console pour tous les services"^].



[[back-up-a-kubernetes-application]]
== Sauvegardez une application Kubernetes

Créez manuellement une sauvegarde d'une application Kubernetes pour établir une base de référence pour les futures sauvegardes et instantanés, ou pour garantir la protection des données les plus récentes.

.Étapes
. Dans NetApp Backup and Recovery, sélectionnez *Inventaire*.
. Choisissez une instance Kubernetes et sélectionnez *Afficher* pour accéder aux ressources associées à cette instance.
. Sélectionnez l'onglet *Applications*.
. Dans la liste des applications, sélectionnez une application que vous souhaitez sauvegarder et choisissez le menu Actions associé.
. Sélectionnez *Sauvegarder maintenant*.
. Confirmez que la bonne application est sélectionnée.
. Sélectionnez *Sauvegarder*.


.Résultat
La console crée une sauvegarde de l'application et affiche la progression dans la zone *Surveillance* de Sauvegarde et récupération. La sauvegarde est créée en fonction de la politique de protection associée à l'application.
