---
sidebar: sidebar 
permalink: br-use-oracle-protect-overview.html 
keywords: backing up, restoring, back up, backup, restore, cloud volumes ontap, aws, azure, s3, blob, google cloud, storagegrid, back up volumes, cloud backup, restore volumes, cost, on-premises ontap, onprem, applications, virtual machines, backup and recovery 
summary: Vous pouvez protéger les machines virtuelles Oracle des systèmes ONTAP sur site vers Amazon Web Services, Microsoft Azure, Google Cloud Platform et StorageGRID, garantissant ainsi la protection de vos données. 
---
= Présentation de la protection des charges de travail de la base de données Oracle
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Protégez les bases de données et les journaux Oracle à l’aide de NetApp Backup and Recovery.  Obtenez des sauvegardes et des restaurations rapides, peu encombrantes, cohérentes en cas de panne et cohérentes avec la base de données.  Sauvegardez les charges de travail Oracle sur AWS S3, NetApp StorageGRID, Azure Blob Storage ou ONTAP S3.  Restaurer les sauvegardes sur un hôte Oracle sur site.

Utilisez NetApp Backup and Recovery pour mettre en œuvre une stratégie de protection 3-2-1, où vous disposez de 3 copies de vos données sources sur 2 systèmes de stockage différents ainsi que d'une copie dans le cloud. Les avantages de l’approche 3-2-1 incluent :

* Plusieurs copies de données protègent contre les menaces de cybersécurité internes et externes.
* L’utilisation de différents types de supports vous aide à récupérer si l’un d’eux tombe en panne.
* Vous pouvez restaurer rapidement à partir de la copie sur site et utiliser les copies hors site si la copie sur site est compromise.



NOTE: Pour basculer vers et depuis les versions de l'interface utilisateur NetApp Backup and Recovery , reportez-vous àlink:br-start-switch-ui.html["Passer à l'interface utilisateur précédente de NetApp Backup and Recovery"] .

Vous pouvez utiliser NetApp Backup and Recovery pour effectuer les tâches suivantes liées aux charges de travail Oracle :

* link:br-start-discover-oracle.html["Découvrez les charges de travail Oracle"]
* link:br-use-oracle-protection-groups.html["Créer et gérer des groupes de protection pour les charges de travail Oracle"]
* link:br-use-oracle-backup.html["Sauvegarder les charges de travail Oracle"]
* link:br-use-oracle-restore.html["Restaurer les charges de travail Oracle"]

