---
sidebar: sidebar 
permalink: br-use-mssql-protect-overview.html 
keywords: backing up, restoring, back up, backup, restore, cloud volumes ontap, aws, azure, s3, blob, google cloud, storagegrid, back up volumes, cloud backup, restore volumes, cost, on-premises ontap, onprem, applications, virtual machines, backup and recovery 
summary: 'Vous pouvez sauvegarder les données des applications Microsoft SQL Server à partir de systèmes ONTAP locaux vers Amazon Web Services, Microsoft Azure et StorageGRID, garantissant ainsi la protection de vos données. Les sauvegardes sont automatiquement générées et stockées dans un magasin d’objets sur votre compte cloud public ou privé.  Vous pouvez mettre en œuvre une stratégie 3-2-1, où vous disposez de 3 copies de vos données sources sur 2 systèmes de stockage différents ainsi que d"une copie dans le cloud.' 
---
= Présentation de la protection des charges de travail Microsoft SQL avec NetApp Backup and Recovery
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Protégez les données de vos applications Microsoft SQL Server depuis les systèmes ONTAP locaux vers Amazon Web Services, Microsoft Azure ou StorageGRID à l'aide de NetApp Backup and Recovery. Les sauvegardes sont automatiquement générées et stockées dans un magasin d’objets de votre compte cloud public ou privé en fonction des politiques que vous créez.  Vous pouvez mettre en œuvre une stratégie 3-2-1, où vous disposez de 3 copies de vos données sources sur 2 systèmes de stockage différents ainsi que d'une copie dans le cloud.

Les avantages de l’approche 3-2-1 incluent :

* Plusieurs copies de données offrent une protection multicouche contre les menaces de cybersécurité internes (initiées) et externes.
* Plusieurs types de supports garantissent la viabilité du basculement en cas de défaillance physique ou logique d'un type de support.
* La copie sur site facilite les restaurations rapides, les copies hors site étant disponibles au cas où la copie sur site serait compromise.


NetApp Backup and Recovery exploite la technologie de réplication de données NetApp SnapMirror pour garantir que toutes les sauvegardes sont entièrement synchronisées en créant des copies instantanées et en les transférant vers les emplacements de sauvegarde.

Vous pouvez atteindre les objectifs de protection suivants :

* link:concept-start-prereq-snapcenter-import.html["Configurer des éléments supplémentaires en cas d'importation depuis SnapCenter"]
* link:br-start-discover.html["Découvrez les charges de travail Microsoft SQL Server et importez éventuellement des ressources SnapCenter"]
* link:br-use-mssql-backup.html["Sauvegardez les charges de travail avec des snapshots locaux sur le stockage principal ONTAP local"]
* link:br-use-mssql-backup.html["Répliquer les charges de travail vers le stockage secondaire ONTAP"]
* link:br-use-mssql-backup.html["Sauvegarder les charges de travail vers un emplacement de stockage d'objets"]
* link:br-use-mssql-backup.html["Sauvegardez les charges de travail maintenant"]
* link:br-use-mssql-restore-overview.html["Restaurer les charges de travail"]
* link:br-use-mssql-clone.html["Cloner les charges de travail"]
* link:br-use-manage-inventory.html["Gérer l'inventaire des charges de travail"]
* link:br-use-manage-snapshots.html["Gérer les instantanés"]


Pour sauvegarder les charges de travail, vous créez généralement des politiques qui régissent les opérations de sauvegarde et de restauration.  Voirlink:br-use-policies-create.html["Créer des politiques"] pour plus d'informations.

.Destinations de sauvegarde prises en charge
NetApp Backup and Recovery vous permet de sauvegarder des instances et des bases de données Microsoft SQL Server à partir des systèmes sources suivants vers les systèmes secondaires suivants et le stockage d'objets dans les fournisseurs de cloud public et privé.  Les copies instantanées résident sur le système source.

[cols="33,33,33"]
|===
| Système source | Système secondaire (réplication) | Magasin d'objets de destination (sauvegarde) 


| Cloud Volumes ONTAP dans AWS | Cloud Volumes ONTAP dans le système ONTAP sur site AWS | Amazon S3 ONTAP S3 


| Cloud Volumes ONTAP dans Azure | Cloud Volumes ONTAP dans le système ONTAP sur site Azure | Azure Blob ONTAP S3 


| Système ONTAP sur site | Cloud Volumes ONTAP Système ONTAP sur site | Amazon S3 Azure Blob NetApp StorageGRID ONTAP S3 


| Amazon FSx for NetApp ONTAP | Amazon FSx for NetApp ONTAP | NA ifdef::gcp[] endif::gcp[] ifdef::gcp[] endif::gcp[] 
|===
.Destinations de restauration prises en charge
Vous pouvez restaurer des instances et des bases de données Microsoft SQL Server à partir d’une sauvegarde qui réside dans le stockage principal ou un système secondaire (un volume répliqué) ou dans le stockage d’objets (un fichier de sauvegarde) sur les systèmes suivants.  Les copies instantanées résident sur le système source et ne peuvent être restaurées que sur ce même système.

[cols="33,33,33"]
|===
2+| À partir de l'emplacement du fichier de sauvegarde | Vers le système de destination 


| *Magasin d'objets (sauvegarde)* | *Système secondaire (réplication)* |  


| Amazon S3 | Cloud Volumes ONTAP dans le système ONTAP sur site AWS | Volumes cloud dans le système ONTAP sur site AWS ONTAP S3 


| Azure Blob | Cloud Volumes ONTAP dans le système ONTAP sur site Azure | Cloud Volumes ONTAP dans Azure Système ONTAP sur site ONTAP S3 ifdef::gcp[] endif::gcp[] 


| StorageGRID | Cloud Volumes ONTAP Système ONTAP sur site | Système ONTAP sur site ONTAP S3 


| Amazon FSx for NetApp ONTAP | Amazon FSx for NetApp ONTAP | N / A 
|===

NOTE: Les références aux « systèmes ONTAP sur site » incluent les systèmes FAS et AFF .
