---
sidebar: sidebar 
permalink: br-use-mssql-restore-overview.html 
keywords: backing up, restoring, back up, backup, restore, cloud volumes ontap, aws, azure, s3, blob, google cloud, storagegrid, back up volumes, cloud backup, restore volumes, cost, on-premises ontap, onprem, applications, virtual machines, backup and recovery 
summary: 'Les sauvegardes de vos données sont disponibles pour la restauration à partir des emplacements où vous avez créé des sauvegardes, ce qui inclut les instantanés, les réplications et les sauvegardes dans le stockage d"objets.  Passez en revue les emplacements de restauration, les points de restauration et les types de ressources à restaurer.' 
---
= Restaurer la vue d'ensemble des charges de travail Microsoft SQL à l'aide de NetApp Backup and Recovery
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Les sauvegardes de vos données Microsoft SQL Server à partir de NetApp Backup and Recovery sont disponibles pour la restauration à partir des emplacements où vous avez déplacé les sauvegardes : snapshots, réplications ou sauvegardes dans le stockage d'objets.  Vous pouvez restaurer une charge de travail sur le système d'origine, sur un autre système utilisant le même compte cloud ou sur un système ONTAP sur site.  Passez en revue les emplacements de restauration, les points de restauration et les types de ressources à restaurer.

.Restaurer à partir de ces emplacements
Vous pouvez restaurer des charges de travail à partir de différents emplacements de départ :

* Restaurer à partir d'un emplacement principal
* Restaurer à partir d'une ressource répliquée
* Restaurer à partir d'une sauvegarde de magasin d'objets


.Restaurer ces points
Vous pouvez restaurer les données vers le dernier instantané ou vers ces points :

* Restaurer à partir d'instantanés
* Restaurer à un moment précis dans le temps.  Cela est utile si vous connaissez le nom et l'emplacement du fichier, ainsi que la date à laquelle il a été conservé en bon état pour la dernière fois.
* Restaurer la dernière sauvegarde




== Quelle est la prochaine étape

Pour plus de détails sur la façon de restaurer les charges de travail, voirlink:br-use-mssql-restore.html["Restaurer les charges de travail"] .
