---
sidebar: sidebar 
permalink: concept-start-prereq.html 
keywords: backing up, restoring, back up, backup, restore, cloud volumes ontap, aws, azure, s3, blob, google cloud, storagegrid, back up volumes, cloud backup, restore volumes, cost, on-premises ontap, onprem, applications, backup and recovery 
summary: Commencez à utiliser NetApp Backup and Recovery en vérifiant l’état de préparation de votre environnement opérationnel, de l’agent de console et du compte de console.  Pour utiliser NetApp Backup and Recovery, vous aurez besoin de ces prérequis. 
---
= NetApp Backup and Recovery exigences
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Avant de commencer à utiliser NetApp Backup and Recovery, assurez-vous que votre NetApp Console et votre environnement opérationnel répondent aux exigences suivantes.



[[prepare-netapp-console]]
== Préparer la NetApp Console

Vous accédez à NetApp Backup and Recovery via NetApp Console. Pour préparer la Console pour Backup and Recovery, vous devez :

* Ajouter un agent de console
* Ajoutez au moins un système de stockage
* Configurer une organisation Console et des rôles d'utilisateur


Vous devez disposer du rôle d'administrateur de l'organisation ou de super administrateur dans la NetApp Console pour effectuer cette préparation.

Pour en savoir plus sur NetApp Console, consultez https://docs.netapp.com/us-en/console-setup-admin/concept-overview.html["NetApp Console pour la gestion unifiée du stockage"^].



[[complete-initial-netapp-console-setup]]
=== Effectuez la configuration initiale complète de la NetApp Console

Terminez la configuration initiale de la NetApp Console si vous ne l'avez pas déjà fait.

https://docs.netapp.com/us-en/console-setup-admin/task-quick-start-standard-mode.html["Processus de démarrage pour NetApp Console (application SaaS)"^]



[[deploy-a-console-agent]]
=== Déployer un agent de console

Un agent Console est un composant logiciel léger que vous installez sur votre réseau pour connecter votre infrastructure de stockage à NetApp Console. Il permet une orchestration avancée du stockage, des services de données et une intégration au cloud sécurisée.

https://docs.netapp.com/us-en/console-setup-admin/concept-agents.html["En savoir plus sur les agents de console"^] https://docs.netapp.com/us-en/console-setup-admin/concept-agent-install-options.html["Déployer un agent de console"^]



[[add-a-storage-system]]
=== Ajouter un système de stockage

Avant de pouvoir protéger les charges de travail dans NetApp Backup and Recovery, vous devez ajouter un système de stockage ONTAP à la NetApp Console.

https://docs.netapp.com/us-en/storage-management-ontap-onprem/task-discovering-ontap.html["Découvrez les clusters ONTAP locaux dans la NetApp Console"^]



[[configure-an-organization-and-user-roles]]
=== Configurer une organisation et des rôles d'utilisateur

Découvrez les organisations, les projets et les rôles des utilisateurs, puis configurez les utilisateurs avec les autorisations appropriées nécessaires à l'exécution de leurs tâches.

Reportez-vous à  https://docs.netapp.com/us-en/console-setup-admin/task-iam-manage-members-permissions.html["Ajouter des utilisateurs à une organisation NetApp Console"] pour obtenir des informations sur l'utilisation d'une organisation et de projets pour contrôler l'accès aux ressources.

Reportez-vous à  https://docs.netapp.com/us-en/console-setup-admin/reference-iam-backup-rec-roles.html["Rôles de NetApp Backup and Recovery dans la NetApp Console"] pour obtenir des détails sur les rôles et les autorisations nécessaires pour effectuer des opérations dans NetApp Backup and Recovery.



[[requirements-for-backups-to-object-storage]]
== Exigences relatives aux sauvegardes sur stockage objet

Pour utiliser le stockage d'objets comme cibles de sauvegarde, vous avez besoin d'un compte AWS S3, Google Cloud Storage, Microsoft Azure Blob, StorageGRID ou ONTAP et des autorisations d'accès appropriées configurées.



[[requirements-for-protecting-ontap-volume-workloads]]
== Exigences relatives à la protection des charges de travail de volume ONTAP

Pour utiliser NetApp Backup and Recovery pour les charges de travail de volume ONTAP, vous devez respecter les prérequis suivants en matière de système hôte, d'espace et de dimensionnement.

* ONTAP 9.8 ou une version ultérieure est requise.
* ONTAP 9.12.1 ou une version ultérieure est requise pour la protection des volumes FlexGroup. Consultez link:br-reference-limitations.html["Limitations connues avec NetApp Backup and Recovery pour les volumes ONTAP"] pour plus d'informations.
* ONTAP 9.17.1 ou une version ultérieure est requise pour la sauvegarde ou la restauration sur un stockage d'objets compatible S3.
* ONTAP 9.19.1 ou une version ultérieure est nécessaire pour prendre en charge plus de 6 compartiments par système sur différents fournisseurs de cloud (jusqu'à 100 compartiments maximum).
* Une licence ONTAP One doit être activée sur l'instance ONTAP locale.


Pour plus d'informations sur les fonctionnalités prises en charge, les types de volumes, les destinations de sauvegarde et de restauration, et plus encore, consultez link:prev-ontap-protect-overview.html["Protégez vos données de volume ONTAP"].



[[requirements-for-protecting-microsoft-sql-server-workloads]]
== Exigences pour la protection des charges de travail Microsoft SQL Server

Pour utiliser NetApp Backup and Recovery pour les charges de travail Microsoft SQL Server, vous avez besoin des prérequis suivants en matière de système hôte, d’espace et de dimensionnement.


NOTE: ONTAP 9.19.1 ou une version ultérieure est nécessaire pour prendre en charge plus de 6 compartiments par système sur différents fournisseurs de cloud (jusqu'à 100 compartiments maximum).

[cols="33,66a"]
|===
| Article | Exigences 


| Systèmes d'exploitation  a| 
Microsoft Windows Pour obtenir les dernières informations sur les versions prises en charge, consultez le https://imt.netapp.com/matrix/imt.jsp?components=121074;&solution=1257&isHWU&src=IMT#welcome["Outil de matrice d'interopérabilité NetApp"^] .



| Versions de Microsoft SQL Server  a| 
Les versions 2012 et ultérieures sont prises en charge pour VMware Virtual Machine File System (VMFS) et VMware Virtual Machine Disk (VMDK) NFS.



| Version du serveur SnapCenter  a| 
La version 5.0 ou supérieure de SnapCenter Server est requise si vous souhaitez importer vos données existantes de SnapCenter dans NetApp Backup and Recovery.


NOTE: Si vous disposez déjà de SnapCenter, vérifiez d'abord que vous avez rempli les conditions préalables avant d'importer depuis SnapCenter.  Voirlink:concept-start-prereq-snapcenter-import.html["Conditions préalables à l'importation de ressources depuis SnapCenter"] .



| RAM minimale pour le plug-in sur l'hôte SQL Server  a| 
1 Go



| Espace minimum d'installation et de journalisation pour le plug-in sur l'hôte SQL Server  a| 
5 Go

Allouez suffisamment d’espace disque et surveillez la consommation de stockage par le dossier des journaux.  L'espace journal requis varie en fonction du nombre de sauvegardes effectuées et de la fréquence des opérations de protection des données.  S'il n'y a pas suffisamment d'espace, les journaux ne seront pas créés pour les opérations.



| Logiciels requis  a| 
* ASP.NET Core Runtime 8.0.24 Hosting Bundle (et tous les correctifs 8.0.x ultérieurs)
* PowerShell 7.4.13


Pour obtenir les dernières informations sur les versions prises en charge, consultez le https://imt.netapp.com/matrix/imt.jsp?components=121074;&solution=1257&isHWU&src=IMT#welcome["Outil de matrice d'interopérabilité NetApp"^] .

|===
[cols="33,66a"]
|===
| Hôte de base de données | Stockage pris en charge 


| Serveur physique  a| 
* LUNs présentés via Fibre Channel
* LUNs présentés via iSCSI




| VMware VM  a| 
* LUN iSCSI connectés directement au système invité par l’initiateur iSCSI
* Systèmes de fichiers de machines virtuelles (VMFS)
* datastores NFS




| Machine virtuelle Hyper-V  a| 
LUN iSCSI connectés directement au système invité par l’initiateur iSCSI


NOTE: La protection des bases de données stockées sur des disques pass-through ou des fichiers VHD/VHDX provisionnés sur NetApp storage n'est pas prise en charge.

|===


[[requirements-for-protecting-vmware-workloads]]
== Exigences pour la protection des charges de travail VMware

Vous avez besoin d’exigences spécifiques pour découvrir et protéger vos charges de travail VMware.

|===
| Exigence | Pris en charge 


| Types de datastore | NFSv3, NFSv4.1 et VMFS 


| Versions de VMware ESXi Server | 7.0U1 et versions ultérieures 


| Versions VMware vCenter vSphere | 7.0U1 et versions ultérieures 


| Outils VMware | VMware Tools est requis pour utiliser la fonction de restauration de fichiers et de dossiers ainsi que les sauvegardes cohérentes avec les machines virtuelles. Pour vous assurer que la version de VMware Tools correspond à votre version d'ESXi Server, consultez la  https://packages.vmware.com/tools/versions["Informations de correspondance des versions VMware"]. 


| Types d'adresses IP | IPv4, IPv6 


| Versions TLS de VMware | 1.2, 1.3 


| Stockage connecté  a| 
* ONTAP 9.13.1 ou version ultérieure (ONTAP 9.19.1 ou version ultérieure est requis pour prendre en charge plus de 6 compartiments par système sur différents fournisseurs de cloud ; jusqu’à 100 compartiments maximum)
* Amazon FSx for NetApp ONTAP storage systems exécutant la version 9.13.1 ou ultérieure
* ASA r2 SAN uniquement (ONTAP 9.17.1 ou version ultérieure requis)


|===
[cols="33,66a"]
|===
| Type de port | Port préconfiguré 


| Port du serveur VMware ESXi  a| 
443 (HTTPS), bidirectionnel. La fonction de restauration de fichiers et de dossiers utilise ce port.



| Cluster de stockage ou port de VM de stockage  a| 
* 443 (HTTPS), bidirectionnel.
* 80 (HTTP), bidirectionnel. Ce port est utilisé pour la communication entre l'appliance virtuelle et la machine virtuelle de stockage ou le cluster contenant la machine virtuelle de stockage.


|===
.Exigences de contrôle d'accès basé sur les rôles (RBAC) pour la protection des charges de travail VMware
Votre compte utilisateur Console doit disposer du rôle de super administrateur de Backup and Recovery pour pouvoir travailler avec les charges de travail VMware.

Pour plus d'informations sur les rôles de Backup and Recovery, veuillez consulter https://docs.netapp.com/us-en/console-setup-admin/reference-iam-backup-rec-roles.html["Rôles de sauvegarde et de restauration dans la NetApp Console"].



[[requirements-for-protecting-kvm-workloads]]
== Exigences pour la protection des charges de travail KVM

Vous avez besoin d’exigences spécifiques pour découvrir et protéger les machines virtuelles KVM.


NOTE: ONTAP 9.19.1 ou une version ultérieure est nécessaire pour prendre en charge plus de 6 compartiments par système sur différents fournisseurs de cloud (jusqu'à 100 compartiments maximum).

* Une distribution Linux moderne exécutant la version du noyau 5.14.0-503.22.1.el9_5.x86_64 (long terme) ou ultérieure
* Vos hôtes KVM et vos machines virtuelles doivent être gérés par une plateforme de gestion. NetApp Backup and Recovery prend en charge les plateformes de gestion suivantes :
+
** Apache CloudStack 4.22.0.0


* Assurez-vous que le trafic réseau entrant sur le port 22 est autorisé depuis l'agent de console vers l'hôte KVM.
* Agent invité QEMU version 9.0.0 ou ultérieure
* libvirt version 10.5.0 ou ultérieure



NOTE: Pour garantir la réussite des restaurations de charges de travail KVM, assurez-vous que le paramètre *Activer l'instantané cohérent avec la machine virtuelle* est actif dans la stratégie de protection que vous utilisez pour les sauvegardes KVM.

[NOTE]
====
Pour activer la protection des machines virtuelles KVM administrées par des utilisateurs non root, procédez comme suit :

. Montez le volume en tant que type NFS3 pour éviter l'utilisation de `nobody` utilisateur et groupe.
. Utilisez la commande suivante pour ajouter un utilisateur non root à la liste `qemu` groupe tout en préservant leurs groupes existants :
+
[source, console]
----
usermod -aG qemu <non-root-user>
----
. Utilisez la commande suivante pour accorder la propriété du chemin de montage à `qemu` utilisateur et groupe et modifier les autorisations du chemin de montage :
+
[source, console]
----
chown -R qemu:qemu <kvm_vm_mount_path> & chmod 771 <kvm_vm_mount_path>
----
. Supprimez le répertoire NetApp_SnapCenter_Backups existant s'il existe.


====


[[requirements-for-protecting-oracle-database-workloads]]
== Exigences relatives à la protection des charges de travail Oracle Database

Assurez-vous que votre environnement répond aux exigences spécifiques pour découvrir et protéger les ressources Oracle Database.


NOTE: ONTAP 9.19.1 ou une version ultérieure est nécessaire pour prendre en charge plus de 6 compartiments par système sur différents fournisseurs de cloud (jusqu'à 100 compartiments maximum).

|===
| Exigence | Pris en charge 


| Topologie de déploiement  a| 
* Autonome (NFS, SAN, ASM SAN)
* RAC sur ASM (VMDK sur VMFS)




| Versions d'Oracle Database  a| 
* Oracle Database 19c
* Oracle Database 21c
* Base de données Oracle AI 26ai




| Stockage de bases de données | Doit être déployé sur NetApp ONTAP (principal ou secondaire) 


| OS de l'hôte  a| 
* Red Hat Enterprise Linux 8
* Red Hat Enterprise Linux 9




| Stockage d'objets (cibles de sauvegarde)  a| 
* Stockage d'objets Azure
* Amazon AWS
* NetApp StorageGRID
* ONTAP S3


|===


[[requirements-for-protecting-kubernetes-applications]]
== Exigences pour la protection des applications Kubernetes

Vous avez besoin d’exigences spécifiques pour découvrir les ressources Kubernetes et protéger vos applications Kubernetes.

Pour connaître les exigences de NetApp Console, veuillez consulter <<Préparer la NetApp Console>>.


NOTE: ONTAP 9.19.1 ou une version ultérieure est nécessaire pour prendre en charge plus de 6 compartiments par système sur différents fournisseurs de cloud (jusqu'à 100 compartiments maximum).


NOTE: NetApp recommande fortement d'attribuer une adresse IP statique à l'agent Console que vous utilisez pour les charges de travail Kubernetes afin d'éviter les problèmes en cas de changement d'adresse IP de l'agent.

* Un système ONTAP principal (les systèmes ASA r2 ne sont pas pris en charge)
* NetApp Trident 25.02 ou version ultérieure
* NetApp Trident Protect 26.05 ou version ultérieure (installé sur le cluster Kubernetes lors de la découverte)
* Un cluster Kubernetes - Les distributions et versions Kubernetes prises en charge incluent celles prises en charge par https://docs.netapp.com/us-en/trident/trident-protect/trident-protect-requirements.html["Trident Protect"].
+
** Assurez-vous que le port TCP 443 n'est pas filtré dans le sens sortant entre le cluster Kubernetes, le Trident Protect Connector et le Trident Protect proxy.






[[requirements-for-protecting-hyper-v-workloads]]
== Exigences pour la protection des charges de travail Hyper-V

Assurez-vous que votre instance Hyper-V répond à des exigences spécifiques pour découvrir et protéger les machines virtuelles.

|===
| Exigence | Pris en charge 


| Microsoft Hyper-V | 2019, 2022 et 2025 editions 


| ASP.NET Core Runtime | 8.0.24 Hosting Bundle (et tous les correctifs 8.0.x ultérieurs) 


| PowerShell | 7.4.13 ou version ultérieure 


| Si des utilisateurs non administrateurs doivent protéger des machines virtuelles Hyper-V, assurez-vous que les utilisateurs disposent des autorisations suivantes  a| 
* Membre du groupe des administrateurs locaux
* Partie de la politique de sécurité locale « Se connecter en tant que service »




| Assurez-vous que le trafic HTTPS bidirectionnel est autorisé pour les ports suivants dans les paramètres du pare-feu Windows  a| 
* TCP 8144 (NetApp Plugin pour Hyper-V)
* TCP 8145 (NetApp Plugin pour Windows)




| Stockage connecté  a| 
* ONTAP 9.13.1 ou version ultérieure
* Partages SMB
* Stockage SAN connecté via iSCSI ou Fibre Channel


|===
.Configuration matérielle requise pour l'hôte Hyper-V
* Les hôtes autonomes et en cluster FCI sont pris en charge
* 1 Go de RAM minimum pour le plug-in NetApp Hyper-V sur l'hôte Hyper-V
* 5 Go minimum d'espace d'installation et de journal pour le plug-in sur l'hôte Hyper-V
+

NOTE: Assurez-vous d’allouer suffisamment d’espace disque sur l’hôte Hyper-V pour le dossier des journaux et surveillez régulièrement son utilisation.  L'espace requis dépend de la fréquence des sauvegardes et des opérations de protection des données.  S'il n'y a pas assez d'espace, les journaux ne seront pas générés.



.NetApp exigences de configuration ONTAP
* Un système ONTAP principal (ONTAP 9.14.1 ou version ultérieure - ONTAP 9.19.1 ou version ultérieure est requis pour prendre en charge plus de 6 compartiments par système auprès de différents fournisseurs de cloud ; jusqu'à 100 compartiments maximum)
* Pour les déploiements Hyper-V utilisant des partages SMB pour stocker les données des machines virtuelles, assurez-vous que la propriété de partage à disponibilité continue est activée sur le système ONTAP. Consultez la  https://docs.netapp.com/us-en/ontap/smb-hyper-v-sql/configure-shares-continuous-availability-task.html["Documentation ONTAP"^] pour obtenir des instructions.

