---
sidebar: sidebar 
permalink: prev-vmware-protect-overview.html 
keywords: backing up, back up, backup, backup application data, Amazon Web services, AWS, NetApp Backup and Recovery, Oracle database, Microsoft SQL Server database, SAP HANA database 
summary: Protégez vos charges de travail VMware avec NetApp NetApp Backup and Recovery. 
---
= Présentation de la protection des charges de travail des machines virtuelles dans NetApp Backup and Recovery
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Protégez les charges de travail de vos machines virtuelles avec NetApp Backup and Recovery.  NetApp Backup and Recovery fournit des opérations de sauvegarde et de restauration rapides, peu encombrantes, cohérentes en cas de panne et cohérentes avec les machines virtuelles pour les machines virtuelles, les banques de données et les VMDK.

Vous pouvez sauvegarder des banques de données sur Amazon Web Services S3, Microsoft Azure Blob, Google Cloud Platform et StorageGRID et restaurer des machines virtuelles sur l'hôte SnapCenter Plug-in for VMware vSphere sur site.

[]
====
*REMARQUE* Pour basculer vers et depuis les charges de travail NetApp Backup and Recovery, reportez-vous àlink:br-start-switch-ui.html["Basculer vers différentes charges de travail de sauvegarde et de récupération NetApp"] .

====
Pour obtenir des instructions sur la protection des charges de travail des machines virtuelles, consultez les rubriques suivantes :

* link:prev-vmware-policy-create.html["Créer une politique pour les charges de travail VMware"]
* link:prev-vmware-backup-aws.html["Sauvegarder les banques de données VMware sur Amazon Web Services"]
* link:prev-vmware-backup-azure.html["Sauvegarder les banques de données VMware sur Microsoft Azure"]
* link:prev-vmware-backup-gcp.html["Sauvegarder les banques de données VMware sur Google Cloud Platform"]
* link:prev-vmware-backup-storagegrid.html["Sauvegarder les banques de données VMware sur StorageGRID"]
* link:prev-vmware-restore.html["Restaurer les charges de travail VMware"]
* link:prev-vmware-manage.html["Gérer la protection des charges de travail VMware"]

