---
sidebar: sidebar 
permalink: prev-ontap-discover-no-activate.html 
keywords: activate, backup and recovery, volumes, back up, discover 
summary: Découvrez les systèmes et les volumes sans activer NetApp Backup and Recovery. 
---
= Découvrez les systèmes et volumes ONTAP sans activer NetApp Backup and Recovery
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Découvrez les systèmes et volumes ONTAP avant d’activer NetApp Backup and Recovery. Après la découverte, vous pouvez consulter les volumes, mais vous ne pouvez pas les protéger tant que vous n’avez pas activé Backup and Recovery.

.Étapes
. Accédez à *Protection > Backup and Recovery*.
. Sélectionnez la tuile *Volumes*.
+
Le tableau de bord Volumes s'affiche.

. Sélectionnez *Discover systems*.
. Dans la liste, sélectionnez tous les systèmes dont vous souhaitez découvrir les volumes.
. Sélectionnez *Découvrir*.
. Dans NetApp Backup and Recovery, sélectionnez *Inventaire*.
+
Le processus de découverte commence. Vous pouvez consulter l'état et le résultat de la découverte dans le Moniteur de tâches.


