---
sidebar: sidebar 
permalink: prev-reference-gcp-archive-storage-tiers.html 
keywords: backing up, back up, backup, backup application data, Amazon Web services, AWS, NetApp Backup and Recovery, Oracle database, Microsoft SQL Server database, SAP HANA database 
summary: 'NetApp Backup and Recovery prend en charge une classe de stockage d"archivage Google et la plupart des régions.' 
---
= Niveaux de stockage d'archives Google pris en charge avec NetApp Backup and Recovery
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Utilisez ces informations pour comprendre le niveau d'archivage de Google Cloud Storage que NetApp Backup and Recovery prend en charge. Vous pouvez également consulter les coûts de restauration et les délais de récupération des sauvegardes archivées.



[[supported-google-archival-storage-classes-for-netapp-backup-and-recovery]]
== Classes de stockage d'archivage Google prises en charge pour NetApp Backup and Recovery

Lors de leur création, les fichiers de sauvegarde sont initialement stockés dans un stockage _Standard_. Ce niveau est optimisé pour le stockage de données rarement consultées, tout en permettant un accès immédiat.

Si votre cluster local utilise ONTAP 9.12.1 ou une version ultérieure, vous pouvez choisir de transférer les anciennes sauvegardes vers le stockage _Archive_ dans l’interface utilisateur NetApp Backup and Recovery après un certain nombre de jours (généralement plus de 30 jours) afin d’optimiser davantage les coûts. Les données dans ce niveau entraîneront un coût de récupération plus élevé, il est donc important de prendre en compte la fréquence à laquelle vous pourriez avoir besoin de restaurer des données à partir de ces fichiers de sauvegarde archivés. Consultez la section de cette page concernant la restauration des données à partir du stockage d’archivage.

Notez que lorsque vous configurez NetApp Backup and Recovery avec ce type de règle de cycle de vie, vous ne devez configurer aucune règle de cycle de vie lors de la configuration du bucket dans votre compte Google.

https://cloud.google.com/storage/docs/storage-classes["En savoir plus sur les classes de stockage Google"^].



[[restore-data-from-archival-storage]]
== Restaurer les données à partir du stockage d'archives

Bien que le stockage d'anciens fichiers de sauvegarde dans le stockage d'archives soit beaucoup moins coûteux que le stockage standard, l'accès aux données d'un fichier de sauvegarde dans le stockage d'archives pour les opérations de restauration prendra un peu plus de temps et coûtera plus cher.

Combien coûte la restauration des données de Google Archive ?:: Pour connaître les tarifs détaillés de Google Cloud Storage par région, visitez le https://cloud.google.com/storage/pricing["Page de tarification de Google Cloud Storage"^] .
Combien de temps faudra-t-il pour restaurer mes objets archivés dans Google Archive ?:: Le temps de restauration total est composé de deux parties :
+
--
* *Temps de récupération* : Le temps nécessaire pour récupérer le fichier de sauvegarde de l'archive et le placer dans le stockage standard.  C'est ce qu'on appelle parfois le temps de « réhydratation ».  Contrairement aux solutions de stockage « les plus froides » fournies par d’autres fournisseurs de cloud, vos données sont accessibles en quelques millisecondes.
* *Temps de restauration* : Le temps nécessaire pour restaurer les données à partir du fichier de sauvegarde dans le stockage standard.  Cette fois, ce n’est pas différent de l’opération de restauration typique directement à partir du stockage standard, lorsque vous n’utilisez pas de niveau d’archivage.


--


[NOTE]
====
La restauration d'un volume ou d'un fichier à partir d'un stockage d'archive peut prendre plus de temps. La tâche reste *En cours* dans le Moniteur de tâches pendant que Backup and Recovery réessaie la restauration en fonction de la priorité sélectionnée. Surveillez la restauration dans le *Moniteur de tâches* ; elle se termine lorsque la tâche atteint un état final, tel que *Terminée* ou *Échec*, après toutes les tentatives de restauration. Ne lancez pas une autre restauration à moins que la tâche n'échoue finalement.

====