---
sidebar: sidebar 
permalink: prev-vmware-policy-create.html 
keywords: backing up, back up, backup, backup application data, Amazon Web services, AWS, NetApp Backup and Recovery, Oracle database, Microsoft SQL Server database, SAP HANA database 
summary: Protégez vos charges de travail VMware avec NetApp NetApp Backup and Recovery. 
---
= Créer une politique de sauvegarde des banques de données dans NetApp Backup and Recovery
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Vous pouvez créer une politique ou utiliser l'une des politiques prédéfinies suivantes disponibles dans NetApp Backup and Recovery.


NOTE: Pour basculer vers et depuis les charges de travail NetApp Backup and Recovery , reportez-vous àlink:br-start-switch-ui.html["Basculer vers différentes charges de travail de NetApp Backup and Recovery"] .

.Avant de commencer
* Vous devez créer des politiques si vous ne souhaitez pas modifier les politiques prédéfinies.
* Pour déplacer des sauvegardes du magasin d'objets vers le stockage d'archivage, vous devez exécuter ONTAP 9.10.1 ou une version ultérieure et Amazon Web Services ou Microsoft Azure doit être le fournisseur de cloud.
* Vous devez configurer le niveau d’accès aux archives pour chaque fournisseur de cloud.


.À propos de cette tâche
Les politiques prédéfinies suivantes sont disponibles dans la NetApp Console:

|===
| Nom de la politique | Étiquette | Valeur de rétention 


 a| 
1 an de rétention quotidienne à long terme (LTR)
 a| 
Tous les jours
 a| 
366



 a| 
5 ans de LTR quotidien
 a| 
Tous les jours
 a| 
1830



 a| 
LTR hebdomadaire sur 7 ans
 a| 
Hebdomadaire
 a| 
370



 a| 
LTR mensuel sur 10 ans
 a| 
Mensuel
 a| 
120

|===
.Étapes
. Dans la page Machines virtuelles, dans la liste déroulante Paramètres, sélectionnez *Politiques*.
. Sélectionnez *Créer une politique*.
. Dans la section Détails de la politique, spécifiez le nom de la politique.
. Dans la section Rétention, sélectionnez l’un des types de rétention et spécifiez le nombre de sauvegardes à conserver.
. Sélectionnez Principal ou Secondaire comme source de stockage de sauvegarde.
. (Facultatif) Si vous souhaitez déplacer les sauvegardes du magasin d'objets vers le stockage d'archivage après un certain nombre de jours pour optimiser les coûts, cochez la case *Horaires de sauvegarde vers l'archivage* et saisissez le nombre de jours après lesquels la sauvegarde doit être archivée.
. Sélectionnez *Créer*.
+

NOTE: Vous ne pouvez pas modifier ou supprimer une politique associée à une banque de données.


