---
sidebar: sidebar 
permalink: prev-ontap-backup-onprem-s3-compatible.html 
keywords: backing up, back up, backup, backup application data, Amazon Web services, AWS, NetApp Backup and Recovery, S3, compatible, Oracle database, Microsoft SQL Server database, SAP HANA database 
summary: Protégez vos charges de travail VMware avec NetApp Backup and Recovery. 
---
= Sauvegardez les données ONTAP locales sur un stockage compatible S3 avec NetApp Backup and Recovery
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Effectuez quelques étapes dans NetApp Backup and Recovery pour commencer à sauvegarder les données de volume de vos systèmes ONTAP principaux sur site. Vous pouvez envoyer les sauvegardes vers un système de stockage ONTAP secondaire (un volume répliqué) ou vers un compartiment sur un système de stockage compatible S3, ou les deux.



[[verify-support-for-your-configuration]]
== Vérifiez la prise en charge de votre configuration

Lisez les exigences suivantes pour vous assurer que vous disposez d'une configuration prise en charge avant de commencer à sauvegarder des volumes sur un stockage compatible S3.

Versions ONTAP prises en charge:: Une version minimale d'ONTAP 9.17.1 est requise.




[[supported-actions]]
=== Actions prises en charge

Voici les actions prises en charge lors de la sauvegarde sur un stockage compatible S3 :

* Sauvegarde des instantanés cohérents en cas de panne et au niveau de l'application depuis ONTAP sur site vers des espaces de stockage d'objets tiers compatibles S3
* Flux de travail essentiels en matière de protection des données : sauvegarde, restauration et suppression des sauvegardes
* Testé et validé avec le stockage objet Wasabi ; des clients ont également signalé des déploiements réussis avec MinIO et IBM Cloud Object Storage
* NetApp Support accepte et traite toutes les demandes d'assistance concernant les espaces de stockage d'objets compatibles S3 tiers




[[unsupported-features-and-configurations]]
=== Fonctionnalités et configurations non prises en charge

Les fonctionnalités et configurations suivantes ne sont pas prises en charge lors de la sauvegarde sur un stockage compatible S3 :

* Bring Your Own Bucket (BYOB) n'est pas pris en charge
* L'activation de DataLock dans les politiques de sauvegarde n'est pas prise en charge
* L'activation du mode d'archivage dans les stratégies de sauvegarde n'est pas prise en charge
* Les options de chiffrement au niveau du compartiment ne sont pas prises en charge
* MetroCluster configurations ne sont pas prises en charge
* Les environnements ONTAP basés sur le cloud ne sont pas pris en charge ; seul ONTAP sur site est pris en charge




[[caveats]]
=== Mises en garde

Lors de la sauvegarde sur un stockage compatible S3, tenez compte des points suivants :

* *Les performances ne sont pas garanties* : les produits NetApp sont sensibles à la latence et aux IOPS de l’API S3. Les solutions de stockage d’objets tierces doivent offrir une latence et des IOPS équivalentes à celles d’AWS S3 pour garantir des performances comparables. NetApp ne prend pas en charge le dépannage des performances des solutions de stockage d’objets.
* *Aucune responsabilité en cas de corruption des données ou de perte de données* : NetApp n’est pas responsable de la perte de données ou de l’interruption causées par des problèmes liés aux stockages d’objets S3 tiers.
* *Prise en charge limitée des fonctionnalités* : L’ensemble des fonctionnalités prises en charge pour les cibles compatibles S3 tierces est un sous-ensemble de celles disponibles pour les cibles natives (AWS S3, Azure Blob, GCP, ONTAP S3, StorageGRID).




[[prepare-your-console-agent]]
== Préparez votre agent de console

L'agent Console est le logiciel principal pour les fonctionnalités de la console.  Un agent de console est requis pour sauvegarder et restaurer vos données ONTAP .



[[create-or-switch-console-agents]]
=== Créer ou changer d'agents de console

Lorsque vous sauvegardez des données sur un stockage compatible S3, un agent Console doit être disponible sur site ou dans le cloud. Vous devrez soit installer un nouvel agent Console, soit vous assurer que l'agent Console actuellement sélectionné se trouve dans l'un de ces emplacements. L'agent Console sur site peut être installé dans un site avec ou sans accès à Internet.

* https://docs.netapp.com/us-en/console-setup-admin/concept-connectors.html["En savoir plus sur les agents de console"^]
* https://docs.netapp.com/us-en/console-setup-admin/concept-connectors.html#how-to-create-a-connector["Installez l'agent de console dans votre environnement cloud"^]
* https://docs.netapp.com/us-en/console-setup-admin/task-quick-start-connector-on-prem.html["Installation de l'agent de console sur un hôte Linux avec accès Internet"^]
* https://docs.netapp.com/us-en/console-setup-admin/task-quick-start-private-mode.html["Installation de l'agent Console sur un hôte Linux sans accès Internet"^]
* https://docs.netapp.com/us-en/console-setup-admin/task-manage-multiple-connectors.html#switch-between-connectors["Basculer entre les agents de la console"^]




[[prepare-console-agent-networking-requirements]]
=== Préparer les exigences réseau de l'agent de console

Assurez-vous que le réseau sur lequel l’agent de console est installé permet les connexions suivantes :

* Une connexion HTTPS via le port 443 vers le serveur compatible S3
* Une connexion HTTPS via le port 443 vers votre LIF de gestion de cluster ONTAP source
* Une connexion Internet sortante via le port 443 vers NetApp Backup and Recovery (non requise lorsque l'agent de console est installé sur un site « sombre »)




==== Considérations sur le mode privé (site sombre)

La fonctionnalité de NetApp Backup and Recovery est intégrée à l’agent de la console.  Lorsqu'il est installé en mode privé, vous devrez mettre à jour périodiquement le logiciel de l'agent de la console pour accéder aux nouvelles fonctionnalités.  Vérifiez lelink:whats-new.html["Nouveautés de NetApp Backup and Recovery"] pour voir les nouvelles fonctionnalités de chaque version de NetApp Backup and Recovery .  Lorsque vous souhaitez utiliser les nouvelles fonctionnalités, suivez les étapes pour https://docs.netapp.com/us-en/console-setup-admin/task-upgrade-connector.html["mettre à niveau le logiciel de l'agent de la console"^] .

Lorsque vous utilisez NetApp Backup and Recovery dans un environnement SaaS standard, les données de configuration NetApp Backup and Recovery sont sauvegardées dans le cloud. Lorsque vous utilisez NetApp Backup and Recovery sur un site sans accès Internet, les données de configuration NetApp Backup and Recovery sont sauvegardées dans le compartiment compatible S3 où vos sauvegardes sont stockées.



[[verify-license-requirements]]
== Vérifier les exigences de licence

Avant de pouvoir activer NetApp Backup and Recovery pour votre cluster, vous devez acheter et activer une licence BYOL NetApp Backup and Recovery auprès de NetApp. La licence concerne la sauvegarde et la restauration sur stockage objet ; aucune licence n’est nécessaire pour créer des instantanés ou des volumes répliqués. Cette licence est destinée au compte et peut être utilisée sur plusieurs systèmes.

Vous aurez besoin du numéro de série de NetApp qui vous permet d'utiliser le service pendant la durée et la capacité de la licence. link:br-start-licensing.html["Apprenez à gérer vos licences BYOL"] .


TIP: La licence PAYGO n'est pas prise en charge lors de la sauvegarde de fichiers sur un stockage compatible S3.



[[prepare-your-ontap-clusters]]
== Préparez vos clusters ONTAP

Préparez votre système ONTAP source sur site et tous les systèmes ONTAP ou Cloud Volumes ONTAP secondaires sur site.

La préparation de vos clusters ONTAP implique les étapes suivantes :

* Découvrez vos systèmes ONTAP dans la NetApp Console
* Vérifier la configuration système requise ONTAP
* Vérifier les exigences réseau ONTAP pour la sauvegarde des données sur le stockage d'objets
* Vérifier les exigences réseau ONTAP pour la réplication des volumes




[[discover-your-ontap-systems-in-netapp-console]]
=== Découvrez vos systèmes ONTAP dans la NetApp Console

Votre système ONTAP source sur site et tous les systèmes ONTAP ou Cloud Volumes ONTAP secondaires sur site doivent être disponibles sur la page *Systèmes* de la NetApp Console .

Vous devrez connaître l’adresse IP de gestion du cluster et le mot de passe du compte utilisateur administrateur pour ajouter le cluster. https://docs.netapp.com/us-en/storage-management-ontap-onprem/task-discovering-ontap.html["Apprenez à découvrir un cluster"^] .



[[verify-ontap-system-requirements]]
=== Vérifier la configuration système requise ONTAP

Assurez-vous que votre système ONTAP répond aux exigences suivantes :

* Minimum ONTAP 9.8 ; ONTAP 9.8P13 et versions ultérieures sont recommandés.
* Une licence SnapMirror (incluse dans le cadre du pack Premium ou du pack de protection des données).
+
*Remarque :* le « Hybrid Cloud Bundle » n'est pas requis lors de l'utilisation de NetApp Backup and Recovery.

+
Apprenez à https://docs.netapp.com/us-en/ontap/system-admin/manage-licenses-concept.html["gérez vos licences de cluster"^] .

* L'heure et le fuseau horaire sont correctement réglés.  Apprenez à https://docs.netapp.com/us-en/ontap/system-admin/manage-cluster-time-concept.html["configurer l'heure de votre cluster"^] .
* Si vous répliquez des données, vérifiez que les systèmes source et de destination exécutent des versions ONTAP compatibles.
+
https://docs.netapp.com/us-en/ontap/data-protection/compatible-ontap-versions-snapmirror-concept.html["Afficher les versions ONTAP compatibles pour les relations SnapMirror"^].





[[verify-ontap-networking-requirements-for-backing-up-data-to-object-storage]]
=== Vérifier les exigences réseau ONTAP pour la sauvegarde des données sur le stockage d'objets

Vous devez vous assurer que les exigences suivantes sont respectées sur le système qui se connecte au stockage d’objets.

[NOTE]
====
* Lorsque vous utilisez une architecture de sauvegarde en éventail, les paramètres doivent être configurés sur le système de stockage _principal_.
* Lorsque vous utilisez une architecture de sauvegarde en cascade, les paramètres doivent être configurés sur le système de stockage _secondaire_.
+
link:prev-ontap-protect-journey.html["En savoir plus sur les types d'architecture de sauvegarde"].



====
Les exigences de mise en réseau du cluster ONTAP suivantes sont nécessaires :

* Le cluster ONTAP initie une connexion HTTPS via un port spécifié par l'utilisateur depuis la LIF intercluster vers le serveur compatible S3 pour les opérations de sauvegarde et de restauration. Le port est configurable lors de la configuration de la sauvegarde.
+
ONTAP lit et écrit des données vers et depuis le stockage d'objets.  Le stockage d'objets ne s'initialise jamais, il répond simplement.

* ONTAP nécessite une connexion entrante de l'agent de console au LIF de gestion du cluster.
* Un LIF intercluster est requis sur chaque nœud ONTAP qui héberge les volumes que vous souhaitez sauvegarder.  Le LIF doit être associé à l'_IPspace_ ONTAP doit utiliser pour se connecter au stockage d'objets. https://docs.netapp.com/us-en/ontap/networking/standard_properties_of_ipspaces.html["En savoir plus sur IPspaces"^] .
+
Lorsque vous configurez NetApp Backup and Recovery, vous êtes invité à indiquer l'espace IP à utiliser.  Vous devez choisir l’espace IP auquel chaque LIF est associé.  Il peut s'agir de l'espace IP « par défaut » ou d'un espace IP personnalisé que vous avez créé.

* Les LIF intercluster des nœuds peuvent accéder au magasin d'objets (non requis lorsque l'agent de console est installé sur un site « sombre »).
* Les serveurs DNS ont été configurés pour la machine virtuelle de stockage où se trouvent les volumes.  Découvrez comment https://docs.netapp.com/us-en/ontap/networking/configure_dns_services_auto.html["configurer les services DNS pour le SVM"^] .
* Si vous utilisez un IPspace différent de Default, vous devrez peut-être créer une route statique pour accéder au stockage d'objets.
* Mettez à jour les règles de pare-feu, si nécessaire, pour autoriser les connexions du service NetApp Backup and Recovery d' ONTAP au stockage d'objets via le port que vous avez spécifié (généralement le port 443) et le trafic de résolution de noms de la machine virtuelle de stockage vers le serveur DNS via le port 53 (TCP/UDP).




[[verify-ontap-networking-requirements-for-replicating-volumes]]
=== Vérifier les exigences réseau ONTAP pour la réplication des volumes

Si vous prévoyez de créer des volumes répliqués sur un système ONTAP secondaire à l'aide de NetApp Backup and Recovery, assurez-vous que les systèmes source et de destination répondent aux exigences réseau suivantes.

* Si le cluster est sur site, vous devez disposer d’une connexion entre votre réseau d’entreprise et votre réseau virtuel chez le fournisseur de cloud. Il s’agit généralement d’une connexion VPN.
* Les clusters ONTAP doivent répondre à des exigences supplémentaires en matière de sous-réseau, de port, de pare-feu et de cluster.




[[activate-backups-on-your-ontap-volumes]]
== Activer les sauvegardes sur vos volumes ONTAP

Activez les sauvegardes à tout moment directement depuis votre système sur site.

Un assistant vous guide à travers les principales étapes suivantes :

* Sélectionnez les volumes que vous souhaitez sauvegarder
* Définir la stratégie et les politiques de sauvegarde
* Revoyez vos sélections


Vous pouvez également<<Afficher les commandes de l'API>> à l'étape de révision, vous pouvez donc copier le code pour automatiser l'activation de la sauvegarde pour les futurs systèmes.



[[start-the-wizard]]
=== Démarrer l'assistant

.Étapes
. Accédez à l’assistant d’activation de sauvegarde et de récupération en utilisant l’une des méthodes suivantes :
+
** Depuis la page *Systèmes* de la console, sélectionnez le système et sélectionnez *Activer > Volumes de sauvegarde* à côté de Sauvegarde et récupération dans le panneau de droite.
** Sélectionnez *Volumes* dans la barre de sauvegarde et de récupération.  Dans l'onglet Volumes, sélectionnez l'option *Actions (...)* et sélectionnez *Activer la sauvegarde* pour un seul volume (qui n'a pas déjà la réplication ou la sauvegarde vers le stockage d'objets activée).


+
La page d’introduction de l’assistant affiche les options de protection, notamment les instantanés locaux, les réplications et les sauvegardes.  Si vous avez effectué la deuxième option de cette étape, la page Définir la stratégie de sauvegarde s’affiche avec un volume sélectionné.

. Continuez avec les options suivantes :
+
** Si vous disposez déjà d’un agent de console, vous êtes prêt.  Sélectionnez simplement *Suivant*.
** Si vous n’avez pas d’agent de console, l’option *Ajouter un agent de console* apparaît.  Se référer à<<Préparez votre agent de console>> .






[[select-the-volumes-that-you-want-to-back-up]]
=== Sélectionnez les volumes que vous souhaitez sauvegarder

Choisissez les volumes que vous souhaitez protéger.  Un volume protégé est un volume qui possède un ou plusieurs des éléments suivants : politique de snapshot, politique de réplication, politique de sauvegarde vers un objet.

Vous pouvez choisir de protéger les volumes FlexVol ou FlexGroup ; cependant, vous ne pouvez pas sélectionner une combinaison de ces volumes lors de l'activation de la sauvegarde pour un système.  Découvrez commentlink:prev-ontap-backup-manage.html["activer la sauvegarde pour des volumes supplémentaires dans le système"] (FlexVol ou FlexGroup) après avoir configuré la sauvegarde pour les volumes initiaux.

[NOTE]
====
* Vous ne pouvez activer une sauvegarde que sur un seul volume FlexGroup à la fois.
* Lors de la sélection des volumes sources que vous souhaitez protéger, vous ne pouvez sélectionner que les volumes ayant des paramètres SnapLock identiques. Les volumes que vous sélectionnez doivent soit tous avoir la fonctionnalité SnapLock activée, soit tous avoir la fonctionnalité SnapLock désactivée.


====
.Étapes
Notez que si les volumes que vous choisissez ont déjà des stratégies de snapshot ou de réplication appliquées, les stratégies que vous sélectionnez ultérieurement remplaceront ces stratégies existantes.

. Dans la page Sélectionner les volumes, sélectionnez le ou les volumes que vous souhaitez protéger.
+
** Vous pouvez également filtrer les lignes pour afficher uniquement les volumes avec certains types de volumes, styles et plus encore pour faciliter la sélection.
** Après avoir sélectionné le premier volume, vous pouvez sélectionner tous les volumes FlexVol (les volumes FlexGroup ne peuvent être sélectionnés qu'un par un).  Pour sauvegarder tous les volumes FlexVol existants, cochez d’abord un volume, puis cochez la case dans la ligne de titre.
** Pour sauvegarder des volumes individuels, cochez la case correspondant à chaque volume.


. Sélectionnez *Suivant*.




[[define-the-backup-strategy]]
=== Définir la stratégie de sauvegarde

La définition de la stratégie de sauvegarde implique la configuration des options suivantes :

* Options de protection : si vous souhaitez implémenter une ou toutes les options de sauvegarde : instantanés locaux, réplication et sauvegarde sur le stockage d'objets
* Architecture : si vous souhaitez utiliser une architecture de sauvegarde en éventail ou en cascade
* Politique d'instantané local
* Cible et politique de réplication
* Sauvegarde des informations de stockage d'objets (fournisseur, cryptage, mise en réseau, politique de sauvegarde et options d'exportation).


.Étapes
. Dans la page Définir la stratégie de sauvegarde, choisissez une ou toutes les options suivantes.  Les trois sont sélectionnés par défaut :
+
** *Instantanés locaux* : Crée des instantanés locaux.
** *Réplication* : crée des volumes répliqués sur un autre système de stockage ONTAP .
** *Sauvegarde* : sauvegarde les volumes dans un bucket sur un système ONTAP configuré pour S3.


. *Architecture* : Si vous avez choisi à la fois la réplication et la sauvegarde, choisissez l'un des flux d'informations suivants :
+
** *En cascade* : les données de sauvegarde circulent du système principal vers le système secondaire, puis du système secondaire vers le stockage d'objets.
** *Fan out* : les données de sauvegarde circulent du système principal vers le système secondaire _et_ du système principal vers le stockage d'objets.
+
Pour plus de détails sur ces architectures, reportez-vous àlink:prev-ontap-protect-journey.html["Planifiez votre voyage de protection"] .



. *Instantané local* : choisissez une politique d'instantané existante ou créez-en une nouvelle.
+

TIP: Si vous souhaitez créer une politique personnalisée avant d'activer le Snapshot, vous pouvez utiliser System Manager ou l'interface de ligne de commande ONTAP. `snapmirror policy create` commande.  Se référer à .

+

TIP: Pour créer une politique personnalisée à l'aide de Sauvegarde et récupération, reportez-vous àlink:br-use-policies-create.html["Créer une politique"] .

+
Pour créer une politique, sélectionnez *Créer une nouvelle politique* et procédez comme suit :

+
** Entrez le nom de la politique.
** Sélectionnez jusqu'à cinq programmes, généralement de fréquences différentes.
** Sélectionnez *Créer*.


. *Réplication* : Si vous avez sélectionné *Réplication*, définissez les options suivantes :
+
** *Cible de réplication* : sélectionnez le système de destination et la machine virtuelle de stockage. Vous pouvez également sélectionner l’agrégat de destination (ou les agrégats pour les volumes FlexGroup) ainsi qu’un préfixe ou un suffixe qui sera ajouté au nom du volume répliqué.
** *Politique de réplication* : Choisissez une politique de réplication existante ou créez-en une nouvelle.
+
Pour créer une politique, sélectionnez *Créer une nouvelle politique* et procédez comme suit :

+
*** Entrez le nom de la politique.
*** Sélectionnez jusqu'à cinq programmes, généralement de fréquences différentes.
*** Sélectionnez *Créer*.




. *Sauvegarder vers l'objet* : Si vous avez sélectionné *Sauvegarder*, définissez les options suivantes :
+
** *Fournisseur* : Sélectionnez * ONTAP S3*.
** *Paramètres du fournisseur* : saisissez les détails du nom de domaine complet (FQDN) du serveur S3, le port, ainsi que la clé d'accès et la clé secrète des utilisateurs.
+
La clé d'accès et la clé secrète sont destinées à l'utilisateur que vous avez créé pour donner au cluster ONTAP l'accès au bucket S3.

** *Mise en réseau* : choisissez l’espace IP dans le cluster ONTAP source où résident les volumes que vous souhaitez sauvegarder.  Les LIF intercluster pour cet espace IP doivent disposer d'un accès Internet sortant (non requis lorsque l'agent de console est installé sur un site « sombre »).
+

TIP: La sélection de l'espace IP correct garantit que NetApp Backup and Recovery peut établir une connexion d' ONTAP à votre stockage d'objets ONTAP S3.

** *Politique de sauvegarde* : sélectionnez une politique de sauvegarde existante ou créez-en une nouvelle.
+

TIP: Vous pouvez créer une politique avec System Manager ou l'interface de ligne de commande ONTAP .  Pour créer une politique personnalisée à l'aide de l'interface de ligne de commande ONTAP `snapmirror policy create` commande, se référer à .

+

TIP: Pour créer une politique personnalisée à l'aide de Sauvegarde et récupération, reportez-vous àlink:br-use-policies-create.html["Créer une politique"] .

+
Pour créer une politique, sélectionnez *Créer une nouvelle politique* et procédez comme suit :

+
*** Entrez le nom de la politique.
*** Sélectionnez jusqu'à cinq programmes, généralement de fréquences différentes.
*** Pour les règles de sauvegarde vers objet, configurez les paramètres Datalock et de protection contre les ransomwares. Pour plus d’informations sur Datalock et la protection contre les ransomwares, consultez link:prev-ontap-policy-object-options.html["Paramètres de la politique de sauvegarde sur objet"].
*** Sélectionnez *Créer*.


** *Exporter les instantanés existants vers le stockage objet en tant que fichiers de sauvegarde* : Si des instantanés locaux de volumes de ce système correspondent à l’étiquette de planification de sauvegarde que vous venez de sélectionner (par exemple, quotidienne, hebdomadaire, etc.), cette invite supplémentaire s’affiche. Cochez cette case pour que tous les instantanés historiques soient copiés vers le stockage d'objets en tant que fichiers de sauvegarde afin de garantir la protection la plus complète pour vos volumes.


. Sélectionnez *Suivant*.




[[review-your-selections]]
=== Revoyez vos sélections

C'est l'occasion de revoir vos sélections et de faire des ajustements, si nécessaire.

.Étapes
. Dans la page Révision, vérifiez vos sélections.
. Cochez éventuellement la case pour *Synchroniser automatiquement les étiquettes de politique de snapshot avec les étiquettes de politique de réplication et de sauvegarde*.  Cela crée des instantanés avec une étiquette qui correspond aux étiquettes des politiques de réplication et de sauvegarde.  Si les politiques ne correspondent pas, les sauvegardes ne seront pas créées.
. Sélectionnez *Activer la sauvegarde*.


.Résultat
NetApp Backup and Recovery commence à effectuer les sauvegardes initiales de vos volumes. Le transfert de base du volume répliqué et du fichier de sauvegarde inclut une copie complète des données sources. Les transferts suivants contiennent des copies différentielles des données de stockage primaire contenues dans les instantanés.

Un volume répliqué est créé dans le cluster de destination qui sera synchronisé avec le volume de stockage principal.

Un compartiment S3 est créé dans le compte de service indiqué par la clé d'accès S3 et la clé secrète que vous avez saisies, et les fichiers de sauvegarde y sont stockés.

Le tableau de bord de sauvegarde des volumes s'affiche pour vous permettre de surveiller l'état des sauvegardes.

Vous pouvez également surveiller l’état des tâches de sauvegarde et de restauration à l’aide de l’link:br-use-monitor-tasks.html["Page de surveillance des tâches"] .



[[show-the-api-commands]]
=== Afficher les commandes de l'API

Vous souhaiterez peut-être afficher et éventuellement copier les commandes API utilisées dans l’assistant d’activation de la sauvegarde et de la récupération.  Vous souhaiterez peut-être faire cela pour automatiser l’activation de la sauvegarde dans les futurs systèmes.

.Étapes
. Dans l’assistant d’activation de la sauvegarde et de la récupération, sélectionnez *Afficher la demande d’API*.
. Pour copier les commandes dans le presse-papiers, sélectionnez l'icône *Copier*.

