---
sidebar: sidebar 
permalink: task-setup-ca-certificates.html 
keywords: cloud backup, backup and recovery, backup, restore, certificates, protection, security, storagegrid, backup, back up 
summary: Créez un certificat de sécurité pour activer la communication entre NetApp Backup and Recovery et StorageGRID ou ONTAP. 
---
= Configurer les certificats d'autorité de certification pour NetApp Backup and Recovery
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Configurez les certificats d'autorité de certification pour que NetApp Backup and Recovery puisse valider les connexions sécurisées à StorageGRID ou ONTAP. Suivez les étapes correspondant à votre environnement et aux systèmes que vous souhaitez protéger.



[[create-a-ca-certificate-for-storagegrid]]
== Créer un certificat d'autorité de certification pour StorageGRID

Si la communication entre les conteneurs NetApp Backup and Recovery et StorageGRID doit vérifier le certificat StorageGRID, veuillez suivre les étapes suivantes.

Le certificat généré doit utiliser le même nom commun (CN) et le même nom alternatif du sujet que vous avez fournis dans NetApp Backup and Recovery lors de l’activation de la sauvegarde.

.Étapes
. Suivez les étapes de la documentation StorageGRID pour créer le certificat StorageGRID .
+
https://docs.netapp.com/us-en/storagegrid-118/admin/configuring-load-balancer-endpoints.html#attach-certificate["Informations StorageGRID sur la configuration des certificats"]

. Mettez à jour StorageGRID avec le certificat si vous ne l’avez pas déjà fait.
. Connectez-vous à l'agent Console en tant qu'utilisateur root. Exécutez :
+
[source, shell]
----
sudo su
----
. Trouvez le volume Docker de NetApp Backup and Recovery (Cloud Backup Service). Exécutez :
+
[source, shell]
----
docker volume ls | grep cbs
----
+
Exemple de sortie :

+
[listing]
----
local service-manager-2_cloudmanager_cbs_volume"
----
+

NOTE: Le nom du volume diffère selon les modes de déploiement Standard, Privé et Restreint. Cet exemple utilise le mode Standard. Se référer à https://docs.netapp.com/us-en/console-setup-admin/concept-modes.html["Modes de déploiement de la NetApp Console"] .

. Recherchez le point de montage du volume NetApp Backup and Recovery . Courir:
+
[source, shell]
----
docker volume inspect service-manager-2_cloudmanager_cbs_volume | grep Mountpoint
----
+
Exemple de sortie :

+
[listing]
----
"Mountpoint": "/var/lib/docker/volumes/service-manager-2_cloudmanager_cbs_volume/_data"
----
+

NOTE: Le point de montage diffère selon les modes de déploiement Standard, Privé et Restreint. Cet exemple montre un déploiement cloud standard. Se référer à https://docs.netapp.com/us-en/console-setup-admin/concept-modes.html["Modes de déploiement de la NetApp Console"] .

. Accédez au répertoire du point de montage. Exécutez :
+
[source, shell]
----
cd /var/lib/docker/volumes/service-manager-2_cloudmanager_cbs_volume/_data
----
. Si le certificat StorageGRID est signé par l'autorité de certification racine et une autorité de certification intermédiaire, ajoutez les deux fichiers  `pem` dans un seul fichier nommé  `sgws.crt` à l'emplacement actuel. N'ajoutez pas le certificat leaf à ce fichier.




[[steps-for-the-cloudmanagercbs-container]]
=== Étapes pour le conteneur cloudmanager_cbs

Activez la vérification du certificat du serveur StorageGRID dans NetApp Backup and Recovery (Cloud Backup Service).

. Accédez au volume Docker que vous avez identifié lors des étapes précédentes.
+
[source, shell]
----
cd /var/lib/docker/volumes/service-manager-2_cloudmanager_cbs_volume/_data
----
. Accédez au répertoire de configuration.
+
[source, shell]
----
cd cbs_config
----
. Créez et enregistrez un fichier de configuration comme indiqué ci-dessous avec l’un des noms suivants, selon votre environnement de déploiement :
+
** `production-customer.json` pour les déploiements en mode standard et en mode restreint
** `darksite-customer.json` pour les déploiements en mode privé
+
Se référer à https://docs.netapp.com/us-en/console-setup-admin/concept-modes.html["Modes de déploiement de la NetApp Console"] .

+
*Fichier de configuration*

+
[source, json]
----
{
  "protocols": {
    "sgws": {
      "certificates": {
        "reject-unauthorized": true,
        "ca-bundle": "/config/sgws.crt"
      }
    }
  }
}
----


. Sortez du conteneur. Courir:
+
[source, shell]
----
exit
----
. Redémarrage `cloudmanager_cbs` . Courir:
+
[source, shell]
----
docker restart cloudmanager_cbs
----




[[steps-for-the-cloudmanagercbscatalog-container]]
=== Étapes pour le conteneur cloudmanager_cbs_catalog

Ensuite, activez la vérification du certificat du serveur StorageGRID pour le service de catalogage.

. Passez au volume Docker :
+
[source, shell]
----
cd /var/lib/docker/volumes/service-manager-2_cloudmanager_cbs_volume/_data
----
. Configurer le catalogue. Courir:
+
[source, shell]
----
cd cbs_catalog_config
----
. Créez un fichier de configuration comme indiqué ci-dessous, avec l’un des noms suivants, selon votre environnement de déploiement :
+
** `production-customer.json` pour les déploiements en mode standard et en mode restreint
** `darksite-customer.json` pour les déploiements en mode privé
+
Se référer à https://docs.netapp.com/us-en/console-setup-admin/concept-modes.html["Modes de déploiement de la NetApp Console"] .

+
*Fichier de configuration du catalogue*

+
[source, json]
----
{
  "protocols": {
    "sgws": {
      "certificates": {
        "reject-unauthorized": true,
        "ca-bundle": "/config/sgws.crt"
      }
    }
  }
}
----


. Redémarrer le catalogue. Courir:
+
[source, shell]
----
docker restart cloudmanager_cbs_catalog
----




[[update-the-console-agent-certificate-with-the-storagegrid-certificate-based-on-the-agent-operating-system]]
=== Mettre à jour le certificat de l'agent de console avec le certificat StorageGRID en fonction du système d'exploitation de l'agent



==== Ubuntu

. Copiez le certificat SGWS dans  `/usr/local/share/ca-certificates`. Voici un exemple :
+
[source, shell]
----
cp /config/sgws.crt /usr/local/share/ca-certificates/
----
+
où `sgws.crt` est le certificat CA racine.

. Mettez à jour les certificats hôtes avec le certificat StorageGRID. Exécutez :
+
[source, shell]
----
sudo update-ca-certificates
----




==== Red Hat Enterprise Linux

. Copiez le certificat SGWS sur `/etc/pki/ca-trust/source/anchors/` .
+
[source, shell]
----
cp /config/sgws.crt /etc/pki/ca-trust/source/anchors/
----
+
où `sgws.crt` est le certificat CA racine.

. Mettez à jour les certificats d’hôte avec le certificat StorageGRID .
+
[source, shell]
----
update-ca-trust extract
----
. Mettre à jour le `ca-bundle.crt`
+
[source, shell]
----
cd /etc/pki/tls/certs/
openssl x509 -in ca-bundle.crt -text -noout
----
. Pour vérifier si les certificats sont présents, exécutez la commande suivante :
+
[source, shell]
----
openssl crl2pkcs7 -nocrl -certfile /etc/pki/tls/certs/ca-bundle.crt | openssl pkcs7 -print_certs | grep subject | head
----




[[create-a-ca-certificate-for-ontap]]
== Créer un certificat d'autorité de certification pour ONTAP

Si la communication entre les conteneurs NetApp Backup and Recovery et ONTAP doit valider le certificat ONTAP, complétez les étapes suivantes.

NetApp Backup and Recovery utilise l'adresse IP de gestion du cluster pour se connecter à ONTAP. Saisissez l'adresse IP du cluster dans les champs Subject Alternative Name du certificat. Spécifiez cette valeur lors de la génération du CSR dans System Manager.

Utilisez la documentation du gestionnaire de système pour créer un nouveau certificat CA pour ONTAP.

* https://docs.netapp.com/us-en/ontap/authentication/manage-certificates-sm-task.html["Gérer les certificats avec System Manager"]
* https://kb.netapp.com/on-prem/ontap/DM/System_Manager/SM-KBs/How_to_manage_ONTAP_SSL_certificates_via_System_Manager["Comment gérer les certificats SSL ONTAP avec System Manager"]


.Étapes
. Connectez-vous à l'agent Console en tant que root. Exécutez :
+
[source, shell]
----
sudo su
----
. Trouvez le volume Docker NetApp Backup and Recovery. Exécutez :
+
[source, shell]
----
docker volume ls | grep cbs
----
+
Exemple de sortie :

+
[listing]
----
local service-manager-2_cloudmanager_cbs_volume
----
+

NOTE: Le nom du volume diffère selon les modes de déploiement Standard, Privé et Restreint. Cet exemple montre un déploiement cloud standard. Se référer à https://docs.netapp.com/us-en/console-setup-admin/concept-modes.html["Modes de déploiement de la NetApp Console"] .

. Trouvez le point de montage du volume. Exécutez :
+
[source, shell]
----
docker volume inspect service-manager-2_cloudmanager_cbs_volume | grep Mountpoint
----
+
Exemple de sortie :

+
[listing]
----
"Mountpoint": "/var/lib/docker/volumes/service-manager-2_cloudmanager_cbs_volume/_data
----
+

NOTE: Le point de montage diffère selon les modes de déploiement Standard, Privé et Restreint. Cet exemple montre un déploiement cloud standard. Se référer à https://docs.netapp.com/us-en/console-setup-admin/concept-modes.html["Modes de déploiement de la NetApp Console"] .

. Accédez au répertoire du point de montage. Exécutez :
+
[source, shell]
----
cd /var/lib/docker/volumes/service-manager-2_cloudmanager_cbs_volume/_data
----
. Effectuez l’une des étapes suivantes :
+
** Si le certificat ONTAP est signé par l'autorité de certification racine et une autorité de certification intermédiaire, ajoutez le `pem` fichiers des deux dans un seul fichier nommé `ontap.crt` à l'emplacement actuel.
** Si le certificat ONTAP est signé par une seule autorité de certification, renommez-le `pem` déposer comme `ontap.crt` et copiez-le à l'emplacement actuel. N'ajoutez pas le certificat feuille à ce fichier.






[[steps-for-the-cloudmanagercbs-container]]
=== Étapes pour le conteneur cloudmanager_cbs

Ensuite, activez la vérification du certificat du serveur ONTAP dans NetApp Backup and Recovery (Cloud Backup Service).

. Accédez au volume Docker que vous avez identifié lors des étapes précédentes.
+
[source, shell]
----
cd /var/lib/docker/volumes/service-manager-2_cloudmanager_cbs_volume/_data
----
. Accédez au répertoire de configuration. Courir:
+
[source, shell]
----
cd cbs_config
----
. Créez un fichier de configuration comme indiqué ci-dessous, avec l’un des noms suivants, selon votre environnement de déploiement :
+
** `production-customer.json` pour les déploiements en mode standard et en mode restreint
** `darksite-customer.json` pour les déploiements en mode privé
+
Se référer à https://docs.netapp.com/us-en/console-setup-admin/concept-modes.html["Modes de déploiement de la NetApp Console"] .

+
*Fichier de configuration*

+
[source, json]
----
{
  "ontap": {
    "certificates": {
      "reject-unauthorized": true,
      "ca-bundle": "/config/ontap.crt"
    }
  }
}
----


. Sortez du conteneur. Courir:
+
[source, shell]
----
exit
----
. Redémarrez NetApp Backup and Recovery. Courir:
+
[source, shell]
----
docker restart cloudmanager_cbs
----




[[steps-for-the-cloudmanagercbscatalog-container]]
=== Étapes pour le conteneur cloudmanager_cbs_catalog

Activez la vérification du certificat du serveur ONTAP pour le service de catalogage.

. Passez au volume Docker. Exécutez :
+
[source, shell]
----
cd /var/lib/docker/volumes/service-manager-2_cloudmanager_cbs_volume/_data
----
. Courir:
+
[source, shell]
----
cd cbs_catalog_config
----
. Créez un fichier de configuration comme indiqué ci-dessous, avec l’un des noms suivants, selon votre environnement de déploiement :
+
** `production-customer.json` pour les déploiements en mode standard et en mode restreint
** `darksite-customer.json` pour les déploiements en mode privé
+
Se référer à https://docs.netapp.com/us-en/console-setup-admin/concept-modes.html["Modes de déploiement de la NetApp Console"] .

+
*Fichier de configuration*

+
[source, json]
----
{
  "ontap": {
    "certificates": {
      "reject-unauthorized": true,
      "ca-bundle": "/config/ontap.crt"
    }
  }
}
----


. Redémarrez NetApp Backup and Recovery. Courir:
+
[source, shell]
----
docker restart cloudmanager_cbs_catalog
----




[[create-a-certificate-for-both-ontap-and-storagegrid]]
== Créer un certificat pour ONTAP et StorageGRID

Si vous devez activer le certificat pour ONTAP et StorageGRID, le fichier de configuration ressemble à ceci :

*Fichier de configuration pour ONTAP et StorageGRID*

[source, json]
----
{
  "protocols": {
    "sgws": {
      "certificates": {
        "reject-unauthorized": true,
        "ca-bundle": "/config/sgws.crt"
      }
    }
  },
  "ontap": {
    "certificates": {
      "reject-unauthorized": true,
      "ca-bundle": "/config/ontap.crt"
    }
  }
}
----