= Modes de protection SnapLock Compliance et SnapLock Enterprise
:allow-uri-read: 




=== Modes de protection SnapLock Compliance et SnapLock Enterprise

NetApp Backup and Recovery peut désormais sauvegarder les volumes FlexVol et FlexGroup sur site qui sont configurés en utilisant les modes de protection SnapLock Compliance ou SnapLock Enterprise. Vos clusters doivent exécuter ONTAP 9.14 ou une version ultérieure pour cette prise en charge. La sauvegarde des volumes FlexVol en mode SnapLock Enterprise est prise en charge depuis ONTAP 9.11.1. Les versions antérieures d'ONTAP ne prennent pas en charge la sauvegarde des volumes protégés par SnapLock.

Consultez la liste complète des volumes pris en charge dans https://docs.netapp.com/us-en/data-services-backup-recovery/concept-backup-to-cloud.html["En savoir plus sur NetApp Backup and Recovery"].



=== Indexation du processus de recherche et de restauration sur la page Volumes

Avant de pouvoir utiliser la recherche et la restauration, vous devez activer « Indexation » sur chaque système source à partir duquel vous souhaitez restaurer les données du volume.  Cela permet au catalogue indexé de suivre les fichiers de sauvegarde pour chaque volume.  La page Volumes affiche désormais l’état de l’indexation :

* Indexé : Les volumes ont été indexés.
* En cours : L'indexation est en cours.
* Non indexé : l’indexation n’a pas commencé.
* Indexation suspendue : L’indexation est suspendue.
* Erreur : Une erreur d'indexation s'est produite.
* Non activé : l’indexation n’est pas activée pour cette source.

