= Prise en charge de Podman sur RHEL 8 ou 9 avec navigation et restauration
:allow-uri-read: 




=== Prise en charge de Podman sur RHEL 8 ou 9 avec navigation et restauration

NetApp Backup and Recovery prend désormais en charge les restaurations de fichiers et de dossiers sur les versions 8 et 9 de Red Hat Enterprise Linux (RHEL) à l'aide du moteur Podman.  Ceci s'applique à la méthode de NetApp Backup and Recovery .

L'agent de console version 3.9.40 prend en charge certaines versions de Red Hat Enterprise Linux 8 et 9 pour les installations manuelles de l'agent de console sur les hôtes RHEL, en plus des systèmes d'exploitation listés dans la  https://docs.netapp.com/us-en/console-setup-admin/task-prepare-private-mode.html#step-3-review-host-requirements["exigences de l'hôte"^]. Ces versions plus récentes de RHEL nécessitent le moteur Podman au lieu du moteur Docker. Auparavant, NetApp Backup and Recovery présentait deux limitations lors de l'utilisation du moteur Podman ; ces limitations ont été levées.

https://docs.netapp.com/us-en/data-services-backup-recovery/prev-ontap-restore.html["En savoir plus sur la restauration des données ONTAP à partir de fichiers de sauvegarde"].



=== L'indexation plus rapide du catalogue améliore la recherche et la restauration

Cette version inclut un index de catalogue amélioré qui termine l'indexation de base beaucoup plus rapidement.  Une indexation plus rapide vous permet d’utiliser la fonction Rechercher et restaurer plus rapidement.

https://docs.netapp.com/us-en/data-services-backup-recovery/prev-ontap-restore.html["En savoir plus sur la restauration des données ONTAP à partir de fichiers de sauvegarde"].
