= Charges de travail Microsoft Hyper-V prises en charge en General Availability (GA)
:allow-uri-read: 




=== Charges de travail Microsoft Hyper-V prises en charge en General Availability (GA)

La prise en charge des charges de travail Microsoft Hyper-V est désormais généralement disponible (GA) dans NetApp Backup and Recovery.



=== Charges de travail KVM prises en charge en General Availability (GA)

La prise en charge des charges de travail KVM est désormais généralement disponible (GA) dans NetApp Backup and Recovery.



=== Améliorations des charges de travail Kubernetes

Cette version des charges de travail Kubernetes introduit les fonctionnalités améliorées suivantes :

* *Prise en charge du flux de travail CR* : Vous pouvez désormais effectuer des tâches de protection courantes à l’aide des CR ainsi que de l’interface utilisateur Web Backup and Recovery.
* *Migration de clusters* : Vous pouvez désormais ajouter des clusters Kubernetes existants protégés par Trident Protect à Backup and Recovery.
* *Prise en charge du framework d'alertes* : Vous pouvez désormais recevoir des alertes par e-mail et via l'interface utilisateur pour certains événements de charge de travail Kubernetes.
* *Intégration de l'onglet Restauration* : Vous pouvez désormais accéder aux actions de restauration de charge de travail Kubernetes depuis le menu Restauration.
* *Prise en charge de l'architecture de sauvegarde 3-2-1 fanout* : Vous pouvez désormais utiliser une architecture 3-2-1 fanout dans votre politique de protection lors de la protection des charges de travail Kubernetes.


Pour plus de détails sur la protection des charges de travail Kubernetes, reportez-vous à https://docs.netapp.com/us-en/data-services-backup-recovery/br-use-kubernetes-protect-overview.html["Présentation de la protection des charges de travail Kubernetes"] .



=== Améliorations des charges de travail Oracle Database

Cette version des charges de travail Oracle Database introduit les fonctionnalités améliorées suivantes :

* *Prise en charge des utilisateurs non root* : Les utilisateurs non root peuvent désormais effectuer des opérations de sauvegarde, de restauration et de clonage, améliorant la sécurité et la conformité.
* *Prise en charge du clonage* : Les fonctionnalités de clonage sont désormais prises en charge dans les environnements NAS, SAN et ASM principaux et secondaires en utilisant ASM library v2, permettant des flux de travail de protection coordonnés.
* *Prise en charge du fractionnement des clones* : Vous pouvez désormais fractionner les instantanés inscriptibles (clones) de leurs volumes parents, libérer de l’espace de stockage et permettre des opérations indépendantes.
* *Sauvegarde et restauration pour le stockage d'objets* : Les fonctionnalités natives de sauvegarde et de restauration sont désormais prises en charge pour les cibles de stockage S3 compatibles basées sur des objets.
* *Gestion du cycle de vie des clones (CLM)*: Les opérations d’actualisation des clones sont prises en charge sur le stockage principal.
* *Clonage vers un hôte alternatif* : Vous pouvez désormais cloner des bases de données vers un hôte différent (pour des tests ou de l’analytique) à partir du stockage principal et secondaire.
* *Prise en charge des groupes de cohérence ONTAP* : Les groupes de cohérence ONTAP sont désormais pris en charge, garantissant des instantanés cohérents au niveau des applications sur plusieurs volumes.
* Backup and Recovery prend désormais en charge les architectures de stratégie de protection suivantes pour les charges de travail Oracle Database :
+
** Fanout 3-2-1
** Disque à disque
** Du disque au stockage objet
** En cascade
** Instantané local




Pour plus de détails sur la protection des charges de travail Oracle Database, consultez https://docs.netapp.com/us-en/data-services-backup-recovery/br-use-oracle-protect-overview.html["Présentation de la protection des charges de travail de la base de données Oracle"].
