= Annotation de délai d'expiration du data mover
:allow-uri-read: 




== Annotation de délai d'expiration du data mover

Utilisez l’annotation  `protect.trident.netapp.io/data-mover-timeout-sec` pour définir un délai d’expiration par opération du data mover (en secondes) lors de la sauvegarde et de la restauration. Elle spécifie la durée pendant laquelle un data mover attend qu’une opération progresse avant d’expirer. Ceci est utile pour détecter et gérer les transferts bloqués (par exemple, lorsque des problèmes réseau empêchent la progression de la restauration des données d’un volume).

Vous pouvez utiliser cette annotation dans votre fichier YAML comme indiqué ci-dessous :

[source, yaml]
----
---
apiVersion: protect.trident.netapp.io/v1
kind: BackupRestore
metadata:
  name: bkp-restore-kopia
  namespace: trident-protect
  annotations: # Optional annotations to configure data movement timeout
    protect.trident.netapp.io/data-mover-timeout-sec: "2"
spec:
  appVaultRef: appvault-name
  appArchivePath: my-backup-path
  namespaceMapping: [{"source": "my-source-namespace", "destination": "my-destination-namespace"}]
  storageClassMapping:
    destination: "${destinationStorageClass}"
    source: "${sourceStorageClass}"
----
Dans cet exemple, l'annotation fait échouer l' `BackupRestore`opération si aucune progression n'a lieu dans les 2 secondes lors de l'opération de restauration.


NOTE: Si la valeur de l'annotation est inférieure ou égale à 0, l'opération échouera immédiatement.
