= Annotations et étiquettes d'espace de noms lors des opérations de restauration et de basculement
:allow-uri-read: 




== Annotations et étiquettes d'espace de noms lors des opérations de restauration et de basculement

Lors de la restauration et du basculement, les étiquettes et annotations de l'espace de noms de destination sont mises à jour pour correspondre à la source : les clés de la source sont ajoutées ou remplacent les clés de destination, tandis que les clés qui existent uniquement dans la destination restent inchangées.


NOTE: Dans Red Hat OpenShift, les annotations d'espace de noms sont importantes car elles garantissent que les pods restaurés reçoivent les contraintes et autorisations de contexte de sécurité appropriées, leur permettant ainsi d'accéder aux volumes et de s'exécuter sans erreurs d'autorisation. Pour plus d'informations, consultez la link:https://docs.redhat.com/en/documentation/openshift_container_platform/4.20/html/authentication_and_authorization/managing-pod-security-policies["Documentation des contraintes de contexte de sécurité OpenShift"^].

Définissez la variable d'environnement Kubernetes

[listing]
----
RESTORE_SKIP_NAMESPACE_ANNOTATIONS
----
avant la restauration ou le basculement pour éviter que des annotations spécifiques de l’espace de noms de destination ne soient écrasées. Par exemple :

[source, console]
----
helm upgrade trident-protect -n trident-protect netapp-trident-protect/trident-protect \
  --set-string restoreSkipNamespaceAnnotations="{<annotation_key_to_skip_1>,<annotation_key_to_skip_2>}" \
  --reuse-values
----

NOTE: Lors d'une restauration ou d'un basculement, les annotations et étiquettes d'espace de noms spécifiées dans  `restoreSkipNamespaceAnnotations` et  `restoreSkipNamespaceLabels` sont exclues de l'opération de restauration ou de basculement. Assurez-vous que ces paramètres sont configurés lors de l'installation initiale de Helm. Pour en savoir plus, consultez  https://docs.netapp.com/us-en/trident/trident-protect/trident-protect-customize-installation.html#configure-additional-trident-protect-helm-chart-settings["Configurer des paramètres supplémentaires du chart Helm Trident Protect"].

Si vous avez utilisé Helm avec le  `--create-namespace` paramètre pour installer l’application source, Trident Protect copie l’étiquette name dans l’espace de noms de destination. Si la valeur de l’étiquette correspond au nom de l’espace de noms source, elle est remplacée par celui de l’espace de noms de destination ; sinon, elle est conservée.



=== Exemple

L'exemple suivant montre les espaces de noms source et de destination avec des étiquettes et des annotations différentes, et affiche l'espace de noms de destination avant et après l'opération pour illustrer comment les clés sont ajoutées, fusionnées ou écrasées.



==== Avant l'opération de restauration ou de basculement

Le tableau suivant illustre l'état des espaces de noms source et de destination de l'exemple avant l'opération de restauration ou de basculement :

[cols="1,2a,2a"]
|===
| Espace de noms | Annotations | Étiquettes 


| Espace de noms ns-1 (source)  a| 
* annotation.one/key: "updatedvalue"
* annotation.two/key: "true"

 a| 
* environment=production
* conformité=hipaa
* name=ns-1




| Espace de noms ns-2 (destination)  a| 
* annotation.one/key: "true"
* annotation.three/key: "false"

 a| 
* rôle=base de données


|===


==== Après l'opération de restauration

Le tableau suivant illustre l'état de l'espace de noms de destination après l'opération de restauration ou de basculement. Certaines clés ont été ajoutées, d'autres ont été écrasées, et l' `name`étiquette a été mise à jour pour correspondre à l'espace de noms de destination :

[cols="1,2a,2a"]
|===
| Espace de noms | Annotations | Étiquettes 


| Espace de noms ns-2 (destination)  a| 
* annotation.one/key: "updatedvalue"
* annotation.two/key: "true"
* annotation.three/key: "false"

 a| 
* name=ns-2
* conformité=hipaa
* environment=production
* rôle=base de données


|===